ALTER TABLE AWARD
ADD CONSTRAINT PK_AWARD
PRIMARY KEY (AWARD_ID)
/

ALTER TABLE AWARD_DOCUMENT
ADD CONSTRAINT PK_AWARD_DOCUMENT
PRIMARY KEY (DOCUMENT_NUMBER)
/

ALTER TABLE PROTOCOL_TYPE 
ADD CONSTRAINT PK_PROTOCOL_TYPE 
PRIMARY KEY (PROTOCOL_TYPE_CODE)
/

ALTER TABLE PROTOCOL_STATUS 
ADD CONSTRAINT PK_PROTOCOL_STATUS 
PRIMARY KEY (PROTOCOL_STATUS_CODE)
/

ALTER TABLE PROTOCOL 
ADD CONSTRAINT PK_PROTOCOL 
PRIMARY KEY (PROTOCOL_NUMBER, SEQUENCE_NUMBER)
/

ALTER TABLE AWARD_IDC_RATE 
ADD CONSTRAINT PK_AWARD_IDC_RATE 
PRIMARY KEY (AWARD_IDC_RATE_ID)
/

ALTER TABLE IDC_RATE_TYPE 
ADD CONSTRAINT PK_IDC_RATE_TYPE_CODE 
PRIMARY KEY (IDC_RATE_TYPE_CODE)
/

ALTER TABLE VULNERABLE_SUBJECT_TYPE 
ADD CONSTRAINT PK_VULNERABLE_SUBJECT_TYPE 
PRIMARY KEY (VULNERABLE_SUBJECT_TYPE_CODE)
;

ALTER TABLE PROTOCOL_VULNERABLE_SUB 
ADD CONSTRAINT PK_PROTOCOL_VULNERABLE_SUB 
PRIMARY KEY (PROTOCOL_ID, VULNERABLE_SUBJECT_TYPE_CODE)
;

ALTER TABLE VALID_RATES 
ADD CONSTRAINT PK_VALID_RATES 
PRIMARY KEY (VALID_RATES_ID)
/

ALTER TABLE PROTOCOL_RESEARCH_AREAS 
ADD CONSTRAINT PK_PROTOCOL_RESEARCH_AREAS 
PRIMARY KEY (PROTOCOL_ID, RESEARCH_AREA_CODE)  
/  

ALTER TABLE RISK_LEVEL 
ADD CONSTRAINT PK_RISK_LEVEL 
PRIMARY KEY (RISK_LEVEL_CODE)
/

ALTER TABLE PROTOCOL_RISK_LEVELS 
ADD CONSTRAINT PK_PROTOCOL_RISK_LEVELS 
PRIMARY KEY (PROTOCOL_RISK_LEVELS_ID)
/

