DELIMITER /
CREATE TABLE FIN_IDC_TYPE_CODE
  ( 
    FIN_IDC_CODE varchar(5) not null,
    RATE_TYPE_CODE varchar(3) not null,
    OBJ_ID VARCHAR(36),
    VER_NBR DECIMAL(8,0) NOT NULL,
    RATE_CLASS_CODE VARCHAR(3) not null
  ) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_bin;
/
ALTER TABLE FIN_IDC_TYPE_CODE
    ADD CONSTRAINT PK_IDC_CODE
    PRIMARY KEY (RATE_CLASS_CODE, RATE_TYPE_CODE)
/
DELIMITER ;
