
CREATE OR REPLACE VIEW osp$eps_prop_investigators ( 

 	   PROPOSAL_NUMBER, PERSON_ID, PERSON_NAME, PRINCIPAL_INVESTIGATOR_FLAG, FACULTY_FLAG, 
	   NON_MIT_PERSON_FLAG, CONFLICT_OF_INTEREST_FLAG, PERCENTAGE_EFFORT, FEDR_DEBR_FLAG, FEDR_DELQ_FLAG, UPDATE_TIMESTAMP, UPDATE_USER) 
	   AS select 
	   PROPOSAL_NUMBER, cast(decode(PERSON_ID,null,ROLODEX_ID,PERSON_ID) as varchar2(10)) PERSON_ID, FULL_NAME, 
	   decode(PROP_PERSON_ROLE_ID,'PI','Y','N') PRINCIPAL_INVESTIGATOR_FLAG, IS_FACULTY, 
	   decode(PERSON_ID,null,'N','Y') NON_MIT_PERSON_FLAG,CONFLICT_OF_INTEREST_FLAG, PERCENTAGE_EFFORT, 
	   FEDR_DEBR_FLAG, FEDR_DELQ_FLAG, UPDATE_TIMESTAMP, UPDATE_USER
	from EPS_PROP_PERSON WHERE PROP_PERSON_ROLE_ID in ('PI','COI')
