insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,1,5,1,'Y',0,0,sysdate,'kradev');

insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,1,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,1,2,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,2,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,2,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,3,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,3,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,4,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,4,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,5,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,5,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,6,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,6,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,7,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,8,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,9,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,10,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,10,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,10,8,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,11,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,1,12,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,1,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,1,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,2,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,2,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,3,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,3,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,4,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,4,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,5,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,5,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,6,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,6,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,7,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,8,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,9,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,10,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,10,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,10,8,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,11,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,2,12,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,1,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,1,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,2,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,2,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,3,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,3,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,4,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,4,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,5,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,5,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,6,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,6,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,7,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,8,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,9,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,10,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,10,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,10,8,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,11,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,3,12,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,1,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,1,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,2,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,2,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,3,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,3,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,4,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,4,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,5,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,5,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,6,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,6,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,7,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,8,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,9,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,10,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,10,5,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,10,8,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,11,1,1,'Y',0,0,sysdate,'kradev');
insert into budget_details_cal_amts (PROPOSAL_NUMBER,VERSION_NUMBER,BUDGET_PERIOD,LINE_ITEM_NUMBER,RATE_CLASS_CODE,RATE_TYPE_CODE,APPLY_RATE_FLAG,CALCULATED_COST,CALCULATED_COST_SHARING,UPDATE_TIMESTAMP,UPDATE_USER) values (
999999,1,4,12,1,1,'Y',0,0,sysdate,'kradev');



update BUDGET_DETAILS_CAL_AMTS set CALCULATED_COST = 1000, CALCULATED_COST_SHARING = 1000 where BUDGET_PERIOD=1;
update BUDGET_DETAILS_CAL_AMTS set CALCULATED_COST = 2000, CALCULATED_COST_SHARING = 2000 where BUDGET_PERIOD=2;
update BUDGET_DETAILS_CAL_AMTS set CALCULATED_COST = 3000, CALCULATED_COST_SHARING = 3000 where BUDGET_PERIOD=3;
update BUDGET_DETAILS_CAL_AMTS set CALCULATED_COST = 4000, CALCULATED_COST_SHARING = 4000 where BUDGET_PERIOD=4;
