DELETE FROM PROTOCOL_CORRESPONDENCE;
DELETE FROM PROTOCOL_ACTIONS;
DELETE FROM PROTOCOL_ATTACHMENT_PERSONNEL;
DELETE FROM PROTOCOL_ATTACHMENT_PROTOCOL;
DELETE FROM PROTOCOL_PERSONS;
--DELETE FROM PROTOCOL_PERSON_ROLE_MAPPING;
--DELETE FROM PROTOCOL_PERSON_ROLES;
DELETE FROM PROTOCOL_VULNERABLE_SUB;
DELETE FROM PROTOCOL_LOCATION;
DELETE FROM PROTOCOL_NOTEPAD;
DELETE FROM PROTOCOL_EXEMPT_CHKLST;
DELETE FROM PROTOCOL_EXEMPT_NUMBER;
DELETE FROM PROTOCOL_EXPIDITED_CHKLST;
DELETE FROM PROTOCOL_FUNDING_SOURCE;
DELETE FROM PROTOCOL_SPECIAL_REVIEW;
DELETE FROM PROTOCOL_REFERENCES;
DELETE FROM PROTOCOL_RESEARCH_AREAS;
DELETE FROM PROTOCOL_REVIEWERS;
DELETE FROM PROTOCOL_RISK_LEVELS;
DELETE FROM PROTOCOL_SUBMISSION_DOC;
DELETE FROM PROTOCOL_SUBMISSION;
DELETE FROM PROTOCOL_VOTE_ABSTAINEES;
DELETE FROM PROTOCOL;
DELETE FROM PROTOCOL_STATUS; 
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(100, 'Pending/In Progress', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(101, 'Submitted to IRB', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(102, 'Specific Minor Revisions Required', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(103, 'Deferred', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(104, 'Substantive Revisions Required', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(105, 'Amendment in Progress', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(106, 'Renewal in Progress', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(200, 'Active - Open to Enrollment', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(201, 'Active - Closed to Enrollment', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(202, 'Active - Data Analysis Only', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(203, 'Exempt', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(300, 'Closed Administratively for lack of response', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(301, 'Closed by Investigator', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(302, 'Suspended by Investigator', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(303, 'Do Not Use - delete later - Terminated by Investigator', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(304, 'Withdrawn', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(305, 'Expired', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(306, 'Disapproved', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(307, 'Terminated by IRB', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(308, 'Suspended by IRB', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(309, 'Not Human Subjects Research', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(310, 'IRB review not required', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(311, 'Suspended by DSMB', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(400, 'Amendment Incorportated into Protocol', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_STATUS
(PROTOCOL_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
Values
(401, 'Renewal Incorporated into Protocol', to_date('2007-12-20 13:25:59','YYYY-MM-DD HH24:MI:SS'), 'COEUS');
