INSERT INTO PROTOCOL_REVIEWER_TYPE (REVIEWER_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1', 'primary', sysdate, 'KRADEV');
INSERT INTO PROTOCOL_REVIEWER_TYPE (REVIEWER_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2', 'secondary', sysdate, 'KRADEV');
