INSERT INTO ACCOUNT_TYPE ( ACCOUNT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 1, 'Regular', sysdate, user ); 
INSERT INTO ACCOUNT_TYPE ( ACCOUNT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 2, 'Fabricated Equipment', sysdate, user ); 
INSERT INTO ACCOUNT_TYPE ( ACCOUNT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 3, 'Draper Fellowship', sysdate, user ); 
INSERT INTO ACCOUNT_TYPE ( ACCOUNT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 4, 'Core Grant Administration', sysdate, user ); 
INSERT INTO ACCOUNT_TYPE ( ACCOUNT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 5, 'Gift', sysdate, user ); 
INSERT INTO ACCOUNT_TYPE ( ACCOUNT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 6, 'Conversion Account', sysdate, user ); 
INSERT INTO ACCOUNT_TYPE ( ACCOUNT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 7, 'Off-campus account', sysdate, user ); 
INSERT INTO ACCOUNT_TYPE ( ACCOUNT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 8, 'SBIR', sysdate, user ); 
INSERT INTO ACCOUNT_TYPE ( ACCOUNT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 9, 'STTR', sysdate, user ); 
INSERT INTO ACCOUNT_TYPE ( ACCOUNT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 10, 'No Account', sysdate, user ); 
INSERT INTO ACCOUNT_TYPE ( ACCOUNT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 11, 'Service Facilities', sysdate, user ); 
