INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1', 'Full', sysdate,'KRADEV');
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2', 'Expedited', sysdate,'KRADEV');
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3', 'Exempt', sysdate,'KRADEV');
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4', 'Limited/Single Use', sysdate,'KRADEV');
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5', 'IRB Review not required', sysdate,'KRADEV');
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('6', 'Response', sysdate,'KRADEV');
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('7', 'FYI', sysdate,'KRADEV');
