DELETE FROM PROTOCOL_VULNERABLE_SUB;
DELETE FROM PROTOCOL_ACTIONS;
DELETE FROM PROTOCOL_ATTACHMENT_PERSONNEL;
DELETE FROM PROTOCOL_PERSONS;
DELETE FROM PROTOCOL_LOCATION;
DELETE FROM PROTOCOL_SPECIAL_REVIEW;
DELETE FROM PROTOCOL; 
DELETE FROM PROTOCOL_TYPE;
Insert into PROTOCOL_TYPE
   (PROTOCOL_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
 Values
   (1, 'Standard', TO_DATE('12/20/2007 13:25:59', 'MM/DD/YYYY HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_TYPE
   (PROTOCOL_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
 Values
   (2, 'Emergency Use', TO_DATE('12/20/2007 13:25:59', 'MM/DD/YYYY HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_TYPE
   (PROTOCOL_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
 Values
   (3, 'Humanitarian Use Device (HUD)', TO_DATE('12/20/2007 13:25:59', 'MM/DD/YYYY HH24:MI:SS'), 'COEUS');
Insert into PROTOCOL_TYPE
   (PROTOCOL_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
 Values
   (4, 'Exempt', TO_DATE('12/20/2007 13:25:59', 'MM/DD/YYYY HH24:MI:SS'), 'COEUS');