INSERT INTO PROTOCOL_ATTACHMENT_GROUP ( GROUP_CD, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 1, 'Protocol Attachments', sysdate, user ); 
INSERT INTO PROTOCOL_ATTACHMENT_GROUP ( GROUP_CD, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 2, 'Personnel Attachments', sysdate, user );