CREATE TABLE CFDA (
    CFDA_NBR VARCHAR2(7) NOT NULL,
    CFDA_PGM_TTL_NM varchar2(300) NOT NULL,
    CFDA_MAINT_TYP_ID varchar2(10),
    ACTIVE_FLAG VARCHAR2(1) NOT NULL,
    VER_NBR NUMBER(8) default 1 NOT NULL,
    OBJ_ID VARCHAR2(36) NOT NULL
);
ALTER TABLE CFDA
    ADD CONSTRAINT CFDA_NBR
PRIMARY KEY (CFDA_NBR);