-- Foreign Key Constraint(s) 
ALTER TABLE PROTO_NOTIFICATION_TEMPL 
    ADD CONSTRAINT FK_PROTO_NOTIFICATION_TEMPL 
            FOREIGN KEY (ACTION_TYPE_CODE) 
                REFERENCES PROTOCOL_ACTION_TYPE (PROTOCOL_ACTION_TYPE_CODE) ;