DELIMITER /
 CREATE TABLE BUDGET_CHANGED_DATA(
  PROPOSAL_NUMBER VARCHAR(8), 
	COLUMN_NAME VARCHAR(30),
	CHANGE_NUMBER DECIMAL(3,0),
	CHANGED_VALUE VARCHAR(200),
	DISPLAY_VALUE VARCHAR(200),
	OLD_DISPLAY_VALUE VARCHAR(200),
	COMMENTS VARCHAR(300),
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USER VARCHAR(60) NOT NULL,
	VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL,
	OBJ_ID VARCHAR(36) NOT NULL
  ) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_bin
/
ALTER TABLE BUDGET_CHANGED_DATA ADD CONSTRAINT PK_BUDGET_CHANGED_DATA
PRIMARY KEY (PROPOSAL_NUMBER, COLUMN_NAME, CHANGE_NUMBER)
/
DELIMITER ;
