DELIMITER /
CREATE TABLE IACUC_PROTOCOL_UNITS ( 
    IACUC_PROTOCOL_UNITS_ID DECIMAL(12,0) NOT NULL, 
    IACUC_PROT_INVESTIGATORS_ID DECIMAL(12,0) NOT NULL, 
    PROTOCOL_NUMBER VARCHAR(20) NOT NULL, 
    SEQUENCE_NUMBER DECIMAL(4,0) NOT NULL, 
    UNIT_NUMBER VARCHAR(8) NOT NULL, 
    LEAD_UNIT_FLAG VARCHAR(1) NOT NULL, 
    PERSON_ID VARCHAR(40) NOT NULL, 
    UPDATE_TIMESTAMP DATE, 
    UPDATE_USER VARCHAR(60), 
    VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR(36) NOT NULL) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_bin
/


ALTER TABLE IACUC_PROTOCOL_UNITS 
ADD CONSTRAINT PK_IACUC_PROTOCOL_UNITS 
PRIMARY KEY (IACUC_PROTOCOL_UNITS_ID) 
/
DELIMITER ;
