DELIMITER /
CREATE TABLE VALID_IACUC_PROTO_SUB_REV_TYPE 
   (	VALID_PROTO_SUB_REV_TYPE_ID DECIMAL(12,0), 
	SUBMISSION_TYPE_CODE VARCHAR(3) NOT NULL, 
	PROTOCOL_REVIEW_TYPE_CODE DECIMAL(3,0) NOT NULL, 
	UPDATE_TIMESTAMP DATE NOT NULL, 
	UPDATE_USER VARCHAR(60) NOT NULL, 
	VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, 
	OBJ_ID VARCHAR(36) NOT NULL) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_bin
/
ALTER TABLE VALID_IACUC_PROTO_SUB_REV_TYPE 
ADD CONSTRAINT PK_VALID_AC_PROTO_SUB_REV_TYPE 
PRIMARY KEY (VALID_PROTO_SUB_REV_TYPE_ID)
/
DELIMITER ;
