DELIMITER /
CREATE TABLE IACUC_PRINCIPLES ( 
    IACUC_PRINCIPLES_ID DECIMAL(12,0) NOT NULL, 
    PROTOCOL_ID DECIMAL(12,0) NOT NULL,
    PROTOCOL_NUMBER VARCHAR(20),
    SEQUENCE_NUMBER DECIMAL(4,0) DEFAULT 1 NOT NULL,    
    REDUCTION VARCHAR(2000),
    REFINEMENT VARCHAR(2000),
    REPLACEMENT VARCHAR(2000),
    EXCEPTIONS_PRESENT VARCHAR(1) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR(60) NOT NULL, 
    VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR(36) NOT NULL) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_bin
/

ALTER TABLE IACUC_PRINCIPLES 
ADD CONSTRAINT PK_IACUC_PRINCIPLES
PRIMARY KEY (IACUC_PRINCIPLES_ID) 
/
DELIMITER ;
