-- Add reference to AWARD table
ALTER TABLE AWARD_PERSONS ADD CONSTRAINT FK_AWARD_AWARD_PERSONS FOREIGN KEY (AWARD_ID) REFERENCES AWARD(AWARD_ID);

-- Add reference to EPS_PROPOSAL_PERSON_ROLE table
ALTER TABLE AWARD_PERSONS ADD CONSTRAINT FK_PROP_PERS_ROLE_AWD_PERSONS FOREIGN KEY (CONTACT_ROLE_CODE) REFERENCES EPS_PROP_PERSON_ROLE(PROP_PERSON_ROLE_ID);