delimiter /
TRUNCATE TABLE PROTOCOL_REVIEWER_TYPE
/
INSERT INTO PROTOCOL_REVIEWER_TYPE (REVIEWER_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','primary','admin',NOW(),UUID(),1)
/
INSERT INTO PROTOCOL_REVIEWER_TYPE (REVIEWER_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','secondary','admin',NOW(),UUID(),1)
/
delimiter ;
