delimiter /
TRUNCATE TABLE EPS_PROP_COLUMNS_TO_ALTER
/
INSERT INTO EPS_PROP_COLUMNS_TO_ALTER (COLUMN_NAME,COLUMN_LABEL,DATA_TYPE,DATA_LENGTH,HAS_LOOKUP,LOOKUP_ARGUMENT,LOOKUP_RETURN,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('ACTIVITY_TYPE_CODE','Activity Type','STRING',3,'Y','org.kuali.kra.proposaldevelopment.bo.ActivityType','description','admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_COLUMNS_TO_ALTER (COLUMN_NAME,COLUMN_LABEL,DATA_TYPE,DATA_LENGTH,HAS_LOOKUP,LOOKUP_ARGUMENT,LOOKUP_RETURN,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('DEADLINE_DATE','Sponsor Deadline Date','DATE',10,'N',null,null,'admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_COLUMNS_TO_ALTER (COLUMN_NAME,COLUMN_LABEL,DATA_TYPE,DATA_LENGTH,HAS_LOOKUP,LOOKUP_ARGUMENT,LOOKUP_RETURN,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('DEADLINE_TYPE','Deadline Type','STRING',1,'Y','org.kuali.kra.proposaldevelopment.bo.DeadlineType','description','admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_COLUMNS_TO_ALTER (COLUMN_NAME,COLUMN_LABEL,DATA_TYPE,DATA_LENGTH,HAS_LOOKUP,LOOKUP_ARGUMENT,LOOKUP_RETURN,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('MAILING_ADDRESS_ID','Mailing Address','NUMBER',22,'Y','org.kuali.kra.bo.Rolodex','organization','admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_COLUMNS_TO_ALTER (COLUMN_NAME,COLUMN_LABEL,DATA_TYPE,DATA_LENGTH,HAS_LOOKUP,LOOKUP_ARGUMENT,LOOKUP_RETURN,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NOTICE_OF_OPPORTUNITY_CODE','Notice of Opportunity','NUMBER',3,'Y','org.kuali.kra.bo.NoticeOfOpportunity','description','admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_COLUMNS_TO_ALTER (COLUMN_NAME,COLUMN_LABEL,DATA_TYPE,DATA_LENGTH,HAS_LOOKUP,LOOKUP_ARGUMENT,LOOKUP_RETURN,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('PROGRAM_ANNOUNCEMENT_NUMBER','Program Number','STRING',50,'N',null,null,'admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_COLUMNS_TO_ALTER (COLUMN_NAME,COLUMN_LABEL,DATA_TYPE,DATA_LENGTH,HAS_LOOKUP,LOOKUP_ARGUMENT,LOOKUP_RETURN,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('PROGRAM_ANNOUNCEMENT_TITLE','Program Title','STRING',255,'N',null,null,'admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_COLUMNS_TO_ALTER (COLUMN_NAME,COLUMN_LABEL,DATA_TYPE,DATA_LENGTH,HAS_LOOKUP,LOOKUP_ARGUMENT,LOOKUP_RETURN,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('PROPOSAL_TYPE_CODE','Proposal Type','NUMBER',3,'Y','org.kuali.kra.proposaldevelopment.bo.ProposalType','description','admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_COLUMNS_TO_ALTER (COLUMN_NAME,COLUMN_LABEL,DATA_TYPE,DATA_LENGTH,HAS_LOOKUP,LOOKUP_ARGUMENT,LOOKUP_RETURN,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('TITLE','Title','STRING',150,'N',null,null,'admin',NOW(),UUID(),1)
/
delimiter ;
