delimiter /
TRUNCATE TABLE FREQUENCY_BASE
/
INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','Execution Date','admin',NOW(),UUID(),1)
/
INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','Project Start Date','admin',NOW(),UUID(),1)
/
INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('3','Obligation End Date','admin',NOW(),UUID(),1)
/
INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('4','Project End Date','admin',NOW(),UUID(),1)
/
INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('5','Obligation Start Date','admin',NOW(),UUID(),1)
/
INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('6','As Required','admin',NOW(),UUID(),1)
/
delimiter ;
