delimiter /
TRUNCATE TABLE CARRIER_TYPE
/
INSERT INTO CARRIER_TYPE (CARRIER_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','Regular','admin',NOW(),UUID(),1)
/
INSERT INTO CARRIER_TYPE (CARRIER_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','DHL','admin',NOW(),UUID(),1)
/
INSERT INTO CARRIER_TYPE (CARRIER_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('3','Electronic','admin',NOW(),UUID(),1)
/
delimiter ;
