delimiter /
TRUNCATE TABLE PROTOCOL_PERSON_ROLE_MAPPING
/
INSERT INTO SEQ_PROTOCOL_ID VALUES (null)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT MAX(ID) FROM SEQ_PROTOCOL_ID),'PI','COI','admin',NOW(),UUID(),1)
/
INSERT INTO SEQ_PROTOCOL_ID VALUES (null)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT MAX(ID) FROM SEQ_PROTOCOL_ID),'COI','PI','admin',NOW(),UUID(),1)
/
INSERT INTO SEQ_PROTOCOL_ID VALUES (null)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT MAX(ID) FROM SEQ_PROTOCOL_ID),'SP','CA','admin',NOW(),UUID(),1)
/
INSERT INTO SEQ_PROTOCOL_ID VALUES (null)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT MAX(ID) FROM SEQ_PROTOCOL_ID),'SP','CRC','admin',NOW(),UUID(),1)
/
INSERT INTO SEQ_PROTOCOL_ID VALUES (null)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT MAX(ID) FROM SEQ_PROTOCOL_ID),'CA','SP','admin',NOW(),UUID(),1)
/
INSERT INTO SEQ_PROTOCOL_ID VALUES (null)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT MAX(ID) FROM SEQ_PROTOCOL_ID),'CA','CRC','admin',NOW(),UUID(),1)
/
INSERT INTO SEQ_PROTOCOL_ID VALUES (null)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT MAX(ID) FROM SEQ_PROTOCOL_ID),'CRC','SP','admin',NOW(),UUID(),1)
/
INSERT INTO SEQ_PROTOCOL_ID VALUES (null)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT MAX(ID) FROM SEQ_PROTOCOL_ID),'CRC','CA','admin',NOW(),UUID(),1)
/
delimiter ;
