delimiter /
TRUNCATE TABLE IDC_RATE_TYPE
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (1,'MTDC','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (2,'TDC- DO NOT USE','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (3,'Other','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (4,'None','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (5,'RESMN','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (6,'RESMF','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (7,'EXCLU','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (8,'RESEB','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (9,'RESMFF','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (10,'FUNSN','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (11,'FUNNX','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (12,'FUNSNX','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (13,'FUNSAX','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (14,'FUNNXF','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (15,'FUNMNX','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (16,'FUNMFX','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (17,'SLNSN','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (18,'SLNMN','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (19,'SLNMF','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (20,'GENSN','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (21,'GENSNF','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (22,'RESSN','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (23,'FUNSAN','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (24,'FUNFN','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (25,'RESTDC','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (26,'FUNTDC','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (27,'RESTG','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (28,'RESTDE','admin',NOW(),UUID(),1)
/
INSERT INTO IDC_RATE_TYPE (IDC_RATE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (29,'BIMN','admin',NOW(),UUID(),1)
/
delimiter ;
