delimiter /
TRUNCATE TABLE AFFILIATION_TYPE
/
INSERT INTO AFFILIATION_TYPE (AFFILIATION_TYPE_CODE,DESCRIPTION,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (1,'Faculty','Y','admin',NOW(),UUID(),1)
/
INSERT INTO AFFILIATION_TYPE (AFFILIATION_TYPE_CODE,DESCRIPTION,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (2,'Non-Faculty','Y','admin',NOW(),UUID(),1)
/
INSERT INTO AFFILIATION_TYPE (AFFILIATION_TYPE_CODE,DESCRIPTION,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (3,'Affiliate','Y','admin',NOW(),UUID(),1)
/
INSERT INTO AFFILIATION_TYPE (AFFILIATION_TYPE_CODE,DESCRIPTION,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (4,'Student Investigator','Y','admin',NOW(),UUID(),1)
/
INSERT INTO AFFILIATION_TYPE (AFFILIATION_TYPE_CODE,DESCRIPTION,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (5,'Faculty Supervisor','Y','admin',NOW(),UUID(),1)
/
delimiter ;
