delimiter /
TRUNCATE TABLE EPS_PROP_PER_DOC_TYPE
/
INSERT INTO EPS_PROP_PER_DOC_TYPE (DOCUMENT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','Biosketch','admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_PER_DOC_TYPE (DOCUMENT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','Currentpending','admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_PER_DOC_TYPE (DOCUMENT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('3','Budget Details','admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_PER_DOC_TYPE (DOCUMENT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('4','Statement of Commitment ','admin',NOW(),UUID(),1)
/
INSERT INTO EPS_PROP_PER_DOC_TYPE (DOCUMENT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('5','Other','admin',NOW(),UUID(),1)
/
delimiter ;
