delimiter /
TRUNCATE TABLE APPOINTMENT_TYPE
/
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','TEMPORARY EMPLOYEE',1,'admin',NOW(),UUID(),1)
/
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','SUMMER EMPLOYEE',3,'admin',NOW(),UUID(),1)
/
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('3','9M DURATION',9,'admin',NOW(),UUID(),1)
/
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('4','10M DURATION',10,'admin',NOW(),UUID(),1)
/
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('5','11M DURATION',11,'admin',NOW(),UUID(),1)
/
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('6','12M DURATION',12,'admin',NOW(),UUID(),1)
/
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('7','REGULAR EMPLOYEE',12,'admin',NOW(),UUID(),1)
/
delimiter ;
