delimiter /
TRUNCATE TABLE CORRESPONDENT_TYPE
/
INSERT INTO CORRESPONDENT_TYPE (CORRESPONDENT_TYPE_CODE,DESCRIPTION,QUALIFIER,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','Administrator','P','admin',NOW(),UUID(),1)
/
INSERT INTO CORRESPONDENT_TYPE (CORRESPONDENT_TYPE_CODE,DESCRIPTION,QUALIFIER,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','CRC','P','admin',NOW(),UUID(),1)
/
delimiter ;
