delimiter /
TRUNCATE TABLE VALID_PROTO_SUB_TYPE_QUAL
/
INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (SUBMISSION_TYPE_CODE,SUBMISSION_TYPE_QUAL_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_TYPE_QUAL_ID,VER_NBR)
  VALUES ('112','1',STR_TO_DATE( '20110221133454', '%Y%m%d%H%i%s' ),'KRADEV',86,1)
/
INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (SUBMISSION_TYPE_CODE,SUBMISSION_TYPE_QUAL_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_TYPE_QUAL_ID,VER_NBR)
  VALUES ('112','8',STR_TO_DATE( '20110221133454', '%Y%m%d%H%i%s' ),'KRADEV',87,1)
/
INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (SUBMISSION_TYPE_CODE,SUBMISSION_TYPE_QUAL_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_TYPE_QUAL_ID,VER_NBR)
  VALUES ('112','9',STR_TO_DATE( '20110221133454', '%Y%m%d%H%i%s' ),'KRADEV',88,1)
/
INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (SUBMISSION_TYPE_CODE,SUBMISSION_TYPE_QUAL_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_TYPE_QUAL_ID,VER_NBR)
  VALUES ('112','12',STR_TO_DATE( '20110221133454', '%Y%m%d%H%i%s' ),'KRADEV',89,1)
/
INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (SUBMISSION_TYPE_CODE,SUBMISSION_TYPE_QUAL_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_TYPE_QUAL_ID,VER_NBR)
  VALUES ('112','13',STR_TO_DATE( '20110221133454', '%Y%m%d%H%i%s' ),'KRADEV',90,1)
/
INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (SUBMISSION_TYPE_CODE,SUBMISSION_TYPE_QUAL_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_TYPE_QUAL_ID,VER_NBR)
  VALUES ('112','2',STR_TO_DATE( '20110221133454', '%Y%m%d%H%i%s' ),'KRADEV',91,1)
/
INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (SUBMISSION_TYPE_CODE,SUBMISSION_TYPE_QUAL_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_TYPE_QUAL_ID,VER_NBR)
  VALUES ('112','3',STR_TO_DATE( '20110221133454', '%Y%m%d%H%i%s' ),'KRADEV',92,1)
/
delimiter ;
