-- View for Coeus compatibility 
CREATE OR REPLACE VIEW OSP$PROPOSAL_IDC_RATE AS SELECT 
    PROPOSAL_NUMBER, 
    SEQUENCE_NUMBER, 
    APPLICABLE_IDC_RATE, 
    IDC_RATE_TYPE_CODE, 
    FISCAL_YEAR, 
    ON_CAMPUS_FLAG, 
    UNDERRECOVERY_OF_IDC, 
    SOURCE_ACCOUNT, 
    UPDATE_TIMESTAMP, 
    UPDATE_USER
FROM PROPOSAL_IDC_RATE;

