CREATE OR REPLACE VIEW OSP$AWARD_DOCUMENT_TERMS AS 
SELECT AWARD_NUMBER MIT_AWARD_NUMBER,
       SEQUENCE_NUMBER SEQUENCE_NUMBER,
       SPONSOR_TERM_ID EQUIPMENT_APPROVAL_CODE,
       UPDATE_TIMESTAMP UPDATE_TIMESTAMP,
       UPDATE_USER UPDATE_USER
FROM   AWARD_SPONSOR_TERM
WHERE  EXISTS (SELECT SPONSOR_TERM_TYPE_CODE
               FROM   SPONSOR_TERM
               WHERE  AWARD_SPONSOR_TERM.SPONSOR_TERM_ID = SPONSOR_TERM.SPONSOR_TERM_ID 
                      AND SPONSOR_TERM_TYPE_CODE = '6') ;
                      
CREATE OR REPLACE VIEW OSP$AWARD_EQUIPMENT_TERMS AS 
SELECT AWARD_NUMBER MIT_AWARD_NUMBER,
       SEQUENCE_NUMBER SEQUENCE_NUMBER,
       SPONSOR_TERM_ID EQUIPMENT_APPROVAL_CODE,
       UPDATE_TIMESTAMP UPDATE_TIMESTAMP,
       UPDATE_USER UPDATE_USER
FROM   AWARD_SPONSOR_TERM
WHERE  EXISTS (SELECT SPONSOR_TERM_TYPE_CODE
               FROM   SPONSOR_TERM
               WHERE  AWARD_SPONSOR_TERM.SPONSOR_TERM_ID = SPONSOR_TERM.SPONSOR_TERM_ID 
                      AND SPONSOR_TERM_TYPE_CODE = '1') ;
                      
CREATE OR REPLACE VIEW OSP$AWARD_INVENTION_TERMS AS 
SELECT AWARD_NUMBER MIT_AWARD_NUMBER,
       SEQUENCE_NUMBER SEQUENCE_NUMBER,
       SPONSOR_TERM_ID EQUIPMENT_APPROVAL_CODE,
       UPDATE_TIMESTAMP UPDATE_TIMESTAMP,
       UPDATE_USER UPDATE_USER
FROM   AWARD_SPONSOR_TERM
WHERE  EXISTS (SELECT SPONSOR_TERM_TYPE_CODE
               FROM   SPONSOR_TERM
               WHERE  AWARD_SPONSOR_TERM.SPONSOR_TERM_ID = SPONSOR_TERM.SPONSOR_TERM_ID 
                      AND SPONSOR_TERM_TYPE_CODE = '2') ;

CREATE OR REPLACE VIEW OSP$AWARD_PRIOR_APPROVAL_TERMS AS 
SELECT AWARD_NUMBER MIT_AWARD_NUMBER,
       SEQUENCE_NUMBER SEQUENCE_NUMBER,
       SPONSOR_TERM_ID EQUIPMENT_APPROVAL_CODE,
       UPDATE_TIMESTAMP UPDATE_TIMESTAMP,
       UPDATE_USER UPDATE_USER
FROM   AWARD_SPONSOR_TERM
WHERE  EXISTS (SELECT SPONSOR_TERM_TYPE_CODE
               FROM   SPONSOR_TERM
               WHERE  AWARD_SPONSOR_TERM.SPONSOR_TERM_ID = SPONSOR_TERM.SPONSOR_TERM_ID 
                      AND SPONSOR_TERM_TYPE_CODE = '3') ;

CREATE OR REPLACE VIEW OSP$AWARD_PROPERTY_TERMS AS 
SELECT AWARD_NUMBER MIT_AWARD_NUMBER,
       SEQUENCE_NUMBER SEQUENCE_NUMBER,
       SPONSOR_TERM_ID EQUIPMENT_APPROVAL_CODE,
       UPDATE_TIMESTAMP UPDATE_TIMESTAMP,
       UPDATE_USER UPDATE_USER
FROM   AWARD_SPONSOR_TERM
WHERE  EXISTS (SELECT SPONSOR_TERM_TYPE_CODE
               FROM   SPONSOR_TERM
               WHERE  AWARD_SPONSOR_TERM.SPONSOR_TERM_ID = SPONSOR_TERM.SPONSOR_TERM_ID 
                      AND SPONSOR_TERM_TYPE_CODE = '4') ;

CREATE OR REPLACE VIEW OSP$AWARD_PUBLICATION_TERMS AS 
SELECT AWARD_NUMBER MIT_AWARD_NUMBER,
       SEQUENCE_NUMBER SEQUENCE_NUMBER,
       SPONSOR_TERM_ID EQUIPMENT_APPROVAL_CODE,
       UPDATE_TIMESTAMP UPDATE_TIMESTAMP,
       UPDATE_USER UPDATE_USER
FROM   AWARD_SPONSOR_TERM
WHERE  EXISTS (SELECT SPONSOR_TERM_TYPE_CODE
               FROM   SPONSOR_TERM
               WHERE  AWARD_SPONSOR_TERM.SPONSOR_TERM_ID = SPONSOR_TERM.SPONSOR_TERM_ID 
                      AND SPONSOR_TERM_TYPE_CODE = '5') ;

CREATE OR REPLACE VIEW OSP$AWARD_RIGHTS_IN_DATA_TERMS AS 
SELECT AWARD_NUMBER MIT_AWARD_NUMBER,
       SEQUENCE_NUMBER SEQUENCE_NUMBER,
       SPONSOR_TERM_ID EQUIPMENT_APPROVAL_CODE,
       UPDATE_TIMESTAMP UPDATE_TIMESTAMP,
       UPDATE_USER UPDATE_USER
FROM   AWARD_SPONSOR_TERM
WHERE  EXISTS (SELECT SPONSOR_TERM_TYPE_CODE
               FROM   SPONSOR_TERM
               WHERE  AWARD_SPONSOR_TERM.SPONSOR_TERM_ID = SPONSOR_TERM.SPONSOR_TERM_ID 
                      AND SPONSOR_TERM_TYPE_CODE = '7') ;

CREATE OR REPLACE VIEW OSP$AWARD_SUBCONTRACT_TERMS AS 
SELECT AWARD_NUMBER MIT_AWARD_NUMBER,
       SEQUENCE_NUMBER SEQUENCE_NUMBER,
       SPONSOR_TERM_ID EQUIPMENT_APPROVAL_CODE,
       UPDATE_TIMESTAMP UPDATE_TIMESTAMP,
       UPDATE_USER UPDATE_USER
FROM   AWARD_SPONSOR_TERM
WHERE  EXISTS (SELECT SPONSOR_TERM_TYPE_CODE
               FROM   SPONSOR_TERM
               WHERE  AWARD_SPONSOR_TERM.SPONSOR_TERM_ID = SPONSOR_TERM.SPONSOR_TERM_ID 
                      AND SPONSOR_TERM_TYPE_CODE = '8') ;

CREATE OR REPLACE VIEW OSP$AWARD_TRAVEL_TERMS AS 
SELECT AWARD_NUMBER MIT_AWARD_NUMBER,
       SEQUENCE_NUMBER SEQUENCE_NUMBER,
       SPONSOR_TERM_ID EQUIPMENT_APPROVAL_CODE,
       UPDATE_TIMESTAMP UPDATE_TIMESTAMP,
       UPDATE_USER UPDATE_USER
FROM   AWARD_SPONSOR_TERM
WHERE  EXISTS (SELECT SPONSOR_TERM_TYPE_CODE
               FROM   SPONSOR_TERM
               WHERE  AWARD_SPONSOR_TERM.SPONSOR_TERM_ID = SPONSOR_TERM.SPONSOR_TERM_ID 
                      AND SPONSOR_TERM_TYPE_CODE = '9') ;