-- View for Coeus compatibility  
CREATE OR REPLACE VIEW OSP$QUESTIONNAIRE_QUESTIONS AS 
SELECT QUESTIONNAIRE_QUESTIONS.QUESTIONNAIRE_ID,
       QUESTION.QUESTION_ID,
       QUESTIONNAIRE_QUESTIONS.QUESTION_NUMBER,
       QUESTIONNAIRE_QUESTIONS.PARENT_QUESTION_NUMBER,
       QUESTIONNAIRE_QUESTIONS.CONDITION_FLAG,
       QUESTIONNAIRE_QUESTIONS.CONDITION,
       QUESTIONNAIRE_QUESTIONS.CONDITION_VALUE,
       QUESTIONNAIRE_QUESTIONS.UPDATE_TIMESTAMP,
       QUESTIONNAIRE_QUESTIONS.UPDATE_USER,
       QUESTIONNAIRE_QUESTIONS.QUESTION_SEQ_NUMBER
FROM   QUESTIONNAIRE_QUESTIONS,
       QUESTION
WHERE  QUESTION.QUESTION_REF_ID = QUESTIONNAIRE_QUESTIONS.QUESTION_REF_ID_FK;