CREATE OR REPLACE VIEW OSP$RESEARCH_AREAS AS 
SELECT RESEARCH_AREA_CODE,
       PARENT_RESEARCH_AREA_CODE,
       HAS_CHILDREN_FLAG,
       DESCRIPTION,
       UPDATE_TIMESTAMP,
       UPDATE_USER
FROM   RESEARCH_AREAS;