ALTER TABLE AWD_BUDGET_PER_DET_EXT 
    ADD CONSTRAINT FK_AWD_BUDGET_PER_DET_EXT FOREIGN KEY (BUDGET_PERSONNEL_DETAILS_ID) 
                REFERENCES BUDGET_PERSONNEL_DETAILS (BUDGET_PERSONNEL_DETAILS_ID) ;