ALTER TABLE PROTOCOL_UNITS 
    ADD CONSTRAINT FK_PROTOCOL_UNITS 
            FOREIGN KEY (PROTOCOL_INVESTIGATORS_ID) 
                REFERENCES PROTOCOL_INVESTIGATORS (PROTOCOL_INVESTIGATORS_ID) ON DELETE CASCADE;

ALTER TABLE PROTOCOL_UNITS 
    ADD CONSTRAINT FK_PROTOCOL_UNITS_2 FOREIGN KEY (UNIT_NUMBER) 
                REFERENCES UNIT (UNIT_NUMBER) ;