ALTER TABLE PROTOCOL_PERSON_ROLE_MAPPING 
    ADD CONSTRAINT FK_PERSON_SOURCE_ROLE FOREIGN KEY (SOURCE_ROLE_ID) 
                REFERENCES PROTOCOL_PERSON_ROLES (PROTOCOL_PERSON_ROLE_ID) ;

ALTER TABLE PROTOCOL_PERSON_ROLE_MAPPING 
    ADD CONSTRAINT FK_PERSON_TARGET_ROLE FOREIGN KEY (TARGET_ROLE_ID) 
                REFERENCES PROTOCOL_PERSON_ROLES (PROTOCOL_PERSON_ROLE_ID) ;