ALTER TABLE PROTOCOL_ACTIONS 
    ADD CONSTRAINT FK_PROTOCOL_ACTIONS1 FOREIGN KEY (PROTOCOL_ID) 
                REFERENCES PROTOCOL (PROTOCOL_ID) ;

ALTER TABLE PROTOCOL_ACTIONS 
    ADD CONSTRAINT FK_PROTOCOL_ACTIONS2 FOREIGN KEY (SUBMISSION_ID_FK) 
                REFERENCES PROTOCOL_SUBMISSION (SUBMISSION_ID) ;

ALTER TABLE PROTOCOL_ACTIONS 
    ADD CONSTRAINT FK_PROTOCOL_ACTIONS3 FOREIGN KEY (PROTOCOL_ACTION_TYPE_CODE) 
                REFERENCES PROTOCOL_ACTION_TYPE (PROTOCOL_ACTION_TYPE_CODE) ;