ALTER TABLE PROTOCOL_LOCATION 
    ADD CONSTRAINT FK_PROTOCOL_LOCATION FOREIGN KEY (PROTOCOL_ID) 
                REFERENCES PROTOCOL (PROTOCOL_ID) ;

ALTER TABLE PROTOCOL_LOCATION 
    ADD CONSTRAINT FK_PROTOCOL_LOCATION_2 FOREIGN KEY (ORGANIZATION_ID) 
                REFERENCES ORGANIZATION (ORGANIZATION_ID) ;

ALTER TABLE PROTOCOL_LOCATION 
    ADD CONSTRAINT FK_PROTOCOL_LOCATION_3 FOREIGN KEY (PROTOCOL_ORG_TYPE_CODE) 
                REFERENCES PROTOCOL_ORG_TYPE (PROTOCOL_ORG_TYPE_CODE) ;