#created on: Apr 4, 2009
package updateIacucProtocol

#list any import classes here.

import org.kuali.kra.iacuc.actions.submit.IacucProtocolActionUpdateMapping;

import org.kuali.kra.iacuc.actions.submit.IacucProtocolReviewType;
import org.kuali.kra.iacuc.actions.submit.IacucProtocolSubmission;
import org.kuali.kra.iacuc.actions.submit.IacucProtocolSubmissionStatus; 
import org.kuali.kra.iacuc.actions.submit.IacucProtocolSubmissionType;

function void createAuditTrail(IacucProtocolActionUpdateMapping protocolAction) {
	if(protocolAction.getProtocol().getProtocolSubmission() != null) {
		protocolAction.getProtocolAction().setPrevSubmissionStatusCode(protocolAction.getProtocol().getProtocolSubmission().getSubmissionStatusCode());
		protocolAction.getProtocolAction().setSubmissionTypeCode(protocolAction.getProtocol().getProtocolSubmission().getSubmissionTypeCode());
	}
	String currentProtocolStatusCode = protocolAction.getProtocol().getProtocolStatusCode();
    protocolAction.getProtocolAction().setPrevProtocolStatusCode(currentProtocolStatusCode);
}
function void setProtocolSubmissionStatusCode(IacucProtocolActionUpdateMapping protocolAction, String newProtocolSubmissionStatusCode) {
	//TODO Test this with OJB, if you have to find object with new status code and re-attache to protocol submission status???
    protocolAction.getProtocolSubmission().setSubmissionStatusCode(newProtocolSubmissionStatusCode);  
} 
 
function void setNewProtocolSubmission(IacucProtocolActionUpdateMapping protocolAction, String submissionTypeCode, String reviewCode, String submissionStatusCode) {
	IacucProtocolSubmission protocolSubmission = new IacucProtocolSubmission();

	IacucProtocolSubmissionType submissionType = new IacucProtocolSubmissionType();
	submissionType.setSubmissionTypeCode(submissionTypeCode);
	protocolSubmission.setProtocolSubmissionType(submissionType);
	protocolSubmission.setSubmissionTypeCode(submissionTypeCode);
	
	IacucProtocolReviewType protocolReviewType = new IacucProtocolReviewType();
	protocolReviewType.setReviewTypeCode(reviewCode); 
	protocolSubmission.setProtocolReviewType(protocolReviewType);
	protocolSubmission.setProtocolReviewTypeCode(reviewCode);
	
	IacucProtocolSubmissionStatus protocolSubmissionStatus = new IacucProtocolSubmissionStatus();
	protocolSubmissionStatus.setProtocolSubmissionStatusCode(submissionStatusCode);
	protocolSubmission.setSubmissionStatus(protocolSubmissionStatus);
	protocolSubmission.setSubmissionStatusCode(submissionStatusCode);
	
	//TODO check submission number and increment to 1 if mounted bo does not contain latest submission number
	protocolSubmission.setSubmissionNumber(protocolAction.getProtocol().getProtocolSubmission().getSubmissionNumber() + 1);
	
	protocolAction.getProtocolAction().setSubmissionTypeCode(submissionTypeCode);
	//TODO should it be set to one to many or one to one mount
	protocolAction.getProtocol().setProtocolSubmission(protocolSubmission);
}

function void setProtocolStatusCode(IacucProtocolActionUpdateMapping protocolAction, String newProtocolStatusCode) {
    protocolAction.getProtocol().setProtocolStatusCode(newProtocolStatusCode);  
} 

rule "fn_assign_to_agenda: Submission Status = 1102 (Assigned to Agenda);"
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1200")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1102");
end

rule "fn_table: Submission Status = 1212 (Major Revisions Required); Protocol Status = 1107 (Tabled)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1211")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1212");
	setProtocolStatusCode(protocolAction, "1107");
end

rule "fn_approve: Submission Status = 1200;" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1204", protocolNumberARCondition in ("A", "R") )
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1200");
end

rule "fn_approve: Submission Status = 1200; Protocol Status = 1200" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1204", protocolNumberARCondition not in ("A", "R"))
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1200");
	setProtocolStatusCode(protocolAction, "1200");
end

rule "fn_SMRReqd: Submission Status = 1210 (Specific Minor Revisions Required); Protocol Status = 1104 (Specific Minor Revisions Required)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1209")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1210");
	setProtocolStatusCode(protocolAction, "1104");
end

//TODO: What is IACUC equivalent of Closed?
//rule "fn_close: Submission Status = 207 (Closed); Protocol Status = 301 (Closed by investigator)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "300", submissionTypeCode == "109")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolSubmissionStatusCode(protocolAction, "207");
//	setProtocolStatusCode(protocolAction, "301");
//end

//TODO: What is IACUC equiv for Closed by IRB Administrator?
//rule "fn_close: Protocol Status = 300 (Closed by IRB Administrator)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "300", submissionTypeCode != "109")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolStatusCode(protocolAction, "300");
//end

//???? Not sure what to do about this one...
//rule "fn_terminate: Submission Status = 1202 (Terminated); Protocol Status = 303 (Terminated by investigator)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1306", submissionTypeCode == "108")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolSubmissionStatusCode(protocolAction, "1202");
//	setProtocolStatusCode(protocolAction, "303");
//end

//TODO: What is IACUC equiv for Terminated by IRB Administrator?
//rule "fn_terminate: Protocol Status = 307 (Terminated by IRB Administrator)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1306", submissionTypeCode != "108")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolStatusCode(protocolAction, "307");
//end

// What to do about this in IACUC?
//rule "fn_suspend: Submission Status = 1203 (Suspended); Protocol Status =  302 (Suspended by investigator)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1307", submissionTypeCode == "110")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolSubmissionStatusCode(protocolAction, "1203");
//	setProtocolStatusCode(protocolAction, "302");
//end

//TODO: What is IACUC equiv for Suspended by IRB Administrator?
//rule "fn_suspend: Protocol Status =  308 (Suspended by IRB Administrator)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1307", submissionTypeCode != "110")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolStatusCode(protocolAction, "308");
//end

rule "fn_expire: Protocol Status =  1308 (Expire)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1302")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "1308");
end

rule "fn_withdraw: Submission Status =  1204 (Withdrawn )" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "3115")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1204");
end

rule "fn_withdraw: Protocol Status =  1105 (Withdrawn) " 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "3115", protocolStatusCode == "101")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "1105");
end

rule "fn_disapprove: Submission Status = 1201(Disapproved); Protocol Status =  306(Disapprove)  " 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1301")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1201");
	setProtocolStatusCode(protocolAction, "306");
end

// following is changed from "exempt" to "review not required"
rule "fn_grantExempt: Submission Status = 1104 (Review Not Required); Protocol Status = 1300" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1207")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1104");
	setProtocolStatusCode(protocolAction, "1300");
end

//TODO: For IACUC, do we get rid of following?
//rule "fn_IRB_Review_Not_Required: fn_grantExempt: Submission Status = 104 (IRB review not nequired) ; Protocol Status = 310" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "210")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolSubmissionStatusCode(protocolAction, "104");
//	setProtocolStatusCode(protocolAction, "310");
//end
 
//IACUC not used 
//rule "fn_request_for_termination: submissionTypeCode = 108, reviewCode = 1, submissionStatusCode = 1104**/" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "104")
//then	
//	setNewProtocolSubmission(protocolAction, "108", "1", "102");
//end

//IACUC not used 
//rule "fn_request_for_suspension: submissionTypeCode = 110, reviewCode = 1, submissionStatusCode = 1104**/" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "106")
//then	
//	setNewProtocolSubmission(protocolAction, "110", "1", "102");
//end

//IACUC not used 
//rule "fn_request_to_close: submissionTypeCode = 109, reviewCode = 1, submissionStatusCode = 1104**/" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "105")
//then	
	//setNewProtocolSubmission(protocolAction, "109", "1", "102");
//end

rule "fn_assign_to_schedule: Updates all the Submission with the given Committee Id & Schedule Id" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1109")
then	
	createAuditTrail(protocolAction);
	//TODO update all protocol submission's and committee schedule, following statement should be removed
	setNewProtocolSubmission(protocolAction, "111", "1", "102");
end

rule "fn_Response_Approve: Submission Status = 1200;" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1205", protocolNumberARCondition in ("A", "R") )
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1200");
end

rule "fn_Response_Approve: Submission Status = 1200; Protocol Status = 1200" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1205", protocolNumberARCondition not in ("A", "R"))
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1200");
	setProtocolStatusCode(protocolAction, "1200");
end

rule "fn_IACUC_Acknowledge: Submission Status = 1205" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1206")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1205");
end

// Notify IACUC does not exist in submission type table for IACUC
//rule "fn_notify_iacuc: submissionTypeCode = 112, reviewCode = 7, submissionStatusCode = 1104" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1114")
//then	
//	createAuditTrail(protocolAction);
//	# new submission already created in notifyirbservice.  this is duplicate
//	#setNewProtocolSubmission(protocolAction, "112", "7", "102");
//end

// Following 2 statii do not exist in IACUC status table. What to do about them?
//rule "fn_table:  Protocol Status = 105 (Tabled)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1102")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolStatusCode(protocolAction, "105");
//end
//
//rule "fn_table:  Protocol Status = 106 (Tabled)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1104")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolStatusCode(protocolAction, "106");
//end

//TODO: What to do about this? Equivalent in IACUC?
//rule "fn_table:  Protocol Defer" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "201")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolSubmissionStatusCode(protocolAction, "1206");
//	setProtocolStatusCode(protocolAction, "103");
//end

//rule "Abandoned:  Protocol Status = 313 " 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1117")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolStatusCode(protocolAction, "313");
//end

