DELIMITER /

INSERT INTO IACUC_CORRESPONDENT_TYPE ( CORRESPONDENT_TYPE_CODE, DESCRIPTION, QUALIFIER, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID )
VALUES ( '1', 'IACUC correspondent', 'P', NOW(), 'admin', 1, UUID() )
/

INSERT INTO IACUC_CORRESPONDENT_TYPE ( CORRESPONDENT_TYPE_CODE, DESCRIPTION, QUALIFIER, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID )
VALUES ( '2', 'Administrative contact', 'U', NOW(), 'admin', 1, UUID() )
/

INSERT INTO IACUC_CORRESPONDENT_TYPE ( CORRESPONDENT_TYPE_CODE, DESCRIPTION, QUALIFIER, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID )
VALUES ( '3', 'Organization contact', 'O', NOW(), 'admin', 1, UUID() )
/

DELIMITER ;
