CREATE TABLE S2S_ERROR (
    S2S_ERROR_ID NUMBER(12,0) NOT NULL,
    MESSAGE_KEY VARCHAR2(200) NOT NULL,
    MESSAGE VARCHAR2(200) NOT NULL,
    FIX_LINK VARCHAR2(200) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    UPDATE_USER VARCHAR2(60) NOT NULL,
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL,
    OBJ_ID VARCHAR2(36) NOT NULL)
/

ALTER TABLE S2S_ERROR
ADD CONSTRAINT PK_S2S_ERROR
PRIMARY KEY (S2S_ERROR_ID)
/

ALTER TABLE S2S_ERROR
ADD CONSTRAINT UQ_S2S_ERROR
UNIQUE (MESSAGE_KEY)
/
