/*
 * Kuali Coeus, a comprehensive research administration system for higher education.
 *
 * Copyright 2005-2016 Kuali, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package updateProtocol


import org.kuali.kra.irb.actions.submit.ProtocolUndoActionMapping;

function void resetProtocolSubmissionStatusCode(ProtocolUndoActionMapping protocolAction) { 
    protocolAction.getProtocol().getProtocolSubmission().setSubmissionStatusCode(protocolAction.getProtocolAction().getPrevSubmissionStatusCode());  
} 

function void deleteNewProtocolSubmission(ProtocolUndoActionMapping protocolAction) {
	protocolAction.setProtocolSubmissionToBeDeleted(true);
}

function void resetProtocolStatusCode(ProtocolUndoActionMapping protocolAction) {
    protocolAction.getProtocol().setProtocolStatusCode(protocolAction.getProtocolAction().getPrevProtocolStatusCode());  
    protocolAction.getProtocol().refreshReferenceObject("protocolStatus");
} 

rule "fn_assign_to_agenda"
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "200")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
end

rule "fn_defer"
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "201")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_table" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "202")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_approve" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "204")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_SMRReqd" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "203")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_close: submissionTypeCode 109" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "300", submissionTypeCode == "109")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_close: submissionTypeCode other than 109" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "300", submissionTypeCode != "109")
then	
	resetProtocolStatusCode(protocolAction);
end

rule "fn_terminate" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "301", submissionTypeCode == "108")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_terminate: submissionTypeCode other than 108" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "301", submissionTypeCode != "108")
then	
	resetProtocolStatusCode(protocolAction);
end

rule "fn_suspend" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "302", submissionTypeCode == "110")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_suspend: submissionTypeCode other than 110" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "302", submissionTypeCode != "110")
then	
	resetProtocolStatusCode(protocolAction);
end

rule "fn_suspend_by_dsmb" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "306", submissionTypeCode == "110")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_suspend_by_dsmb: submissionTypeCode other than 110" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "306", submissionTypeCode != "110")
then	
	resetProtocolStatusCode(protocolAction);
end

rule "fn_expire" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "305")
then	
	resetProtocolStatusCode(protocolAction);
end

rule "fn_withdraw" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "303")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
end

rule "fn_withdraw: submissionTypeCode 101" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "303", protocolStatusCode == "101")
then	
	resetProtocolStatusCode(protocolAction);
end

rule "fn_disapprove" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "304")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_expeditedApprove" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "205")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_grantExempt" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "206")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_IRB_Review_Not_Required" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "210")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_closed_For_Enrollment: submissionTypeCode 111" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "207", submissionTypeCode == "111")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_closed_For_Enrollment" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "207")
then	
	resetProtocolStatusCode(protocolAction);
end

rule "fn_request_for_termination" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "104")
then	
	deleteNewProtocolSubmission(protocolAction);
end

rule "fn_request_for_suspension" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "106")
then	
	deleteNewProtocolSubmission(protocolAction);
end

rule "fn_request_to_close" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "105")
then	
	deleteNewProtocolSubmission(protocolAction);
end

rule "fn_request_to_close_enrollment" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "108")
then	
	deleteNewProtocolSubmission(protocolAction);
end

rule "fn_assign_to_schedule" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "109")
then	
	//TODO update all protocol submission's and committee schedule, following statement should be removed
	// currently, this is only a followup action will be recorded as action.  not delete submission is needed.
	//deleteNewProtocolSubmission(protocolAction);
end

rule "fn_Response_Approve" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "208")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction); 
end

rule "fn_IRB_Acknowledge" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "209")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
end

rule "fn_request_for_data_analysis" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "114")
then	
	deleteNewProtocolSubmission(protocolAction);
end

rule "fn_request_to_reopen_enroll" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "115")
then	
	deleteNewProtocolSubmission(protocolAction);
end

rule "fn_notify_irb" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "116")
then	
	deleteNewProtocolSubmission(protocolAction);
end

rule "fn_data_analysis_only" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "211", submissionTypeCode == "111")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_data_analysis_only: submissionTypeCode other than 111" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "211", submissionTypeCode != "111")
then	
	resetProtocolStatusCode(protocolAction);
end

rule "fn_re_open_Enrollment" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "212", submissionTypeCode == "115")
then	
	resetProtocolSubmissionStatusCode(protocolAction);
	resetProtocolStatusCode(protocolAction);
end

rule "fn_re_open_Enrollment: submissionTypeCode other than 115" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "212", submissionTypeCode != "115")
then	
	resetProtocolStatusCode(protocolAction);
end

rule "fn_table: actionTypeCode 103" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "103")
then	
	resetProtocolStatusCode(protocolAction);
end
rule "fn_table: actionTypeCode 102" 
salience 100
when
	protocolAction : ProtocolUndoActionMapping( actionTypeCode == "102")
then	
	resetProtocolStatusCode(protocolAction);
end

