/*
 * Kuali Coeus, a comprehensive research administration system for higher education.
 *
 * Copyright 2005-2016 Kuali, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package updateProtocol


import org.kuali.kra.irb.actions.submit.ProtocolActionUpdateMapping;

import org.kuali.kra.irb.actions.submit.ProtocolReviewType;
import org.kuali.kra.irb.actions.submit.ProtocolSubmission;
import org.kuali.kra.irb.actions.submit.ProtocolSubmissionStatus; 
import org.kuali.kra.irb.actions.submit.ProtocolSubmissionType;

function void createAuditTrail(ProtocolActionUpdateMapping protocolAction) {
	if(protocolAction.getProtocol().getProtocolSubmission() != null) {
		protocolAction.getProtocolAction().setPrevSubmissionStatusCode(protocolAction.getProtocol().getProtocolSubmission().getSubmissionStatusCode());
		protocolAction.getProtocolAction().setSubmissionTypeCode(protocolAction.getProtocol().getProtocolSubmission().getSubmissionTypeCode());
	}
	String currentProtocolStatusCode = protocolAction.getProtocol().getProtocolStatusCode();
    protocolAction.getProtocolAction().setPrevProtocolStatusCode(currentProtocolStatusCode);
}
function void setProtocolSubmissionStatusCode(ProtocolActionUpdateMapping protocolAction, String newProtocolSubmissionStatusCode) {
	//TODO Test this with OJB, if you have to find object with new status code and re-attache to protocol submission status???
    protocolAction.getProtocolSubmission().setSubmissionStatusCode(newProtocolSubmissionStatusCode);  
} 
 
function void setProtocolStatusCode(ProtocolActionUpdateMapping protocolAction, String newProtocolStatusCode) {
    protocolAction.getProtocol().setProtocolStatusCode(newProtocolStatusCode);  
} 

rule "fn_assign_to_agenda: Submission Status = 101 (Assiged to Agenda);"
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "200")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "101");
end

rule "fn_defer: Submission Status = 206 (Deferred); Protocol Status = 103 (Deferred)"
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "201")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "206");
	setProtocolStatusCode(protocolAction, "103");
end

rule "fn_table: Submission Status = 201 (Substantive Revisions Required); Protocol Status = 104 (Tabled)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "202")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "201");
	setProtocolStatusCode(protocolAction, "104");
end

rule "fn_approve: Submission Status = 203;" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "204", protocolNumberARCondition in ("A", "R") )
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "203");
end

rule "fn_approve: Submission Status = 203; Protocol Status = 200" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "204", protocolNumberARCondition not in ("A", "R"))
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "203");
	setProtocolStatusCode(protocolAction, "200");
end

rule "fn_SMRReqd: Submission Status = 202 (Specific Minor Revisions Required); Protocol Status = 102 (Specific Minor Revisions Required)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "203")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "202");
	setProtocolStatusCode(protocolAction, "102");
end

rule "fn_close: Submission Status = 207 (Closed); Protocol Status = 301 (Closed by investigator)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "300", submissionTypeCode == "109")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "207");
	setProtocolStatusCode(protocolAction, "301");
end

rule "fn_close: Protocol Status = 300 (Closed by IRB Administrator)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "300", submissionTypeCode != "109")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "300");
end

rule "fn_terminate: Submission Status = 208 (Terminated); Protocol Status = 303 (Terminated by investigator)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "301", submissionTypeCode == "108")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "208");
	setProtocolStatusCode(protocolAction, "303");
end

rule "fn_terminate: Protocol Status = 307 (Terminated by IRB Administrator)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "301", submissionTypeCode != "108")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "307");
end

rule "fn_suspend: Submission Status = 209 (Suspended); Protocol Status =  302 (Suspended by investigator)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "302", submissionTypeCode == "110")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "209");
	setProtocolStatusCode(protocolAction, "302");
end

rule "fn_suspend: Protocol Status =  308 (Suspended by IRB Administrator)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "302", submissionTypeCode != "110")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "308");
end

rule "fn_suspend_by_dsmb: Submission Status = 209 (Suspended); Protocol Status =  311 (Suspended by DSMB)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "306", submissionTypeCode == "110")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "209");
	setProtocolStatusCode(protocolAction, "311");
end

rule "fn_suspend_by_dsmb: Protocol Status =  311 (Suspended by DSMB)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "306", submissionTypeCode != "110")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "311");
end

rule "fn_expire: Protocol Status =  305 (Expire)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "305")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "305");
end

rule "fn_withdraw: Submission Status =  210 (Withdrawn )" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "303")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "210");
end

rule "fn_withdraw: Protocol Status =  304 (Withdrawn) " 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "303", protocolStatusCode == "101")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "304");
end

rule "fn_disapprove: Submission Status = 205(Disapproved); Protocol Status =  306(Disapprove)  " 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "304")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "205");
	setProtocolStatusCode(protocolAction, "306");
end

rule "fn_expeditedApprove: Protocol Status = 203" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "205", protocolNumberARCondition in ("A", "R"))
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "203");
end

rule "fn_expeditedApprove: Submission Status = 200; Protocol Status = 203" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "205", protocolNumberARCondition not in ("A", "R"))
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "203");
	setProtocolStatusCode(protocolAction, "200");
end

rule "fn_grantExempt: Submission Status = 204 (Exemption Granted); Protocol Status = 203" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "206")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "204");
	setProtocolStatusCode(protocolAction, "203");
end

rule "fn_IRB_Review_Not_Required: fn_grantExempt: Submission Status = 104 (IRB review not nequired) ; Protocol Status = 310" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "210")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "104");
	setProtocolStatusCode(protocolAction, "310");
end
 
rule "fn_closed_For_Enrollment: Submission Status = 211 (Closed for Enrollment); Protocol Status =  201 (Active Closed for Enrollment)**/" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "207", submissionTypeCode == "111")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "211");
	setProtocolStatusCode(protocolAction, "201");
end

rule "fn_closed_For_Enrollment: Protocol Status =  201 (Active Closed for Enrollment)**/" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "207", submissionTypeCode != "111")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "201");
end

rule "fn_request_for_termination: submissionTypeCode = 108, reviewCode = 1, submissionStatusCode = 102**/" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "104")
then	
	//setNewProtocolSubmission(protocolAction, "108", "1", "102");
end

rule "fn_request_for_suspension: submissionTypeCode = 110, reviewCode = 1, submissionStatusCode = 102**/" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "106")
then	
	//setNewProtocolSubmission(protocolAction, "110", "1", "102");
end

rule "fn_request_to_close: submissionTypeCode = 109, reviewCode = 1, submissionStatusCode = 102**/" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "105")
then	
	//setNewProtocolSubmission(protocolAction, "109", "1", "102");
end

rule "fn_request_to_close_enrollment: submissionTypeCode = 111, reviewCode = 1, submissionStatusCode = 102" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "108")
then	
	//setNewProtocolSubmission(protocolAction, "111", "1", "102");
end

rule "fn_notify_committee: " 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "109")
then	
	createAuditTrail(protocolAction);
	// setNewProtocolSubmission(protocolAction, "111", "1", "102");
end

rule "fn_Response_Approve: Submission Status = 203;" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "208", protocolNumberARCondition in ("A", "R") )
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "203");
end

rule "fn_Response_Approve: Submission Status = 203; Protocol Status = 200" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "208", protocolNumberARCondition not in ("A", "R"))
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "203");
	setProtocolStatusCode(protocolAction, "200");
end

rule "fn_IRB_Acknowledge: Submission Status = 212" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "209")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "212");
end

rule "fn_request_for_data_analysis: submissionTypeCode = 113, reviewCode = 1, submissionStatusCode = 102" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "114")
then	
    // submission created in requestservice
	//setNewProtocolSubmission(protocolAction, "113", "1", "102");
end

rule "fn_request_to_reopen_enroll: submissionTypeCode = 114, reviewCode = 1, submissionStatusCode = 102" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "115")
then	
	//setNewProtocolSubmission(protocolAction, "114", "1", "102");
end

rule "fn_notify_irb: submissionTypeCode = 112, reviewCode = 7, submissionStatusCode = 102" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "116")
then	
	createAuditTrail(protocolAction);
	// new submission already created in notifyirbservice.  this is duplicate
	//setNewProtocolSubmission(protocolAction, "112", "7", "102");
end

rule "fn_data_analysis_only: Submission Status = 211 (Closed for Enrollment); Protocol Status =  202 (Active Data Analysis Only)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "211", submissionTypeCode == "111")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "211");
	setProtocolStatusCode(protocolAction, "202");
end

rule "fn_data_analysis_only: Protocol Status =  202 (Active Data Analysis Only)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "211", submissionTypeCode != "111")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "222");
	setProtocolStatusCode(protocolAction, "202");
end

rule "fn_re_open_Enrollment: Submission Status = 211 (Closed for Enrollment); Protocol Status =  202 (Active Open for Enrollment)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "212", submissionTypeCode == "115")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "211");
	setProtocolStatusCode(protocolAction, "200");
end

rule "fn_re_open_Enrollment: Protocol Status =  202 (Active Open for Enrollment)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "212", submissionTypeCode != "115")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "221");
	setProtocolStatusCode(protocolAction, "200");
end

//rule "fn_table: Submission Status = 212 ; Protocol Status = 101 (Tabled)" 
//salience 100
//when
//	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "101")
//then	
//	setProtocolSubmissionStatusCode(protocolAction, "100");
//	setProtocolStatusCode(protocolAction, "101");
//end
rule "fn_table:  Protocol Status = 105 (Tabled)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "103")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "105");
end
rule "fn_table:  Protocol Status = 106 (Tabled)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "102")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "106");
end

rule "fn_table:  Protocol Defer" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "201")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "206");
	setProtocolStatusCode(protocolAction, "103");
end

rule "Abandoned:  Protocol Status = 313 " 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "119")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "313");
end

rule "fn_return_to_pi: Submission Status = 209 (Returned To PI); Protocol Status = 102 (Return To PI)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "213")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "213");
	setProtocolStatusCode(protocolAction, "107");
end

rule "fn_recall: Submission Status = 406 (Recalled in Routing); Protocol Status = 402 (Recalled in Routing)" 
salience 100
when
	protocolAction : ProtocolActionUpdateMapping( actionTypeCode == "405")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "406");
	setProtocolStatusCode(protocolAction, "402");
end
