-- These must be run together to avoid errors --
ALTER TABLE COMMITTEE 
  DROP CONSTRAINT FK_COMMITTEE_DOCUMENT;
ALTER TABLE COMMITTEE MODIFY (DOCUMENT_NUMBER VARCHAR2(40));
ALTER TABLE COMMITTEE_DOCUMENT MODIFY (DOCUMENT_NUMBER VARCHAR2(40));
ALTER TABLE COMMITTEE
  ADD CONSTRAINT FK_COMMITTEE_DOCUMENT FOREIGN KEY (DOCUMENT_NUMBER)
  REFERENCES COMMITTEE_DOCUMENT (DOCUMENT_NUMBER);