CREATE TABLE QUESTIONNAIRE_CONDITION_TYPE 
  ( 
        QUEST_CONDITION_TYPE_CODE VARCHAR2(3), 
        DESCRIPTION VARCHAR2(200) NOT NULL ENABLE, 
        UPDATE_TIMESTAMP DATE NOT NULL ENABLE, 
        UPDATE_USER VARCHAR2(60 BYTE) NOT NULL ENABLE, 
        VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL ENABLE, 
        OBJ_ID VARCHAR2(36 BYTE) NOT NULL ENABLE,  
        CONSTRAINT QUESTIONNAIRE_CONDITION_TYPEP1 PRIMARY KEY (QUEST_CONDITION_TYPE_CODE)
   )  ;

ALTER TABLE QUESTIONNAIRE_QUESTIONS 
ADD CONSTRAINT FK_QUEST_QUESTIONS_COND_TYPE 
FOREIGN KEY (CONDITION_TYPE) 
REFERENCES QUESTIONNAIRE_CONDITION_TYPE (QUEST_CONDITION_TYPE_CODE);
