<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:award="http://subcontractFdpReports.bean.xml.utils.coeus.mit.edu/award" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:subcontract="http://subcontractFdpReports.bean.xml.utils.coeus.mit.edu/subcontract" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<xsl:output version="1.0" method="xml" encoding="UTF-8" indent="no"/>
	<xsl:param name="SV_OutputFormat" select="'PDF'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="fo:layout-master-set">
		<fo:layout-master-set>
			<fo:simple-page-master master-name="default-page" page-height="11in" page-width="8.5in" margin-left="0.2in" margin-right="0.2in">
				<fo:region-body margin-top="0.5in" margin-bottom="0.79in"/>
				<fo:region-before extent="0.5in"/>
			</fo:simple-page-master>
		</fo:layout-master-set>
	</xsl:variable>
	<xsl:template match="/">
		<fo:root>
			<xsl:copy-of select="$fo:layout-master-set"/>
			<fo:page-sequence master-reference="default-page" initial-page-number="1" format="1">
				<xsl:call-template name="headerall"/>
				<fo:flow flow-name="xsl-region-body">
					<fo:block>
						<fo:block/>
						<xsl:for-each select="$XML">
							<fo:inline-container>
								<fo:block>
									<xsl:text>&#x2029;</xsl:text>
								</fo:block>
							</fo:inline-container>
							<fo:table font-family="Times New Roman" font-size="12pt" font-weight="bold" table-layout="fixed" width="100%" border="solid 1pt gray" border-spacing="-1pt">
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-body start-indent="0pt">
									<fo:table-row>
										<fo:table-cell border="solid 1pt gray" padding="0" display-align="center">
											<fo:block>
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:block text-align="center" margin="0pt">
													<fo:block>
														<fo:inline>
															<xsl:text>Attachment 2</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline>
															<xsl:text>Research Subaward Agreement</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline>
															<xsl:text>Prime Award Terms and Conditions</xsl:text>
														</fo:inline>
														<fo:block/>
														<fo:inline>
															<xsl:text>ONR</xsl:text>
														</fo:inline>
													</fo:block>
												</fo:block>
											</fo:block>
										</fo:table-cell>
									</fo:table-row>
								</fo:table-body>
							</fo:table>
							<fo:inline-container>
								<fo:block>
									<xsl:text>&#x2029;</xsl:text>
								</fo:block>
							</fo:inline-container>
							<fo:table font-family="Times New Roman" table-layout="fixed" width="100%" border-spacing="2pt">
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-body start-indent="0pt">
									<fo:table-row font-size="12pt" font-weight="bold">
										<fo:table-cell padding="0" display-align="center">
											<fo:block>
												<fo:inline>
													<xsl:text>Certifications/Assurances</xsl:text>
												</fo:inline>
												<fo:block>
													<fo:leader leader-pattern="space"/>
												</fo:block>
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:block margin="0pt">
													<fo:block/>
												</fo:block>
											</fo:block>
										</fo:table-cell>
									</fo:table-row>
									<fo:table-row font-size="10pt" font-weight="normal">
										<fo:table-cell padding="0" display-align="center">
											<fo:block>
												<fo:inline>
													<xsl:text> By signing this Research Subaward Agreement Subrecipient makes the certifications and assurances specified in the Research Terms and Conditions Appendix C found at </xsl:text>
												</fo:inline>
												<fo:basic-link text-decoration="underline" color="blue">
													<xsl:choose>
														<xsl:when test="substring(string(&apos;nsf.gov/bfa/dias/policy/rtc/appc.pdf  &apos;), 1, 1) = '#'">
															<xsl:attribute name="internal-destination">
																<xsl:value-of select="substring(string(&apos;nsf.gov/bfa/dias/policy/rtc/appc.pdf  &apos;), 2)"/>
															</xsl:attribute>
														</xsl:when>
														<xsl:otherwise>
															<xsl:attribute name="external-destination">
																<xsl:text>url(</xsl:text>
																<xsl:call-template name="double-backslash">
																	<xsl:with-param name="text">
																		<xsl:value-of select="string(&apos;nsf.gov/bfa/dias/policy/rtc/appc.pdf  &apos;)"/>
																	</xsl:with-param>
																	<xsl:with-param name="text-length">
																		<xsl:value-of select="string-length(string(&apos;nsf.gov/bfa/dias/policy/rtc/appc.pdf  &apos;))"/>
																	</xsl:with-param>
																</xsl:call-template>
																<xsl:text>)</xsl:text>
															</xsl:attribute>
														</xsl:otherwise>
													</xsl:choose>
													<fo:inline>
														<xsl:text>http://www.nsf.gov/bfa/dias/policy/rtc/appc.pdf</xsl:text>
													</fo:inline>
												</fo:basic-link>
											</fo:block>
										</fo:table-cell>
									</fo:table-row>
								</fo:table-body>
							</fo:table>
							<fo:block>
								<fo:leader leader-pattern="space"/>
							</fo:block>
							<fo:inline-container>
								<fo:block>
									<xsl:text>&#x2029;</xsl:text>
								</fo:block>
							</fo:inline-container>
							<fo:block margin="0pt">
								<fo:block/>
							</fo:block>
							<fo:inline-container>
								<fo:block>
									<xsl:text>&#x2029;</xsl:text>
								</fo:block>
							</fo:inline-container>
							<fo:table table-layout="fixed" width="100%" border-spacing="2pt">
								<fo:table-column column-width="28%"/>
								<fo:table-body start-indent="0pt">
									<fo:table-row font-family="Times New Roman" font-size="12pt" font-weight="bold">
										<fo:table-cell padding="2pt" display-align="center">
											<fo:block>
												<fo:inline>
													<xsl:text>General terms and conditions </xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
									</fo:table-row>
								</fo:table-body>
							</fo:table>
							<fo:inline-container>
								<fo:block>
									<xsl:text>&#x2029;</xsl:text>
								</fo:block>
							</fo:inline-container>
							<fo:table font-family="time" font-size="10pt" table-layout="fixed" width="100%" border-spacing="2pt">
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-body start-indent="0pt">
									<fo:table-row>
										<fo:table-cell padding="2pt" display-align="center">
											<fo:block>
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:list-block provisional-distance-between-starts="7mm" provisional-label-separation="2mm">
													<fo:list-item>
														<fo:list-item-label end-indent="label-end()" text-align="right">
															<fo:block>
																<xsl:number format="1" value="1"/>.</fo:block>
														</fo:list-item-label>
														<fo:list-item-body start-indent="body-start()">
															<fo:block font-family="time" font-size="10pt" font-weight="normal">
																<fo:inline>
																	<xsl:text>The restrictions on the expenditure of federal funds in appropriations acts are applicable to this subaward to the extent those restrictions are pertinent.</xsl:text>
																</fo:inline>
															</fo:block>
														</fo:list-item-body>
													</fo:list-item>
													<fo:list-item>
														<fo:list-item-label end-indent="label-end()" text-align="right">
															<fo:block>
																<xsl:number format="1" value="2"/>.</fo:block>
														</fo:list-item-label>
														<fo:list-item-body start-indent="body-start()">
															<fo:block font-family="time" font-size="10pt" font-weight="normal">
																<fo:inline>
																	<xsl:text>DoDGARS Part 32 </xsl:text>
																</fo:inline>
																<fo:basic-link text-decoration="underline" color="blue">
																	<xsl:choose>
																		<xsl:when test="substring(string(&apos;dtic.mil/whs/directives/corres/pdf/321006r32p.pdf &apos;), 1, 1) = '#'">
																			<xsl:attribute name="internal-destination">
																				<xsl:value-of select="substring(string(&apos;dtic.mil/whs/directives/corres/pdf/321006r32p.pdf &apos;), 2)"/>
																			</xsl:attribute>
																		</xsl:when>
																		<xsl:otherwise>
																			<xsl:attribute name="external-destination">
																				<xsl:text>url(</xsl:text>
																				<xsl:call-template name="double-backslash">
																					<xsl:with-param name="text">
																						<xsl:value-of select="string(&apos;dtic.mil/whs/directives/corres/pdf/321006r32p.pdf &apos;)"/>
																					</xsl:with-param>
																					<xsl:with-param name="text-length">
																						<xsl:value-of select="string-length(string(&apos;dtic.mil/whs/directives/corres/pdf/321006r32p.pdf &apos;))"/>
																					</xsl:with-param>
																				</xsl:call-template>
																				<xsl:text>)</xsl:text>
																			</xsl:attribute>
																		</xsl:otherwise>
																	</xsl:choose>
																	<fo:inline>
																		<xsl:text>http://www.dtic.mil/whs/directives/corres/pdf/321006r32p.pdf </xsl:text>
																	</fo:inline>
																</fo:basic-link>
															</fo:block>
														</fo:list-item-body>
													</fo:list-item>
													<fo:list-item>
														<fo:list-item-label end-indent="label-end()" text-align="right">
															<fo:block>
																<xsl:number format="1" value="3"/>.</fo:block>
														</fo:list-item-label>
														<fo:list-item-body start-indent="body-start()">
															<fo:block font-family="time" font-size="10pt" font-weight="normal">
																<fo:inline>
																	<xsl:text>Research Terms and Conditions found at </xsl:text>
																</fo:inline>
																<fo:basic-link text-decoration="underline" color="blue">
																	<xsl:choose>
																		<xsl:when test="substring(string(&apos;nsf.gov/bfa/dias/policy/rtc/terms.pdf &apos;), 1, 1) = '#'">
																			<xsl:attribute name="internal-destination">
																				<xsl:value-of select="substring(string(&apos;nsf.gov/bfa/dias/policy/rtc/terms.pdf &apos;), 2)"/>
																			</xsl:attribute>
																		</xsl:when>
																		<xsl:otherwise>
																			<xsl:attribute name="external-destination">
																				<xsl:text>url(</xsl:text>
																				<xsl:call-template name="double-backslash">
																					<xsl:with-param name="text">
																						<xsl:value-of select="string(&apos;nsf.gov/bfa/dias/policy/rtc/terms.pdf &apos;)"/>
																					</xsl:with-param>
																					<xsl:with-param name="text-length">
																						<xsl:value-of select="string-length(string(&apos;nsf.gov/bfa/dias/policy/rtc/terms.pdf &apos;))"/>
																					</xsl:with-param>
																				</xsl:call-template>
																				<xsl:text>)</xsl:text>
																			</xsl:attribute>
																		</xsl:otherwise>
																	</xsl:choose>
																	<fo:inline>
																		<xsl:text>http://www.nsf.gov/bfa/dias/policy/rtc/terms.pdf </xsl:text>
																	</fo:inline>
																</fo:basic-link>
																<fo:inline>
																	<xsl:text> and Agency Specific Requirements found at </xsl:text>
																</fo:inline>
																<fo:basic-link text-decoration="underline" color="blue">
																	<xsl:choose>
																		<xsl:when test="substring(string(&apos;nsf.gov/pubs/policydocs/rtc/onr_708.pdf&apos;), 1, 1) = '#'">
																			<xsl:attribute name="internal-destination">
																				<xsl:value-of select="substring(string(&apos;nsf.gov/pubs/policydocs/rtc/onr_708.pdf&apos;), 2)"/>
																			</xsl:attribute>
																		</xsl:when>
																		<xsl:otherwise>
																			<xsl:attribute name="external-destination">
																				<xsl:text>url(</xsl:text>
																				<xsl:call-template name="double-backslash">
																					<xsl:with-param name="text">
																						<xsl:value-of select="string(&apos;nsf.gov/pubs/policydocs/rtc/onr_708.pdf&apos;)"/>
																					</xsl:with-param>
																					<xsl:with-param name="text-length">
																						<xsl:value-of select="string-length(string(&apos;nsf.gov/pubs/policydocs/rtc/onr_708.pdf&apos;))"/>
																					</xsl:with-param>
																				</xsl:call-template>
																				<xsl:text>)</xsl:text>
																			</xsl:attribute>
																		</xsl:otherwise>
																	</xsl:choose>
																	<fo:inline>
																		<xsl:text>http://www.nsf.gov/pubs/policydocs/rtc/onr_708.pdf</xsl:text>
																	</fo:inline>
																</fo:basic-link>
																<fo:inline>
																	<xsl:text>, except for the following:</xsl:text>
																</fo:inline>
																<fo:inline-container>
																	<fo:block>
																		<xsl:text>&#x2029;</xsl:text>
																	</fo:block>
																</fo:inline-container>
																<fo:list-block provisional-distance-between-starts="7mm" provisional-label-separation="2mm">
																	<fo:list-item>
																		<fo:list-item-label end-indent="label-end()" text-align="right">
																			<fo:block>
																				<xsl:number format="a" value="1"/>.</fo:block>
																		</fo:list-item-label>
																		<fo:list-item-body start-indent="body-start()">
																			<fo:block>
																				<fo:inline>
																					<xsl:text>The right to initiate an automatic one-time extension of the end date provided by Article 25(c)2 is replaced by the need to obtain prior written approval from the Prime Recipient;</xsl:text>
																				</fo:inline>
																			</fo:block>
																		</fo:list-item-body>
																	</fo:list-item>
																	<fo:list-item>
																		<fo:list-item-label end-indent="label-end()" text-align="right">
																			<fo:block>
																				<xsl:number format="a" value="2"/>.</fo:block>
																		</fo:list-item-label>
																		<fo:list-item-body start-indent="body-start()">
																			<fo:block>
																				<fo:inline>
																					<xsl:text>The payment mechanism described in Article 22 and the financial reporting requirements in Article 52 of the Research Terms and Conditions and Articles 9 and 11 of the Agency-Specific Requirements are replaced with Terms and Conditions (1) through (4) of this agreement; and</xsl:text>
																				</fo:inline>
																			</fo:block>
																		</fo:list-item-body>
																	</fo:list-item>
																	<fo:list-item>
																		<fo:list-item-label end-indent="label-end()" text-align="right">
																			<fo:block>
																				<xsl:number format="a" value="3"/>.</fo:block>
																		</fo:list-item-label>
																		<fo:list-item-body start-indent="body-start()">
																			<fo:block>
																				<fo:inline>
																					<xsl:text>Any prior approvals are to be sought from the Prime Recipient and not the Federal Awarding Agency.</xsl:text>
																				</fo:inline>
																			</fo:block>
																		</fo:list-item-body>
																	</fo:list-item>
																</fo:list-block>
															</fo:block>
														</fo:list-item-body>
													</fo:list-item>
													<fo:list-item>
														<fo:list-item-label end-indent="label-end()" text-align="right">
															<fo:block>
																<xsl:number format="1" value="4"/>.</fo:block>
														</fo:list-item-label>
														<fo:list-item-body start-indent="body-start()">
															<fo:block>
																<fo:inline>
																	<xsl:text>Title to equipment costing $5,000 or more that is purchased or fabricated with research funds or Subrecipient cost sharing&#160;&#160;&#160; funds, as direct costs of the project or program, shall unconditionally vest in the Subrecipient upon acquisition without further obligation to the Federal Awarding Agency subject to the conditions specified in Article 34(a) of the Research Terms and Conditions</xsl:text>
																</fo:inline>
															</fo:block>
														</fo:list-item-body>
													</fo:list-item>
												</fo:list-block>
											</fo:block>
										</fo:table-cell>
									</fo:table-row>
								</fo:table-body>
							</fo:table>
							<fo:inline-container>
								<fo:block>
									<xsl:text>&#x2029;</xsl:text>
								</fo:block>
							</fo:inline-container>
							<fo:table font-family="time" table-layout="fixed" width="100%" border-spacing="2pt">
								<fo:table-column column-width="28%"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-body start-indent="0pt">
									<fo:table-row>
										<fo:table-cell font-family="times" font-size="12pt" font-weight="bold" padding="2pt" display-align="center">
											<fo:block>
												<fo:inline>
													<xsl:text>Special terms and conditions: </xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-family="time" font-size="10pt" padding="2pt" display-align="center">
											<fo:block>
												<fo:inline>
													<xsl:text>&#160;</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
									</fo:table-row>
									<fo:table-row font-family="time" font-size="10pt">
										<fo:table-cell font-family="times" font-size="12pt" font-weight="bold" number-columns-spanned="2" padding="2pt" display-align="center">
											<fo:block>
												<fo:inline-container>
													<fo:block>
														<xsl:text>&#x2029;</xsl:text>
													</fo:block>
												</fo:inline-container>
												<fo:list-block font-family="time" font-size="10pt" font-weight="normal" provisional-distance-between-starts="7mm" provisional-label-separation="2mm">
													<fo:list-item>
														<fo:list-item-label end-indent="label-end()" text-align="right">
															<fo:block>
																<xsl:number format="1" value="1"/>.</fo:block>
														</fo:list-item-label>
														<fo:list-item-body start-indent="body-start()">
															<fo:block>
																<fo:inline>
																	<xsl:text>Copyrights</xsl:text>
																</fo:inline>
																<fo:block/>
																<fo:inline>
																	<xsl:text>Subrecipient </xsl:text>
																</fo:inline>
																<xsl:choose>
																	<xsl:when test="subcontract:SubContractData/subcontract:SubcontractTemplateInfo/subcontract:CopyRights = &quot;1&quot;">
																		<fo:inline>
																			<xsl:text>grants</xsl:text>
																		</fo:inline>
																	</xsl:when>
																	<xsl:when test="subcontract:SubContractData/subcontract:SubcontractTemplateInfo/subcontract:CopyRights = &quot;2&quot;">
																		<fo:inline>
																			<xsl:text>shall grant</xsl:text>
																		</fo:inline>
																	</xsl:when>
																</xsl:choose>
																<fo:inline>
																	<xsl:text> to Prime Recipient an irrevocable, royalty-free, non-transferable, non-exclusive right and license to use, reproduce, make derivative works, display, and perform publicly any copyrights or copyrighted material (including any computer software and its documentation and/or databases) first developed and delivered under this Subaward Agreement solely for the purpose of and only to the extent required to meet Prime Recipient's obligations to the Federal Government under its Prime Award.</xsl:text>
																</fo:inline>
															</fo:block>
														</fo:list-item-body>
													</fo:list-item>
													<fo:list-item>
														<fo:list-item-label end-indent="label-end()" text-align="right">
															<fo:block>
																<xsl:number format="1" value="2"/>.</fo:block>
														</fo:list-item-label>
														<fo:list-item-body start-indent="body-start()">
															<fo:block>
																<fo:inline>
																	<xsl:text>Data Rights</xsl:text>
																</fo:inline>
																<fo:block/>
																<fo:inline>
																	<xsl:text>Subrecipient </xsl:text>
																</fo:inline>
																<xsl:choose>
																	<xsl:when test="subcontract:SubContractData/subcontract:SubcontractTemplateInfo/subcontract:CopyRights = &quot;1&quot;">
																		<fo:inline>
																			<xsl:text>grants</xsl:text>
																		</fo:inline>
																	</xsl:when>
																	<xsl:when test="subcontract:SubContractData/subcontract:SubcontractTemplateInfo/subcontract:CopyRights = &quot;2&quot;">
																		<fo:inline>
																			<xsl:text>shall grant</xsl:text>
																		</fo:inline>
																	</xsl:when>
																</xsl:choose>
																<fo:inline>
																	<xsl:text> to Prime Recipient the right to use data created in the performance of this Subaward Agreement solely for the purpose of and only to the extent required to meet Prime Recipient's obligations to the Federal Government under its Prime Award.</xsl:text>
																</fo:inline>
																<fo:block/>
																<fo:inline>
																	<xsl:text>[Do not add a Patent or Inventions Clause. The prime award governs rights to patents and inventions. Prime Recipient cannot obtain rights in the Subrecipient's subject inventions as a part of consideration for the subaward.&#160; Should it be necessary, the Federal Government can authorize the Prime Recipient's right to practice a Subrecipient's subject invention (as well as subject data or copyrights) on behalf of the Federal Government.]</xsl:text>
																</fo:inline>
															</fo:block>
														</fo:list-item-body>
													</fo:list-item>
													<fo:list-item>
														<fo:list-item-label end-indent="label-end()" text-align="right">
															<fo:block>
																<xsl:number format="1" value="3"/>.</fo:block>
														</fo:list-item-label>
														<fo:list-item-body start-indent="body-start()">
															<fo:block>
																<fo:inline>
																	<xsl:text>Automatic Carry Forward:&#160; </xsl:text>
																</fo:inline>
																<xsl:choose>
																	<xsl:when test="subcontract:SubContractData/subcontract:SubcontractTemplateInfo/subcontract:AutomaticCarryForward = &apos;Y&apos;">
																		<fo:inline>
																			<xsl:text>Yes</xsl:text>
																		</fo:inline>
																	</xsl:when>
																	<xsl:when test="subcontract:SubContractData/subcontract:SubcontractTemplateInfo/subcontract:AutomaticCarryForward = &apos;N&apos;">
																		<fo:inline>
																			<xsl:text>No</xsl:text>
																		</fo:inline>
																		<fo:block/>
																		<fo:inline>
																			<xsl:text>Carry Forward requests must be sent to Prime Recipient's - </xsl:text>
																		</fo:inline>
																		<xsl:for-each select="subcontract:SubContractData">
																			<xsl:for-each select="subcontract:SubcontractTemplateInfo">
																				<xsl:for-each select="subcontract:CarryForwardRequestsSentToDescription">
																					<xsl:variable name="value-of-template">
																						<xsl:apply-templates/>
																					</xsl:variable>
																					<xsl:choose>
																						<xsl:when test="contains(string($value-of-template),'&#x2029;')">
																							<fo:block>
																								<xsl:copy-of select="$value-of-template"/>
																							</fo:block>
																						</xsl:when>
																						<xsl:otherwise>
																							<fo:inline>
																								<xsl:copy-of select="$value-of-template"/>
																							</fo:inline>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																			</xsl:for-each>
																		</xsl:for-each>
																		<fo:inline>
																			<xsl:text>, as shown in Attachment 3.</xsl:text>
																		</fo:inline>
																	</xsl:when>
																</xsl:choose>
																<fo:inline>
																	<xsl:text>&#160;&#160;&#160;&#160; </xsl:text>
																</fo:inline>
															</fo:block>
														</fo:list-item-body>
													</fo:list-item>
												</fo:list-block>
											</fo:block>
										</fo:table-cell>
									</fo:table-row>
								</fo:table-body>
							</fo:table>
							<fo:block/>
							<fo:block/>
						</xsl:for-each>
						<fo:block/>
					</fo:block>
					<fo:block id="SV_RefID_PageTotal"/>
				</fo:flow>
			</fo:page-sequence>
		</fo:root>
	</xsl:template>
	<xsl:template name="headerall">
		<fo:static-content flow-name="xsl-region-before">
			<fo:block>
				<xsl:for-each select="$XML"/>
			</fo:block>
		</fo:static-content>
	</xsl:template>
	<xsl:template name="double-backslash">
		<xsl:param name="text"/>
		<xsl:param name="text-length"/>
		<xsl:variable name="text-after-bs" select="substring-after($text, '\')"/>
		<xsl:variable name="text-after-bs-length" select="string-length($text-after-bs)"/>
		<xsl:choose>
			<xsl:when test="$text-after-bs-length = 0">
				<xsl:choose>
					<xsl:when test="substring($text, $text-length) = '\'">
						<xsl:value-of select="concat(substring($text,1,$text-length - 1), '\\')"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="$text"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring($text,1,$text-length - $text-after-bs-length - 1), '\\')"/>
				<xsl:call-template name="double-backslash">
					<xsl:with-param name="text" select="$text-after-bs"/>
					<xsl:with-param name="text-length" select="$text-after-bs-length"/>
				</xsl:call-template>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>