INSERT INTO IACUC_PROTOCOL_ATTACHMENT_TYPE (DESCRIPTION,OBJ_ID,TYPE_CD,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Protocol Narrative',SYS_GUID(),'1',SYSDATE,'admin',1)
/
INSERT INTO IACUC_PROTOCOL_ATTACHMENT_TYPE (DESCRIPTION,OBJ_ID,TYPE_CD,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Brochure',SYS_GUID(),'2',SYSDATE,'admin',1)
/
INSERT INTO IACUC_PROTOCOL_ATTACHMENT_TYPE (DESCRIPTION,OBJ_ID,TYPE_CD,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Other Protocol Attachments',SYS_GUID(),'3',SYSDATE,'admin',1)
/
INSERT INTO IACUC_PROTOCOL_ATTACHMENT_TYPE (DESCRIPTION,OBJ_ID,TYPE_CD,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Other Attachments',SYS_GUID(),'4',SYSDATE,'admin',1)
/
INSERT INTO IACUC_PROTOCOL_ATTACHMENT_TYPE (DESCRIPTION,OBJ_ID,TYPE_CD,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Investigational New Drug Brochure',SYS_GUID(),'5',SYSDATE,'admin',1)
/
INSERT INTO IACUC_PROTOCOL_ATTACHMENT_TYPE (DESCRIPTION,OBJ_ID,TYPE_CD,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Amendments and Renewals',SYS_GUID(),'6',SYSDATE,'admin',1)
/
INSERT INTO IACUC_PROTOCOL_ATTACHMENT_TYPE (DESCRIPTION,OBJ_ID,TYPE_CD,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Progress Report',SYS_GUID(),'7',SYSDATE,'admin',1)
/
INSERT INTO IACUC_PROTOCOL_ATTACHMENT_TYPE (DESCRIPTION,OBJ_ID,TYPE_CD,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Protocol Submission Documents',SYS_GUID(),'8',SYSDATE,'admin',1)
/
INSERT INTO IACUC_PROTOCOL_ATTACHMENT_TYPE (DESCRIPTION,OBJ_ID,TYPE_CD,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Other Documents',SYS_GUID(),'9',SYSDATE,'admin',1)
/
INSERT INTO IACUC_PROTOCOL_ATTACHMENT_TYPE (DESCRIPTION,OBJ_ID,TYPE_CD,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Adverse Event',SYS_GUID(),'10',SYSDATE,'admin',1)
/
INSERT INTO IACUC_PROTOCOL_ATTACHMENT_TYPE (DESCRIPTION,OBJ_ID,TYPE_CD,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Biography',SYS_GUID(),'11',SYSDATE,'admin',1)
/
