-- create citizenship type table
CREATE TABLE CITIZENSHIP_TYPE_T  ( 
	CITIZENSHIP_TYPE_CODE	NUMBER(15,1) NOT NULL,
	DESCRIPTION          	VARCHAR2(40) NOT NULL,
	ACTIVE_FLAG          	CHAR(1) NOT NULL,
	UPDATE_TIMESTAMP     	DATE NOT NULL,
	UPDATE_USER          	VARCHAR2(60) NOT NULL,
	VER_NBR              	NUMBER(15,5) NOT NULL,
	OBJ_ID               	VARCHAR2(36) NOT NULL 
	);
	
-- add primary key
ALTER TABLE CITIZENSHIP_TYPE_T
	ADD ( CONSTRAINT CITIZEN_TYPE_PK1
	PRIMARY KEY (CITIZENSHIP_TYPE_CODE)
	 );
