--
-- Kuali Coeus, a comprehensive research administration system for higher education.
-- 
-- Copyright 2005-2015 Kuali, Inc.
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as
-- published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
-- 
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
--

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',0,7896,STR_TO_DATE('22-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',1,11064,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Predoctoral',0,20976,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',0,37368,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',1,39360,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',2,42204,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',3,43860,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',4,45504,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',5,47460,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',6,49344,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',7,51552,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',0,7896,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',1,11064,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Predoctoral',0,20976,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',0,37368,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',1,39360,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',2,42204,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',3,43860,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',4,45504,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',5,47460,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',6,49344,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',7,51552,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',13,12345,STR_TO_DATE('22-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',11,12345,STR_TO_DATE('22-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',1,12345,STR_TO_DATE('21-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',5,5555,STR_TO_DATE('01-JAN-10','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Predoctoral',5,55555,STR_TO_DATE('01-JAN-10','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',11,5555555,STR_TO_DATE('01-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',12,12345,STR_TO_DATE('22-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

commit;
