insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',0,7896,STR_TO_DATE('22-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',1,11064,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Predoctoral',0,20976,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',0,37368,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',1,39360,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',2,42204,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',3,43860,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',4,45504,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',5,47460,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',6,49344,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',7,51552,STR_TO_DATE('09-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',0,7896,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',1,11064,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Predoctoral',0,20976,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',0,37368,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',1,39360,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',2,42204,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',3,43860,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',4,45504,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',5,47460,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',6,49344,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',7,51552,STR_TO_DATE('16-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',13,12345,STR_TO_DATE('22-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',11,12345,STR_TO_DATE('22-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',1,12345,STR_TO_DATE('21-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Postdoctoral',5,5555,STR_TO_DATE('01-JAN-10','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Predoctoral',5,55555,STR_TO_DATE('01-JAN-10','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',11,5555555,STR_TO_DATE('01-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

insert into SEQ_TRAINING_STIPEND_RATES_ID VALUES (NULL);
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (LAST_INSERT_ID(),'Undergraduates',12,12345,STR_TO_DATE('22-DEC-09','%d-%M-%y'),NOW(),'admin',UUID());

commit;