INSERT INTO  TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
VALUES (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Undergraduates',0,8304,to_date('20-JAN-12','DD-MON-RR'),sysdate,'admin',SYS_GUID())
/
INSERT INTO  TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
VALUES (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Undergraduates',1,11628,to_date('20-JAN-12','DD-MON-RR'),sysdate,'admin',SYS_GUID())
/
INSERT INTO  TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
VALUES (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Predoctoral',0,22032,to_date('20-JAN-12','DD-MON-RR'),sysdate,'admin',SYS_GUID())
/
INSERT INTO  TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
VALUES (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',0,39264,to_date('20-JAN-12','DD-MON-RR'),sysdate,'admin',SYS_GUID())
/
INSERT INTO  TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
VALUES (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',1,41364,to_date('20-JAN-12','DD-MON-RR'),sysdate,'admin',SYS_GUID())
/
INSERT INTO  TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
VALUES (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',2,44340,to_date('20-JAN-12','DD-MON-RR'),sysdate,'admin',SYS_GUID())
/
INSERT INTO  TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
VALUES (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',3,46092,to_date('20-JAN-12','DD-MON-RR'),sysdate,'admin',SYS_GUID())
/
INSERT INTO  TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
VALUES (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',4,47820,to_date('20-JAN-12','DD-MON-RR'),sysdate,'admin',SYS_GUID())
/
INSERT INTO  TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
VALUES (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',5,49884,to_date('20-JAN-12','DD-MON-RR'),sysdate,'admin',SYS_GUID())
/
INSERT INTO  TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
VALUES (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',6,51582,to_date('20-JAN-12','DD-MON-RR'),sysdate,'admin',SYS_GUID())
/
INSERT INTO  TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
VALUES (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',7,54180,to_date('20-JAN-12','DD-MON-RR'),sysdate,'admin',SYS_GUID())
/
