CREATE TABLE AWARD_TRANSFERRING_SPONSOR ( 
	AWARD_TRANSFERRING_SPONSOR_ID NUMBER(12,0) NOT NULL, 
	AWARD_ID NUMBER(12,0) NOT NULL, 
	AWARD_NUMBER VARCHAR2(12) NOT NULL, 
	SEQUENCE_NUMBER NUMBER(4,0) NOT NULL, 
	SPONSOR_CODE CHAR(6) NOT NULL, 
	UPDATE_TIMESTAMP DATE NOT NULL, 
	UPDATE_USER VARCHAR2(60) NOT NULL, 
	VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
	OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL);
	
ALTER TABLE AWARD_TRANSFERRING_SPONSOR 
ADD CONSTRAINT PK_AWARD_TRANSFERRING_SPONSOR 
PRIMARY KEY (AWARD_TRANSFERRING_SPONSOR_ID);

ALTER TABLE AWARD_TRANSFERRING_SPONSOR 
ADD CONSTRAINT UQ_AWARD_TRANSFERRING_SPONSOR 
UNIQUE (AWARD_NUMBER, SEQUENCE_NUMBER, SPONSOR_CODE);

