ALTER TABLE BUDGET_SUB_AWARD_FILES ADD BUDGET_ID NUMBER (12, 0) ;

ALTER TABLE BUDGET_SUB_AWARD_FILES DROP PRIMARY KEY;

ALTER TABLE BUDGET_SUB_AWARD_FILES MODIFY PROPOSAL_NUMBER NULL;

ALTER TABLE BUDGET_SUB_AWARD_FILES MODIFY VERSION_NUMBER NULL;

UPDATE BUDGET_SUB_AWARD_FILES 
SET BUDGET_ID=(SELECT BUDGET_ID FROM BUDGET 
               WHERE BUDGET.PROPOSAL_NUMBER = BUDGET_SUB_AWARD_FILES.PROPOSAL_NUMBER
                     AND BUDGET.VERSION_NUMBER = BUDGET_SUB_AWARD_FILES.VERSION_NUMBER) ;

COMMIT;

ALTER TABLE BUDGET_SUB_AWARD_FILES 
    ADD CONSTRAINT PK_BUDGET_SUB_AWARD_FILES 
            PRIMARY KEY (BUDGET_ID, SUB_AWARD_NUMBER) ;

ALTER TABLE BUDGET_SUB_AWARD_FILES 
    ADD CONSTRAINT FK1_BUDGET_SUB_AWARD_FILES 
            FOREIGN KEY (BUDGET_ID, SUB_AWARD_NUMBER) 
                REFERENCES BUDGET_SUB_AWARDS;