ALTER TABLE BUDGET_MODULAR ADD BUDGET_ID NUMBER (12, 0) ;

ALTER TABLE BUDGET_MODULAR DROP PRIMARY KEY;

ALTER TABLE BUDGET_MODULAR MODIFY PROPOSAL_NUMBER NULL;

ALTER TABLE BUDGET_MODULAR MODIFY VERSION_NUMBER NULL;

UPDATE BUDGET_MODULAR 
SET BUDGET_ID=(SELECT BUDGET_ID FROM BUDGET 
               WHERE BUDGET.PROPOSAL_NUMBER = BUDGET_MODULAR.PROPOSAL_NUMBER
                     AND BUDGET.VERSION_NUMBER = BUDGET_MODULAR.VERSION_NUMBER) ;

COMMIT;

ALTER TABLE BUDGET_MODULAR 
    ADD CONSTRAINT PK_BUDGET_MODULAR 
            PRIMARY KEY (BUDGET_PERIOD_NUMBER) ;

ALTER TABLE BUDGET_MODULAR 
    ADD CONSTRAINT FK1_BUDGET_MODULAR FOREIGN KEY (BUDGET_PERIOD_NUMBER) 
                REFERENCES BUDGET_PERIODS;