-- Table Script  
CREATE TABLE QUESTIONNAIRE_USAGE (
    QUESTIONNAIRE_USAGE_ID NUMBER (12, 0) NOT NULL, 
    MODULE_ITEM_CODE NUMBER (3, 0) NOT NULL, 
    MODULE_SUB_ITEM_CODE NUMBER (3, 0) NOT NULL, 
    QUESTIONNAIRE_REF_ID_FK NUMBER (12, 0) NOT NULL, 
    QUESTIONNAIRE_SEQUENCE_NUMBER NUMBER (4, 0) NOT NULL, 
    RULE_ID NUMBER (6, 0) , 
    QUESTIONNAIRE_LABEL VARCHAR2 (50) , 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2 (60) NOT NULL, 
    VER_NBR NUMBER (8, 0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2 (36) DEFAULT SYS_GUID () NOT NULL) ;

-- Primary Key Constraint  
ALTER TABLE QUESTIONNAIRE_USAGE 
    ADD CONSTRAINT PK_QUESTIONNAIRE_USAGE 
            PRIMARY KEY (QUESTIONNAIRE_USAGE_ID) ;

-- *************** UNIQUE CONSTRAINT DEFINED FOR COMPOSITE KEY COLUMNS ************  
ALTER TABLE QUESTIONNAIRE_USAGE 
    ADD CONSTRAINT UQ_QUESTIONNAIRE_USAGE 
            UNIQUE (MODULE_ITEM_CODE, MODULE_SUB_ITEM_CODE, QUESTIONNAIRE_REF_ID_FK, QUESTIONNAIRE_SEQUENCE_NUMBER) ;