CREATE TABLE AWARD_COST_SHARE ( 
	AWARD_COST_SHARE_ID		NUMBER(8,0),
    AWARD_ID       			NUMBER,
    AWARD_NUMBER			VARCHAR2(12),
    SEQUENCE_NUMBER        	NUMBER(8,0),
    FISCAL_YEAR            	VARCHAR2(4),
    COST_SHARE_PERCENTAGE	NUMBER(5,2),
    COST_SHARE_TYPE_CODE 	NUMBER(3,0),
    SOURCE         			VARCHAR2(7),
    DESTINATION		    	VARCHAR2(7),
    COMMITMENT_AMOUNT       NUMBER(12,2),
    VERIFICATION_DATE DATE, 
    COST_SHARE_MET NUMBER(12,2),
    UPDATE_TIMESTAMP       	DATE,
    UPDATE_USER            	VARCHAR2(60),
    VER_NBR 				NUMBER(8,0) DEFAULT 1,
	OBJ_ID 					VARCHAR2(36) DEFAULT SYS_GUID()
);

alter table AWARD_COST_SHARE 
ADD CONSTRAINT PK_AWARD_COST_SHARE 
PRIMARY KEY(AWARD_COST_SHARE_ID) ENABLE;

alter table AWARD_COST_SHARE 
ADD CONSTRAINT U_AWARD_COST_SHARE 
UNIQUE(AWARD_NUMBER,SEQUENCE_NUMBER,FISCAL_YEAR,COST_SHARE_TYPE_CODE,SOURCE,DESTINATION) ENABLE;

CREATE SEQUENCE SEQ_AWARD_COST_SHARE_ID START WITH 1 MAXVALUE 99999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
