CREATE TABLE PROTOCOL_ATTACHMENT_STATUS (
    STATUS_CD VARCHAR2 (3) NOT NULL ENABLE, 
    DESCRIPTION VARCHAR2 (300) NOT NULL ENABLE, 
    VER_NBR NUMBER (8, 0) DEFAULT 1 NOT NULL ENABLE, 
    OBJ_ID VARCHAR2 (36) NOT NULL ENABLE, 
    UPDATE_TIMESTAMP DATE NOT NULL ENABLE, 
    UPDATE_USER VARCHAR2 (60) NOT NULL ENABLE) ;

ALTER TABLE PROTOCOL_ATTACHMENT_STATUS 
    ADD CONSTRAINT PK_PROTOCOL_ATTACHMENT_STATUS 
            PRIMARY KEY (STATUS_CD) ;

--ALTER TABLE PROTOCOL_ATTACHMENT_STATUS 
--    ADD CONSTRAINT UQ_PA_STATUS 
--            UNIQUE (DESCRIPTION) ;

