DROP INDEX PK_BUDGET_SUB_AWARD_ATT_KRA;

ALTER TABLE S2S_APP_ATTACHMENTS ADD S2S_APP_ATTACHMENT_ID NUMBER (12, 0) ;

ALTER TABLE S2S_APP_ATTACHMENTS DROP PRIMARY KEY;

DROP INDEX PK_S2S_ATTACHMENTS_KRA;

ALTER TABLE S2S_APP_ATTACHMENTS 
    ADD CONSTRAINT PK_S2S_APP_ATTACHMENTS_KRA 
            PRIMARY KEY (S2S_APP_ATTACHMENT_ID) ;