CREATE TABLE AWARD_TEMPLATE_CONTACT (
    AWARD_TEMPLATE_CONTACT_ID NUMBER (12, 0) NOT NULL, 
    AWARD_TEMPLATE_CODE NUMBER (5, 0) NOT NULL, 
    CONTACT_TYPE_CODE VARCHAR2 (3) NOT NULL, 
    ROLODEX_ID NUMBER (6, 0) NOT NULL, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2 (60) NOT NULL, 
    VER_NBR NUMBER (8, 0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2 (36) DEFAULT SYS_GUID () NOT NULL) ;

ALTER TABLE AWARD_TEMPLATE_CONTACT 
    ADD CONSTRAINT PK_AWARD_TEMPLATE_CONTACT 
            PRIMARY KEY (AWARD_TEMPLATE_CONTACT_ID) ;

ALTER TABLE AWARD_TEMPLATE_CONTACT 
    ADD CONSTRAINT UQ_AWARD_TEMPLATE_CONTACT 
            UNIQUE (AWARD_TEMPLATE_CODE, CONTACT_TYPE_CODE, ROLODEX_ID) ;