ALTER TABLE BUDGET_MODULAR_IDC 
    DROP CONSTRAINT FK_BUDGET_MODULAR_IDC_KRA;

ALTER TABLE BUDGET_MODULAR 
    DROP CONSTRAINT FK_BUDGET_MODULAR_BP_KRA;

ALTER TABLE BUDGET_MODULAR 
    DROP CONSTRAINT FK_PROPOSAL_MODULAR_KRA;

ALTER TABLE BUDGET_PROJECT_INCOME 
    DROP CONSTRAINT FK_BUDGET_PROJ_INC_BUDGET_KRA;

ALTER TABLE EPS_PROP_COST_SHARING 
    DROP CONSTRAINT FK_EPS_PROP_COST_SHARING_KRA;

ALTER TABLE EPS_PROP_IDC_RATE 
    DROP CONSTRAINT FK_EPS_PROP_IDC_RATE_KRA;

ALTER TABLE BUDGET DROP PRIMARY KEY;

UPDATE BUDGET 
SET BUDGET_ID=SEQ_BUDGET_ID.NEXTVAL;

COMMIT;

ALTER TABLE BUDGET MODIFY PROPOSAL_NUMBER NULL;

ALTER TABLE BUDGET MODIFY VERSION_NUMBER NULL;

ALTER TABLE BUDGET 
    ADD CONSTRAINT PK_BUDGET 
            PRIMARY KEY (BUDGET_ID) ;