CREATE TABLE BUDGET_DOCUMENT (
    DOCUMENT_NUMBER VARCHAR2 (10 BYTE) NOT NULL ENABLE, 
    PARENT_DOCUMENT_KEY VARCHAR2 (10 BYTE) ,
    PARENT_DOCUMENT_TYPE_CODE varchar2 (10) , 
    VER_NBR NUMBER (8, 0) DEFAULT 1 NOT NULL ENABLE, 
    OBJ_ID VARCHAR2 (36 BYTE) DEFAULT SYS_GUID () NOT NULL ENABLE, 
    UPDATE_TIMESTAMP DATE NOT NULL ENABLE, 
    UPDATE_USER VARCHAR2 (10 BYTE) NOT NULL ENABLE) ;

ALTER TABLE BUDGET_DOCUMENT 
    ADD CONSTRAINT PK_BUDGET_DOCUMENT 
            PRIMARY KEY (DOCUMENT_NUMBER) ;