CREATE TABLE COMMENT_TYPE (
    COMMENT_TYPE_CODE VARCHAR2 (3) , 
    DESCRIPTION VARCHAR2 (200) , 
    TEMPLATE_FLAG VARCHAR2 (1) , 
    CHECKLIST_FLAG VARCHAR2 (1) , 
    AWARD_COMMENT_SCREEN_FLAG VARCHAR2 (1) , 
    UPDATE_TIMESTAMP DATE, 
    UPDATE_USER VARCHAR2 (60) , 
    VER_NBR NUMBER (8, 0) DEFAULT 1, 
    OBJ_ID VARCHAR2 (36) DEFAULT SYS_GUID () ) ;

ALTER TABLE COMMENT_TYPE 
    ADD CONSTRAINT PK_COMMENT_TYPE 
            PRIMARY KEY (COMMENT_TYPE_CODE) ENABLE;