CREATE TABLE AWARD_COMMENT ( 
	AWARD_COMMENT_ID			NUMBER(8,0),
	AWARD_ID					NUMBER,
	AWARD_NUMBER				VARCHAR2(12),
	SEQUENCE_NUMBER				NUMBER(8,0),
	COMMENT_TYPE_CODE			VARCHAR2(3),
	CHECKLIST_PRINT_FLAG		VARCHAR2(1),
	COMMENTS					CLOB,
    UPDATE_TIMESTAMP       		DATE,
    UPDATE_USER            		VARCHAR2(60),
    VER_NBR 					NUMBER(8,0) DEFAULT 1,
	OBJ_ID 						VARCHAR2(36) DEFAULT SYS_GUID()
);

alter table AWARD_COMMENT 
ADD CONSTRAINT PK_AWARD_COMMENT 
PRIMARY KEY(AWARD_COMMENT_ID) ENABLE;

CREATE SEQUENCE SEQ_AWARD_COMMENT_ID START WITH 1 MAXVALUE 99999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
