ALTER TABLE BUDGET_DETAILS DROP PRIMARY KEY CASCADE;

ALTER TABLE BUDGET_DETAILS MODIFY PROPOSAL_NUMBER NULL;

ALTER TABLE BUDGET_DETAILS MODIFY VERSION_NUMBER NULL;

ALTER TABLE BUDGET_DETAILS 
	ADD (HIERARCHY_PROPOSAL_NUMBER VARCHAR (12) , 
		HIDE_IN_HIERARCHY CHAR (1) DEFAULT 'N' NOT NULL,
		BUDGET_DETAILS_ID NUMBER (12,0) ,
		BUDGET_ID NUMBER (12, 0) )
	MODIFY (PROPOSAL_NUMBER NULL,
		VERSION_NUMBER NULL);

ALTER TABLE BUDGET_DETAILS 
    ADD CONSTRAINT BUDGET_DETAILS_PK 
            PRIMARY KEY (BUDGET_DETAILS_ID) ;
