CREATE TABLE AWARD_SPONSOR_TERM ( 
	AWARD_SPONSOR_TERM_ID	NUMBER(8,0),
    AWARD_ID       			NUMBER(22,0),
    AWARD_NUMBER			VARCHAR2(12),
    SEQUENCE_NUMBER        	NUMBER(8,0),
    SPONSOR_TERM_ID			NUMBER(12,0),
    UPDATE_TIMESTAMP       	DATE,
    UPDATE_USER            	VARCHAR2(60),
    VER_NBR 				NUMBER(8,0) DEFAULT 1,
	OBJ_ID 					VARCHAR2(36) DEFAULT SYS_GUID()
);

ALTER TABLE AWARD_SPONSOR_TERM 
ADD CONSTRAINT PK_AWARD_SPONSOR_TERM 
PRIMARY KEY (AWARD_SPONSOR_TERM_ID);

ALTER TABLE AWARD_SPONSOR_TERM
ADD CONSTRAINT U_AWARD_SPONSOR_TERM
UNIQUE (AWARD_SPONSOR_TERM_CODE,AWARD_SPONSOR_TERM_TYPE_CODE);

CREATE SEQUENCE SEQ_AWARD_SPONSOR_TERMS INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_AWARD_SPONSOR_TERM START WITH 1 MAXVALUE 99999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
