-- Table Script 
CREATE TABLE PROPOSAL_IP_REV_ACTIVITY ( 
    PROPOSAL_IP_REV_ACTIVITY_ID NUMBER(12,0) NOT NULL,
    PROPOSAL_ID NUMBER(12,0) NOT NULL, 
    PROPOSAL_NUMBER VARCHAR2(8) NOT NULL, 
    SEQUENCE_NUMBER NUMBER(4,0) NOT NULL, 
    ACTIVITY_NUMBER NUMBER(3,0) NOT NULL, 
    IP_REVIEW_ACTIVITY_TYPE_CODE VARCHAR2(3) NOT NULL, 
    ACTIVITY_DATE DATE, 
    COMMENTS VARCHAR2(150), 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2(60) NOT NULL, 
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL);


-- Primary Key Constraint 
ALTER TABLE PROPOSAL_IP_REV_ACTIVITY 
ADD CONSTRAINT PK_PROPOSAL_IP_REV_ACTIVITY 
PRIMARY KEY (PROPOSAL_IP_REV_ACTIVITY_ID);

-- *************** UNIQUE CONSTRAINT DEFINED FOR COMPOSITE KEY COLUMNS ************ 
ALTER TABLE PROPOSAL_IP_REV_ACTIVITY 
ADD CONSTRAINT UQ_PROPOSAL_IP_REV_ACTIVITY 
UNIQUE (PROPOSAL_NUMBER, SEQUENCE_NUMBER, ACTIVITY_NUMBER);

