DELIMITER /
INSERT INTO KRA_USER (USER_ID,PERSON_ID,USER_NAME,USER_TYPE,UNIT_NUMBER,NON_MIT_PERSON_FLAG,STATUS,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES ('KRADEV',null,'Coeus Super User',null,'000001','Y','A','admin',NOW(),UUID(),1)
/
DELIMITER ;
