DELIMITER /
INSERT INTO KREW_OUT_BOX_ITM_S VALUES(NULL)
/
INSERT INTO KREW_OUT_BOX_ITM_T (ACTN_ITM_ID,DOC_HDR_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,ACTN_RQST_ID,RQST_CD,PRNCPL_ID,ROLE_NM,ASND_DT,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM KREW_OUT_BOX_ITM_S),4101,'KC Award - Sync Descendants, 300120','KC Award','${kuali.docHandler.url.prefix}/awardHome.do?methodToCall=docHandler','AwardDocument',10006,10117,'A',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),'ROUTED_BY_USER',NOW(),1)
/
INSERT INTO KREW_OUT_BOX_ITM_S VALUES(NULL)
/
INSERT INTO KREW_OUT_BOX_ITM_T (ACTN_ITM_ID,DOC_HDR_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,ACTN_RQST_ID,RQST_CD,PRNCPL_ID,ROLE_NM,ASND_DT,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM KREW_OUT_BOX_ITM_S),4102,'KC Award - Created by Award 010002-00001 Ver 2','KC Award','${kuali.docHandler.url.prefix}/awardHome.do?methodToCall=docHandler','AwardDocument',-3,10121,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,NOW(),1)
/
INSERT INTO KREW_OUT_BOX_ITM_S VALUES(NULL)
/
INSERT INTO KREW_OUT_BOX_ITM_T (ACTN_ITM_ID,DOC_HDR_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,ACTN_RQST_ID,RQST_CD,PRNCPL_ID,ROLE_NM,ASND_DT,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM KREW_OUT_BOX_ITM_S),4103,'KC Award - Created by Award 010002-00001 Ver 2','KC Award','${kuali.docHandler.url.prefix}/awardHome.do?methodToCall=docHandler','AwardDocument',-3,10122,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,NOW(),1)
/
INSERT INTO KREW_OUT_BOX_ITM_S VALUES(NULL)
/
INSERT INTO KREW_OUT_BOX_ITM_T (ACTN_ITM_ID,DOC_HDR_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,ACTN_RQST_ID,RQST_CD,PRNCPL_ID,ROLE_NM,ASND_DT,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM KREW_OUT_BOX_ITM_S),4104,'KC Award - Created by Award 010002-00001 Ver 2','KC Award','${kuali.docHandler.url.prefix}/awardHome.do?methodToCall=docHandler','AwardDocument',-3,10123,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,NOW(),1)
/
INSERT INTO KREW_OUT_BOX_ITM_S VALUES(NULL)
/
INSERT INTO KREW_OUT_BOX_ITM_T (ACTN_ITM_ID,DOC_HDR_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,ACTN_RQST_ID,RQST_CD,PRNCPL_ID,ROLE_NM,ASND_DT,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM KREW_OUT_BOX_ITM_S),4105,'KC Award - Created by Award 010002-00001 Ver 2','KC Award','${kuali.docHandler.url.prefix}/awardHome.do?methodToCall=docHandler','AwardDocument',-3,10124,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,NOW(),1)
/
INSERT INTO KREW_OUT_BOX_ITM_S VALUES(NULL)
/
INSERT INTO KREW_OUT_BOX_ITM_T (ACTN_ITM_ID,DOC_HDR_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,ACTN_RQST_ID,RQST_CD,PRNCPL_ID,ROLE_NM,ASND_DT,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM KREW_OUT_BOX_ITM_S),4106,'KC Award - Created by Award 010002-00001 Ver 2','KC Award','${kuali.docHandler.url.prefix}/awardHome.do?methodToCall=docHandler','AwardDocument',-3,10125,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,NOW(),1)
/
INSERT INTO KREW_OUT_BOX_ITM_S VALUES(NULL)
/
INSERT INTO KREW_OUT_BOX_ITM_T (ACTN_ITM_ID,DOC_HDR_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,ACTN_RQST_ID,RQST_CD,PRNCPL_ID,ROLE_NM,ASND_DT,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM KREW_OUT_BOX_ITM_S),4107,'KC Award - Created by Award 010002-00001 Ver 2','KC Award','${kuali.docHandler.url.prefix}/awardHome.do?methodToCall=docHandler','AwardDocument',-3,10126,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,NOW(),1)
/
INSERT INTO KREW_OUT_BOX_ITM_S VALUES(NULL)
/
INSERT INTO KREW_OUT_BOX_ITM_T (ACTN_ITM_ID,DOC_HDR_ID,DOC_HDR_TTL,DOC_TYP_LBL,DOC_HDLR_URL,DOC_TYP_NM,RSP_ID,ACTN_RQST_ID,RQST_CD,PRNCPL_ID,ROLE_NM,ASND_DT,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM KREW_OUT_BOX_ITM_S),4108,'KC Award - Created by Award 010002-00001 Ver 2','KC Award','${kuali.docHandler.url.prefix}/awardHome.do?methodToCall=docHandler','AwardDocument',-3,10127,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,NOW(),1)
/
DELIMITER ;
