@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/tables/EPS_PROPOSAL_STATUS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/tables/OSP$BUD_PER_SAL_DET_PRN_TMP.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/tables/OSP$EPS_PROP_PERSON_BIO_SOURCE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/tables/OSP$PROPOSAL.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/tables/OSP$PROPOSAL_ADMIN_DETAILS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/tables/OSP$SPONSOR_HIERARCHY.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/tables/OSP$SCHOOL_CODE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/tables/OSP$PARAMETER.sql

@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/data/load_SPONSOR_HIERARCHY.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/data/load_OSP$PARAMETER.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/data/load_ORGANIZATION_TYPE.sql


@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$ABSTRACT_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$ACTIVITY_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_JUSTIFICATION.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$budget_modular_idc.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_MODULAR.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_PERSONS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_PROJECT_INCOME.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$COUNTRY_CODE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$DEGREE_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_ABSTRACT.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_IDC_RATE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_INVESTIGATORS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_KEY_PERSONS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_PERSON_BIO_PDF.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_PERSON_DEGREE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_PERSON.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_SCIENCE_CODE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_UNITS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROPOSAL_STATUS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROPOSAL.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$NSF_CODES.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$ORGANIZATION_AUDIT.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$ORGANIZATION_IDC.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$ORGANIZATION_TYPE_LIST.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$ORGANIZATION_YNQ.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$PERSON_BIO_PDF.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$PERSON_BIO_SOURCE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$PERSON_BIO.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$PROPOSAL_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$SCHOOL_CODE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$SCIENCE_CODE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$SP_REV_APPROVAL_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$SPECIAL_REVIEW.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$STATE_CODE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$UNIT_ADMINISTRATOR_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$UNIT_ADMINISTRATORS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$UNIT_HIERARCHY.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$UNIT.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$USER.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_LOCATION.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$NOTICE_OF_OPPORTUNITY.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$ORGANIZATION.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$ROLODEX.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_CATEGORY_MAPPING.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_CATEGORY_MAPS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_CATEGORY.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_DETAILS_CAL_AMTS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_DETAILS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_PERIODS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_PERSONNEL_CAL_AMTS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_PERSONNEL_DETAILS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_RATE_AND_BASE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_SUB_AWARD_ATT.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET_SUB_AWARDS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$COST_ELEMENT.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_LA_RATES.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_PER_DOC_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_PERSON_BIO.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_RATES.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$INSTITUTE_LA_RATES.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$INSTITUTE_RATES.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$JOB_CODE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$RATE_CLASS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$RATE_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$S2S_APP_ATTACHMENTS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$S2S_APP_SUBMISSION.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$S2S_APPLICATION.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$S2S_OPP_FORMS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$S2S_OPPORTUNITY.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$S2S_SUBMISSION_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$VALID_CALC_TYPES.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$VALID_CE_JOB_CODES.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$VALID_CE_RATE_TYPES.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_PER_CREDIT_SPLIT.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_SPECIAL_REVIEW.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$BUDGET.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_PERS_YNQ.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_UNIT_CREDIT_SPLIT.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_USER_ROLES.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_YNQ.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$INV_CREDIT_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$NARRATIVE_PDF.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$NARRATIVE_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$NARRATIVE_USER_RIGHTS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$NARRATIVE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$PERSON.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$PROPOSAL_INV_CERTIFICATION.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$RIGHTS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$ROLE_RIGHTS.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$ROLE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$SPONSOR_TYPE.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$SPONSOR.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$USER_ROLES.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$VALID_SP_REV_APPROVAL.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$YNQ_EXPLANATION.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$YNQ.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$EPS_PROP_COST_SHARING.sql
@/Users/geo/eclipse/workspace/kra_project/src/main/config/sql/s2s/views/OSP$ORGANIZATION_TYPE.sql