INSERT INTO COMM_DECISION_MOTION_TYPE (COMM_DECISION_MOTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID) VALUES ('1', 'Approve', sysdate, 'KRADEV', SYS_GUID());
INSERT INTO COMM_DECISION_MOTION_TYPE (COMM_DECISION_MOTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID) VALUES ('2', 'Disapprove', sysdate,'KRADEV', SYS_GUID());
INSERT INTO COMM_DECISION_MOTION_TYPE (COMM_DECISION_MOTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID) VALUES ('3', 'Specific Minor Revisions', sysdate, 'KRADEV', SYS_GUID());
INSERT INTO COMM_DECISION_MOTION_TYPE (COMM_DECISION_MOTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID) VALUES ('4', 'Substantive Revisions Required', sysdate, 'KRADEV', SYS_GUID());

COMMIT;
