UPDATE RATE_CLASS SET ICR_TYPE_CODE = 35 WHERE DESCRIPTION = 'MTDC';
UPDATE RATE_CLASS SET ICR_TYPE_CODE = 11 WHERE DESCRIPTION = 'TDC';
UPDATE RATE_CLASS SET ICR_TYPE_CODE = 36 WHERE DESCRIPTION = 'S\&W';
UPDATE RATE_CLASS SET ICR_TYPE_CODE = 11 WHERE DESCRIPTION LIKE '%Fund with Transaction%';
