INSERT INTO PROTOCOL_ONLN_RVW_STATUS (STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('F', 'FINAL', SYSDATE, 'kr', 1, SYS_GUID () ) ;

INSERT INTO PROTOCOL_ONLN_RVW_STATUS (STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('S', 'SAVED', SYSDATE, 'kr', 1, SYS_GUID () ) ;

COMMIT;
