INSERT INTO KRIM_ROLE_RSP_ACTN_T ( ROLE_RSP_ACTN_ID, OBJ_ID, VER_NBR, ACTN_TYP_CD, PRIORITY_NBR, ACTN_PLCY_CD, ROLE_MBR_ID, ROLE_RSP_ID, FRC_ACTN )
VALUES ( KRIM_ROLE_RSP_ACTN_ID_S.NEXTVAL, SYS_GUID(), 1, 'A',1,'F','*',(SELECT A.ROLE_RSP_ID FROM KRIM_ROLE_RSP_T A, KRIM_ROLE_RSP_T B, KRIM_RSP_T C, KRIM_ROLE_T D WHERE A.ROLE_RSP_ID = B.ROLE_RSP_ID AND B.RSP_ID = C.RSP_ID AND B.ROLE_ID = D.ROLE_ID AND C.NMSPC_CD = 'KC-WKFLW' AND C.NM = 'IRB Reviewer Approve Online Review' AND D.NMSPC_CD = 'KC-UNT' AND D.ROLE_NM = 'IRB Online Reviewer'),'N' );

COMMIT;