INSERT INTO PROTOCOL_TYPE(PROTOCOL_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID) 
    VALUES('5', 'Single Patient Use', SYSDATE, 'admin', 0, SYS_GUID());

INSERT INTO PROTOCOL_TYPE(PROTOCOL_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID) 
    VALUES('6', 'Expedited', SYSDATE, 'admin', 0, SYS_GUID());

INSERT INTO PROTOCOL_TYPE(PROTOCOL_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID) 
    VALUES('7', 'Full Board', SYSDATE, 'admin', 0, SYS_GUID());

COMMIT;
