INSERT INTO KRIM_RSP_ATTR_DATA_T ( ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL )
VALUES ( KRIM_ATTR_DATA_ID_S.NEXTVAL, SYS_GUID(), 1, (SELECT RSP_ID FROM KRIM_RSP_T WHERE NMSPC_CD = 'KC-WKFLW' AND NM = 'IRB Reviewer Approve Online Review'), 7, 13, 'ProtocolOnlineReviewDocument');

INSERT INTO KRIM_RSP_ATTR_DATA_T ( ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL )
VALUES ( KRIM_ATTR_DATA_ID_S.NEXTVAL, SYS_GUID(), 1, (SELECT RSP_ID FROM KRIM_RSP_T WHERE NMSPC_CD = 'KC-WKFLW' AND NM = 'IRB Reviewer Approve Online Review'), 7, 16, 'OnlineReviewer');

INSERT INTO KRIM_RSP_ATTR_DATA_T ( ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL )
VALUES ( KRIM_ATTR_DATA_ID_S.NEXTVAL, SYS_GUID(), 1, (SELECT RSP_ID FROM KRIM_RSP_T WHERE NMSPC_CD = 'KC-WKFLW' AND NM = 'IRB Reviewer Approve Online Review'), 7, 40, 'false');

INSERT INTO KRIM_RSP_ATTR_DATA_T ( ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL )
VALUES ( KRIM_ATTR_DATA_ID_S.NEXTVAL, SYS_GUID(), 1, (SELECT RSP_ID FROM KRIM_RSP_T WHERE NMSPC_CD = 'KC-WKFLW' AND NM = 'IRB Reviewer Approve Online Review'), 7, 41, 'false');

COMMIT;