DELIMITER /
INSERT INTO KREW_DOC_HDR_T (DOC_HDR_ID,DOC_TYP_ID,DOC_HDR_STAT_CD,RTE_LVL,STAT_MDFN_DT,CRTE_DT,APRV_DT,FNL_DT,RTE_STAT_MDFN_DT,TTL,APP_DOC_ID,DOC_VER_NBR,INITR_PRNCPL_ID,VER_NBR,RTE_PRNCPL_ID,DTYPE,OBJ_ID,APP_DOC_STAT,APP_DOC_STAT_MDFN_DT)
            VALUES ('KCIAC0209',(SELECT DOC_TYP_ID FROM KREW_DOC_TYP_T WHERE DOC_TYP_NM='CommonCommitteeDocument' AND CUR_IND=1),'F',0,NOW(),NOW(),NOW(),NOW(),NOW(),'Committee Document - IACUC Demo Committee',NULL,1,'10000000001',25,'10000000001',NULL,UUID(),NULL,NULL)
/


DELIMITER ;
