TRUNCATE TABLE KREW_USR_OPTN_T DROP STORAGE
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','ACTION_LIST_SIZE_NEW','10',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','ACTION_REQUESTED_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','CLEAR_FYI_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DATE_CREATED_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DELEGATOR_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DELEGATOR_FILTER','Secondary Delegators on Action List Page',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_A','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_C','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_D','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_E','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_F','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_I','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_P','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_R','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_S','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COLOR_X','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOCUMENT_STATUS_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DOC_TYPE_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Holding0',',,fromDateCreated=10/01/2008,,isAdvancedSearch=NO,,superUserSearch=NO',11)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Holding1',',,fromDateCreated=03/17/2009,,isAdvancedSearch=NO,,superUserSearch=NO',11)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Holding2',',,fromDateCreated=03/17/2009,,isAdvancedSearch=NO,,superUserSearch=NO',11)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Holding3',',,fromDateCreated=11/01/2008,,superUserSearch=NO',10)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Holding4',',,fromDateCreated=12/22/2008,,superUserSearch=NO',10)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','DocSearch.LastSearch.Order','DocSearch.LastSearch.Holding2,DocSearch.LastSearch.Holding1,DocSearch.LastSearch.Holding0,DocSearch.LastSearch.Holding4,DocSearch.LastSearch.Holding3',53)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','EMAIL_NOTIFICATION','immediate',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','EMAIL_NOTIFY_PRIMARY','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','EMAIL_NOTIFY_SECONDARY','no',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','INITIATOR_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','LAST_APPROVED_DATE_COL_SHOW_NEW','no',2)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','OPEN_ITEMS_NEW_WINDOW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','REFRESH_RATE','15',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','TITLE_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','USE_OUT_BOX','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('admin','WORKGROUP_REQUEST_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('employee','DocSearch.LastSearch.Holding0',',,fromDateCreated=12/22/2008,,superUserSearch=NO',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('employee','DocSearch.LastSearch.Order','DocSearch.LastSearch.Holding0',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('supervisor','DocSearch.LastSearch.Holding0',',,fromDateCreated=12/22/2008,,superUserSearch=NO',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('supervisor','DocSearch.LastSearch.Order','DocSearch.LastSearch.Holding0',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user1','DocSearch.LastSearch.Holding0',',,fromDateCreated=09/16/2008,,superUserSearch=NO',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user1','DocSearch.LastSearch.Order','DocSearch.LastSearch.Holding0',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','ACTION_LIST_SIZE_NEW','10',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','ACTION_REQUESTED_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','CLEAR_FYI_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DATE_CREATED_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DELEGATOR_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DELEGATOR_FILTER','Secondary Delegators on Action List Page',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOCUMENT_STATUS_COLOR_A','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOCUMENT_STATUS_COLOR_C','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOCUMENT_STATUS_COLOR_D','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOCUMENT_STATUS_COLOR_E','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOCUMENT_STATUS_COLOR_F','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOCUMENT_STATUS_COLOR_I','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOCUMENT_STATUS_COLOR_P','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOCUMENT_STATUS_COLOR_R','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOCUMENT_STATUS_COLOR_S','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOCUMENT_STATUS_COLOR_X','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOCUMENT_STATUS_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','DOC_TYPE_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','EMAIL_NOTIFICATION','immediate',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','EMAIL_NOTIFY_PRIMARY','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','EMAIL_NOTIFY_SECONDARY','no',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','INITIATOR_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','LAST_APPROVED_DATE_COL_SHOW_NEW','no',2)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','OPEN_ITEMS_NEW_WINDOW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','REFRESH_RATE','15',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','TITLE_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','USE_OUT_BOX','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user2','WORKGROUP_REQUEST_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','ACTION_LIST_SIZE_NEW','10',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','ACTION_REQUESTED_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','CLEAR_FYI_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DATE_CREATED_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DELEGATOR_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DELEGATOR_FILTER','Secondary Delegators on Action List Page',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOCUMENT_STATUS_COLOR_A','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOCUMENT_STATUS_COLOR_C','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOCUMENT_STATUS_COLOR_D','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOCUMENT_STATUS_COLOR_E','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOCUMENT_STATUS_COLOR_F','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOCUMENT_STATUS_COLOR_I','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOCUMENT_STATUS_COLOR_P','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOCUMENT_STATUS_COLOR_R','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOCUMENT_STATUS_COLOR_S','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOCUMENT_STATUS_COLOR_X','white',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOCUMENT_STATUS_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DOC_TYPE_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DocSearch.LastSearch.Holding0',',,fromDateCreated=12/22/2008,,superUserSearch=NO',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','DocSearch.LastSearch.Order','DocSearch.LastSearch.Holding0',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','EMAIL_NOTIFICATION','immediate',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','EMAIL_NOTIFY_PRIMARY','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','EMAIL_NOTIFY_SECONDARY','no',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','INITIATOR_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','LAST_APPROVED_DATE_COL_SHOW_NEW','no',2)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','OPEN_ITEMS_NEW_WINDOW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','REFRESH_RATE','15',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','TITLE_COL_SHOW_NEW','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','USE_OUT_BOX','yes',1)
/
INSERT INTO KREW_USR_OPTN_T (PRNCPL_ID,PRSN_OPTN_ID,VAL,VER_NBR)
  VALUES ('user4','WORKGROUP_REQUEST_COL_SHOW_NEW','yes',1)
/
