DELIMITER /
CREATE TABLE FIN_INT_ENTITY_STATUS ( 
    STATUS_CODE DECIMAL(3,0) NOT NULL, 
    DESCRIPTION VARCHAR(200) NOT NULL, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR(60) NOT NULL, 
    VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR(36) NOT NULL) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_bin
/
ALTER TABLE FIN_INT_ENTITY_STATUS 
ADD CONSTRAINT PK_FIN_INT_ENTITY_STATUS 
PRIMARY KEY (STATUS_CODE)
/
DELIMITER ;
