--REM INSERTING into COMM_SCHEDULE_ACT_ITEMS
Insert into COMM_SCHEDULE_ACT_ITEMS (COMM_SCHEDULE_ACT_ITEMS_ID,SCHEDULE_ID_FK,ACTION_ITEM_NUMBER,SCHEDULE_ACT_ITEM_TYPE_CODE,ITEM_DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
values (1,1,1,'1','Other business item',to_timestamp('06-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'KCDBA',0,SYS_GUID())
/

Insert into COMM_SCHEDULE_ACT_ITEMS (COMM_SCHEDULE_ACT_ITEMS_ID,SCHEDULE_ID_FK,ACTION_ITEM_NUMBER,SCHEDULE_ACT_ITEM_TYPE_CODE,ITEM_DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
values (2,1,2,'2','New membership consideration item',to_timestamp('06-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'KCDBA',0,SYS_GUID())
/

Insert into COMM_SCHEDULE_ACT_ITEMS (COMM_SCHEDULE_ACT_ITEMS_ID,SCHEDULE_ID_FK,ACTION_ITEM_NUMBER,SCHEDULE_ACT_ITEM_TYPE_CODE,ITEM_DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
values (3,1,3,'3','non-compliance item',to_timestamp('06-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'KCDBA',0,SYS_GUID())
/

Insert into COMM_SCHEDULE_ACT_ITEMS (COMM_SCHEDULE_ACT_ITEMS_ID,SCHEDULE_ID_FK,ACTION_ITEM_NUMBER,SCHEDULE_ACT_ITEM_TYPE_CODE,ITEM_DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
values (4,1,4,'4','Protocol deviation item',to_timestamp('06-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'KCDBA',0,SYS_GUID())
/

INSERT INTO COMM_SCHEDULE_ACT_ITEMS (COMM_SCHEDULE_ACT_ITEMS_ID,SCHEDULE_ID_FK,ACTION_ITEM_NUMBER,SCHEDULE_ACT_ITEM_TYPE_CODE,ITEM_DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
VALUES (5,1,5,'5','Adverse event item',TO_TIMESTAMP('06-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'KCDBA',0,SYS_GUID())
/

