--REM INSERTING into KREW_ACTN_RQST_T
INSERT INTO KREW_ACTN_RQST_T (ACTN_RQST_ID,ACTN_RQST_CD,DOC_HDR_ID,STAT_CD,RSP_ID,PRNCPL_ID,RECIP_TYP_CD,PRIO_NBR,RTE_LVL_NBR,RTE_NODE_INSTN_ID,ACTN_TKN_ID,DOC_VER_NBR,CRTE_DT,RSP_DESC_TXT,FRC_ACTN,APPR_PLCY,CUR_IND,VER_NBR) 
VALUES (2371,'C',3091,'D',-3,'10000000001','U',0,0,3672,2332,1,TO_TIMESTAMP('08-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'Initiator needs to complete document.',1,'F',1,0);

INSERT INTO KREW_ACTN_RQST_T (ACTN_RQST_ID,ACTN_RQST_CD,DOC_HDR_ID,STAT_CD,RSP_ID,PRNCPL_ID,RECIP_TYP_CD,PRIO_NBR,RTE_LVL_NBR,RTE_NODE_INSTN_ID,ACTN_TKN_ID,DOC_VER_NBR,CRTE_DT,RSP_DESC_TXT,FRC_ACTN,APPR_PLCY,CUR_IND,VER_NBR) 
VALUES (2372,'C',3092,'D',-3,'10000000001','U',0,0,3676,2334,1,TO_TIMESTAMP('08-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'Initiator needs to complete document.',1,'F',1,0);

INSERT INTO KREW_ACTN_RQST_T (ACTN_RQST_ID,ACTN_RQST_CD,DOC_HDR_ID,STAT_CD,RSP_ID,PRNCPL_ID,RECIP_TYP_CD,PRIO_NBR,RTE_LVL_NBR,RTE_NODE_INSTN_ID,ACTN_TKN_ID,DOC_VER_NBR,CRTE_DT,RSP_DESC_TXT,FRC_ACTN,APPR_PLCY,CUR_IND,VER_NBR) 
VALUES (2373,'C',3093,'D',-3,'10000000001','U',0,0,3680,2336,1,TO_TIMESTAMP('08-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'Initiator needs to complete document.',1,'F',1,0);

INSERT INTO KREW_ACTN_RQST_T (ACTN_RQST_ID,ACTN_RQST_CD,DOC_HDR_ID,STAT_CD,RSP_ID,PRNCPL_ID,RECIP_TYP_CD,PRIO_NBR,RTE_LVL_NBR,RTE_NODE_INSTN_ID,ACTN_TKN_ID,DOC_VER_NBR,CRTE_DT,RSP_DESC_TXT,FRC_ACTN,APPR_PLCY,CUR_IND,VER_NBR) 
VALUES (2374,'C',3094,'D',-3,'10000000001','U',0,0,3684,2338,1,TO_TIMESTAMP('08-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'Initiator needs to complete document.',1,'F',1,0);
