set define off 
@kr_sd_009_load_KREW_ACTN_ITM_T.sql 
@kr_sd_010_load_KREW_ACTN_RQST_T.sql 
@kr_sd_011_load_KREW_ACTN_TKN_T.sql 
@kr_sd_015_load_KREW_DOC_HDR_CNTNT_T.sql 
@kr_sd_020_load_KREW_DOC_HDR_T.sql 
@kr_sd_033_load_KREW_INIT_RTE_NODE_INSTN_T.sql 
@kr_sd_034_load_KREW_OUT_BOX_ITM_T.sql 
@kr_sd_039_load_KREW_RTE_BRCH_ST_T.sql 
@kr_sd_040_load_KREW_RTE_BRCH_T.sql 
@kr_sd_043_load_KREW_RTE_NODE_INSTN_LNK_T.sql 
@kr_sd_043_load_KREW_RTE_NODE_INSTN_T.sql 
@kr_sd_066_load_KRIM_ENTITY_T.sql 
@kr_sd_129_load_KREN_NTFCTN_T.sql 
@kr_sd_135_load_KRIM_ENTITY_ENT_TYP_T.sql 
@kr_sd_138_load_KRIM_ENTITY_NM_T.sql 
@kr_sd_144_load_KRIM_PRNCPL_T.sql 
@kr_sd_145_load_KRIM_ROLE_MBR_ATTR_DATA_T.sql 
@kr_sd_162_load_KREN_NTFCTN_MSG_DELIV_T.sql 
@kr_sd_163_load_KREN_RECIP_T.sql 
@kr_sd_164_load_KREN_SNDR_T.sql 
@kr_sd_166_load_KRIM_ENTITY_ADDR_T.sql 
@kr_sd_167_load_KRIM_ENTITY_EMAIL_T.sql 
@kr_sd_168_load_KRIM_ENTITY_EMP_INFO_T.sql 
@kr_sd_169_load_KRIM_ENTITY_PHONE_T.sql 
@kr_sd_171_load_KRIM_ROLE_MBR_T.sql 
@kr_sd_172_load_KRIM_GRP_MBR_T.sql
exit; 
