delimiter /

INSERT INTO SEQ_PERSON_EDITABLE_FIELD VALUES (NULL)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES ((SELECT MAX(ID) FROM SEQ_PERSON_EDITABLE_FIELD),(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'firstName','Y','admin',NOW(),UUID(),1)
/
INSERT INTO SEQ_PERSON_EDITABLE_FIELD VALUES (NULL)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES ((SELECT MAX(ID) FROM SEQ_PERSON_EDITABLE_FIELD),(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'lastName','Y','admin',NOW(),UUID(),1)
/
INSERT INTO SEQ_PERSON_EDITABLE_FIELD VALUES (NULL)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES ((SELECT MAX(ID) FROM SEQ_PERSON_EDITABLE_FIELD),(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'middleName','Y','admin',NOW(),UUID(),1)
/
delimiter ;
