--
-- Kuali Coeus, a comprehensive research administration system for higher education.
-- 
-- Copyright 2005-2015 Kuali, Inc.
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as
-- published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
-- 
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
--

DELIMITER /
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0001','KC-CGB Demo Data - LOC - by award',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0002','KC-CGB Demo Data - LOC - by account',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0003','KC-CGB Demo Data - LOC - by cc acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0004','KC-CGB Demo Data - MILE - by acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0005','KC-CGB Demo Data - PD - by acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0006','KC-CGB Demo Data - MONTHLY - by award',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0007','KC-CGB Demo Data - MONTHLY - by acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0008','KC-CGB Demo Data - MONTHLY - by cc acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0009','KC-CGB Demo Data - LOC - by award',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0010','KC-CGB Demo Data - LOC - by award',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0011','KC-CGB Demo Data - LOC - by award',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0012','KC-CGB Demo Data - LOC - by acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0013','KC-CGB Demo Data - LOC - by acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0014','KC-CGB Demo Data - LOC - by cc acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0015','KC-CGB Demo Data - LOC - by cc acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0016','KC-CGB Demo Data - LOC - by cc acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0017','KC-CGB Demo Data - LOC - by cc acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0018','KC-CGB Demo Data - LOC - by cc acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0019','KC-CGB Demo Data - MILE - by acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0020','KC-CGB Demo Data - PD - by acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0021','KC-CGB Demo Data - MONTHLY - by award',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0022','KC-CGB Demo Data - MONTHLY - by award',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0023','KC-CGB Demo Data - MONTHLY - by award',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0024','KC-CGB Demo Data - MONTHLY by acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0025','KC-CGB Demo Data - MONTHLY by acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0026','KC-CGB Demo Data - MONTHLY - by cc acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0027','KC-CGB Demo Data - MONTHLY - by cc acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0028','KC-CGB Demo Data - MONTHLY - by cc acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0029','KC-CGB Demo Data - MONTHLY - by cc acct',UUID(),16)
/

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('KCCGB0030','KC-CGB Demo Data - MONTHLY - by cc acct',UUID(),16)
/

 
DELIMITER ;
