DELIMITER /

DROP TABLE IACUC_PROTO_STUDY_GROUP_LOCS
/

CREATE TABLE IACUC_PROTO_STUDY_GROUP_LOCS ( 
    IACUC_PROT_STUD_GROU_LOCS_ID DECIMAL(12,0) NOT NULL,
    IACUC_PROTOCOL_STUDY_GROUP_ID DECIMAL(12,0) NOT NULL,
    STUDY_GROUP_LOCATION_ID DECIMAL(3,0) NOT NULL, 
    LOCATION_TYPE_CODE DECIMAL(3,0) NOT NULL, 
    LOCATION_ID DECIMAL(3,0) NOT NULL, 
    STUDY_GROUP_LOCATION_DESC VARCHAR(2000), 
    LOCATION_ROOM VARCHAR(60),
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR(60) NOT NULL, 
    VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR(36) NOT NULL) 
/

ALTER TABLE IACUC_PROTO_STUDY_GROUP_LOCS 
ADD CONSTRAINT PK_IACUC_PROTO_STUDY_GROUP_LOC 
PRIMARY KEY (IACUC_PROT_STUD_GROU_LOCS_ID) 
/

DELIMITER ;
