DELIMITER /

CREATE TABLE IACUC_PROTO_REVIEW_TYPE_DETER
(  PROTOCOL_REVIEW_TYPE_CODE DECIMAL(3,0) NOT NULL
   , UPDATE_TIMESTAMP DATETIME NOT NULL
   , UPDATE_USER VARCHAR(60) NOT NULL
   , VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL
   , OBJ_ID VARCHAR(36) NOT NULL
 )
/

ALTER TABLE IACUC_PROTO_REVIEW_TYPE_DETER
ADD CONSTRAINT IACUC_PROTO_REV_TYPE_DETER_PK
PRIMARY KEY (PROTOCOL_REVIEW_TYPE_CODE)
/

DELIMITER ;