CREATE TABLE PMC_EPS_PROPOSAL (
  PMC_EPS_PROPOSAL_ID   NUMBER(12,0) NOT NULL,
  PERSON_MASS_CHANGE_ID NUMBER(12,0) NOT NULL,
  INVESTIGATOR          CHAR(1) DEFAULT 'N' NOT NULL,
  MAILING_INFORMATION   CHAR(1) DEFAULT 'N' NOT NULL,
  KEY_STUDY_PERSON      CHAR(1) DEFAULT 'N' NOT NULL,
  UPDATE_USER           VARCHAR2(60) NOT NULL, 
  UPDATE_TIMESTAMP      DATE NOT NULL, 
  OBJ_ID                VARCHAR2(36) NOT NULL,
  VER_NBR               NUMBER(8,0) DEFAULT 1 NOT NULL
)
/
ALTER TABLE PMC_EPS_PROPOSAL ADD CONSTRAINT PK_PMC_EPS_PROPOSAL
  PRIMARY KEY (PMC_EPS_PROPOSAL_ID)
/
