CREATE TABLE NEGOTIATION_PMC (
  NEGOTIATION_PMC_ID    NUMBER(12,0) NOT NULL,
  PERSON_MASS_CHANGE_ID NUMBER(12,0) NOT NULL,
  NEGOTIATOR            CHAR(1) DEFAULT 'N' NOT NULL,
  UPDATE_USER           VARCHAR2(60) NOT NULL, 
  UPDATE_TIMESTAMP      DATE NOT NULL, 
  OBJ_ID                VARCHAR2(36) NOT NULL,
  VER_NBR               NUMBER(8,0) DEFAULT 1 NOT NULL
)
/
ALTER TABLE NEGOTIATION_PMC ADD CONSTRAINT PK_NEGOTIATION_PMC
  PRIMARY KEY (NEGOTIATION_PMC_ID)
/
