CREATE TABLE SUBAWARD_CONTACT 
   (	SUBAWARD_CONTACT_ID NUMBER(12,0) NOT NULL, 
	SUBAWARD_ID NUMBER(12,0) NOT NULL, 
	CONTACT_TYPE_CODE VARCHAR2(3 BYTE) NOT NULL, 
	ROLODEX_ID NUMBER(6,0) NOT NULL, 
	UPDATE_TIMESTAMP DATE NOT NULL, 
	UPDATE_USER VARCHAR2(60 BYTE) NOT NULL, 
	VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
	OBJ_ID VARCHAR2(36 BYTE) DEFAULT SYS_GUID() NOT NULL,
	SEQUENCE_NUMBER NUMBER(4,0) NOT NULL,
	SUBAWARD_CODE VARCHAR2(20 BYTE) NOT NULL
  )
/
ALTER TABLE SUBAWARD_CONTACT
  ADD CONSTRAINT PK_SUBAWARD_CONTACT PRIMARY KEY (SUBAWARD_CONTACT_ID)
/
