CREATE TABLE COI_DISC_DETAILS ( 
    COI_DISC_DETAILS_ID NUMBER(12,0) NOT NULL, 
    COI_DISCLOSURE_ID NUMBER(12,0) NOT NULL, 
    COI_DISCLOSURE_NUMBER VARCHAR2(20) NOT NULL, 
    SEQUENCE_NUMBER NUMBER(6,0) NOT NULL, 
    COI_DISC_DETAILS_NUMBER NUMBER(4,0) NOT NULL, 
    MODULE_CODE NUMBER(3,0), 
    MODULE_ITEM_KEY VARCHAR2(20), 
    ENTITY_NUMBER VARCHAR2(10), 
    ENTITY_SEQUENCE_NUMBER NUMBER(6,0), 
    ENTITY_STATUS_CODE VARCHAR2(3) NOT NULL, 
    DESCRIPTION VARCHAR2(2000) NOT NULL, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2(60) NOT NULL, 
    COMMENTS VARCHAR2(200), 
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2(36) NOT NULL)
/
ALTER TABLE COI_DISC_DETAILS 
ADD CONSTRAINT COI_DISC_DETAILS_PK 
PRIMARY KEY (COI_DISC_DETAILS_ID)
/

