DELIMITER /

INSERT INTO COI_REVIEW_STATUS ( REVIEW_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( 1, 'In Progress', NOW(), 'admin', UUID(), 1 ) 
/ 
INSERT INTO COI_REVIEW_STATUS ( REVIEW_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( 2, 'Submitted For Review', NOW(), 'admin', UUID(), 1 ) 
/ 
INSERT INTO COI_REVIEW_STATUS ( REVIEW_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( 3, 'Review Complete', NOW(), 'admin', UUID(), 1 ) 
/ 
INSERT INTO COI_REVIEW_STATUS ( REVIEW_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( 4, 'Other Review in Progress', NOW(), 'admin', UUID(), 1 ) 
/ 
INSERT INTO COI_REVIEW_STATUS ( REVIEW_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( 5, 'Under COI Committee Review', NOW(), 'admin', UUID(), 1 ) 
/ 
INSERT INTO COI_REVIEW_STATUS ( REVIEW_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( 6, 'Awaiting Additional Information', NOW(), 'admin', UUID(), 1 ) 
/ 
INSERT INTO COI_REVIEW_STATUS ( REVIEW_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( 7, 'Under Review by COI Reviewer', NOW(), 'admin', UUID(), 1 ) 
/ 

DELIMITER ;
