TRUNCATE TABLE EPS_PROP_PERSON_ROLE DROP STORAGE
/
INSERT INTO EPS_PROP_PERSON_ROLE (PROP_PERSON_ROLE_ID,DESCRIPTION,UNIT_DETAILS_REQUIRED,CERTIFICATION_REQUIRED,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('COI','Co-Investigator','Y','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO EPS_PROP_PERSON_ROLE (PROP_PERSON_ROLE_ID,DESCRIPTION,UNIT_DETAILS_REQUIRED,CERTIFICATION_REQUIRED,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('KP','Key Person','O','O','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO EPS_PROP_PERSON_ROLE (PROP_PERSON_ROLE_ID,DESCRIPTION,UNIT_DETAILS_REQUIRED,CERTIFICATION_REQUIRED,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('PI','Principal Investigator','Y','Y','admin',SYSDATE,SYS_GUID(),1)
/
