TRUNCATE TABLE PROTOCOL_PERSON_ROLE_MAPPING DROP STORAGE
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (SEQ_PROTOCOL_ID.NEXTVAL,'PI','COI','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (SEQ_PROTOCOL_ID.NEXTVAL,'COI','PI','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (SEQ_PROTOCOL_ID.NEXTVAL,'SP','CA','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (SEQ_PROTOCOL_ID.NEXTVAL,'SP','CRC','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (SEQ_PROTOCOL_ID.NEXTVAL,'CA','SP','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (SEQ_PROTOCOL_ID.NEXTVAL,'CA','CRC','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (SEQ_PROTOCOL_ID.NEXTVAL,'CRC','SP','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_PERSON_ROLE_MAPPING (ROLE_MAPPING_ID,SOURCE_ROLE_ID,TARGET_ROLE_ID,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (SEQ_PROTOCOL_ID.NEXTVAL,'CRC','CA','admin',SYSDATE,SYS_GUID(),1)
/
