TRUNCATE TABLE CORRESPONDENT_TYPE DROP STORAGE
/
INSERT INTO CORRESPONDENT_TYPE (CORRESPONDENT_TYPE_CODE,DESCRIPTION,QUALIFIER,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','Administrator','P','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO CORRESPONDENT_TYPE (CORRESPONDENT_TYPE_CODE,DESCRIPTION,QUALIFIER,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','CRC','P','admin',SYSDATE,SYS_GUID(),1)
/
