TRUNCATE TABLE PERSON_EDITABLE_FIELDS DROP STORAGE
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('addressLine1','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('addressLine2','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('addressLine3','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('city','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('countryCode','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('county','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('directoryTitle','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('emailAddress','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('eraCommonsUserName','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('facultyFlag','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('faxNumber','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('fullName','N','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('homeUnit','N','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('mobilePhoneNumber','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('officeLocation','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('officePhone','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('otherSignificantContributorFlag','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('pagerNumber','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('percentageEffort','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('postalCode','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('primaryTitle','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('projectRole','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('school','N','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('secondaryOfficeLocation','N','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('state','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('userName','N','admin',SYSDATE,SYS_GUID(),1)
/
