TRUNCATE TABLE SPONSOR_TERM_TYPE DROP STORAGE
/
INSERT INTO SPONSOR_TERM_TYPE (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','Equipment Approval Terms','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO SPONSOR_TERM_TYPE (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','Invention Terms','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO SPONSOR_TERM_TYPE (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('3','Prior Approval Terms','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO SPONSOR_TERM_TYPE (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('4','Property Terms','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO SPONSOR_TERM_TYPE (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('5','Publication Terms','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO SPONSOR_TERM_TYPE (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('6','Referenced Document Terms','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO SPONSOR_TERM_TYPE (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('7','Rights In Data Terms','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO SPONSOR_TERM_TYPE (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('8','Subaward Approval Terms','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO SPONSOR_TERM_TYPE (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('9','Travel Restrictions Terms','admin',SYSDATE,SYS_GUID(),1)
/
