TRUNCATE TABLE EPS_PROPOSAL_STATUS DROP STORAGE
/
INSERT INTO EPS_PROPOSAL_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP) 
    VALUES (1,'In Progress','admin',SYSDATE)
/
INSERT INTO EPS_PROPOSAL_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP) 
    VALUES (2,'Approval In Progress','admin',SYSDATE)
/
INSERT INTO EPS_PROPOSAL_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP) 
    VALUES (3,'Rejected','admin',SYSDATE)
/
INSERT INTO EPS_PROPOSAL_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP) 
    VALUES (4,'Approved','admin',SYSDATE)
/
INSERT INTO EPS_PROPOSAL_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP) 
    VALUES (5,'Submitted','admin',SYSDATE)
/
INSERT INTO EPS_PROPOSAL_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP) 
    VALUES (6,'Post-Submission Approval','admin',SYSDATE)
/
INSERT INTO EPS_PROPOSAL_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP) 
    VALUES (7,'Post-Submission Rejection','admin',SYSDATE)
/
