TRUNCATE TABLE PROTOCOL_REVIEW_TYPE DROP STORAGE
/
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','Full','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','Expedited','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('3','Exempt','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('4','Limited/Single Use','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('5','IRB Review not required','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('6','Response','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PROTOCOL_REVIEW_TYPE (PROTOCOL_REVIEW_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('7','FYI','admin',SYSDATE,SYS_GUID(),1)
/
