TRUNCATE TABLE TBN DROP STORAGE
/
INSERT INTO TBN (TBN_ID,PERSON_NAME,JOB_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
  VALUES ('1','TBA Research','AA000','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO TBN (TBN_ID,PERSON_NAME,JOB_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
  VALUES ('2','Research Associate','AA000','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO TBN (TBN_ID,PERSON_NAME,JOB_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
  VALUES ('3','Data Entry Assistant','AA000','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO TBN (TBN_ID,PERSON_NAME,JOB_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
  VALUES ('4','Computer Programmer','AA000','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO TBN (TBN_ID,PERSON_NAME,JOB_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
  VALUES ('5','Data Manager','AA000','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO TBN (TBN_ID,PERSON_NAME,JOB_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
  VALUES ('6','Project Director','AA000','admin',SYSDATE,SYS_GUID(),1)
/
