TRUNCATE TABLE VALID_PROTO_SUB_REV_TYPE DROP STORAGE
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','100',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',1,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','100',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',2,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','100',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',3,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','100',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',4,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','100',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',5,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','100',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',6,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','100',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',7,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','101',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',8,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','101',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',9,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','101',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',10,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','101',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',11,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','101',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',12,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','101',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',13,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','101',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',14,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','102',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',15,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','102',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',16,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','102',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',17,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','102',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',18,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','102',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',19,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','102',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',20,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','102',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',21,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','103',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',22,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','103',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',23,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','103',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',24,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','103',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',25,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','103',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',26,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','103',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',27,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','103',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',28,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','104',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',29,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','104',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',30,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','104',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',31,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','104',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',32,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','104',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',33,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','104',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',34,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','104',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',35,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','105',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',36,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','105',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',37,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','105',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',38,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','105',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',39,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','105',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',40,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','105',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',41,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','105',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',42,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','106',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',43,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','106',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',44,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','106',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',45,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','106',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',46,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','106',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',47,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','106',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',48,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','106',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',49,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','107',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',50,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','107',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',51,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','107',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',52,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','107',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',53,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','107',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',54,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','107',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',55,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','107',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',56,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','108',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',57,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','108',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',58,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','108',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',59,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','108',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',60,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','108',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',61,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','108',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',62,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','108',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',63,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','109',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',64,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','109',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',65,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','109',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',66,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','109',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',67,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','109',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',68,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','109',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',69,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','109',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',70,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','110',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',71,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','110',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',72,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','110',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',73,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','110',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',74,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','110',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',75,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','110',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',76,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','110',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',77,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('1','111',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',78,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('2','111',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',79,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('3','111',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',80,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('4','111',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',81,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('5','111',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',82,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('6','111',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',83,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','111',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',84,1)
/
INSERT INTO VALID_PROTO_SUB_REV_TYPE (PROTOCOL_REVIEW_TYPE_CODE,SUBMISSION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VALID_PROTO_SUB_REV_TYPE_ID,VER_NBR)
  VALUES ('7','112',TO_DATE( '20110221133454', 'YYYYMMDDHH24MISS' ),'KRADEV',85,1)
/
