CREATE TABLE IACUC_PROTO_REVIEW_TYPE (
    PROTOCOL_REVIEW_TYPE_CODE NUMBER(3,0) NOT NULL,
    DESCRIPTION VARCHAR2(200) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    UPDATE_USER VARCHAR2(60) NOT NULL,
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL,
    OBJ_ID VARCHAR2(36) NOT NULL,
    GLOBAL_FLAG CHAR(1) DEFAULT 'Y')
/
ALTER TABLE IACUC_PROTO_REVIEW_TYPE
ADD CONSTRAINT PK_IACUC_PROTOCOL_REVIEW_TYPE
PRIMARY KEY (PROTOCOL_REVIEW_TYPE_CODE)
/
