CREATE TABLE VALID_IACUC_PROTO_SUB_REV_TYPE 
   (	"VALID_PROTO_SUB_REV_TYPE_ID" NUMBER(12,0), 
	"SUBMISSION_TYPE_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"PROTOCOL_REVIEW_TYPE_CODE" NUMBER(3,0) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"VER_NBR" NUMBER(8,0) DEFAULT 1 NOT NULL ENABLE, 
	"OBJ_ID" VARCHAR2(36 BYTE) NOT NULL ENABLE)
/
ALTER TABLE VALID_IACUC_PROTO_SUB_REV_TYPE 
ADD CONSTRAINT PK_VALID_AC_PROTO_SUB_REV_TYPE 
PRIMARY KEY (VALID_PROTO_SUB_REV_TYPE_ID)
/
