CREATE TABLE IACUC_PROTOCOL_EXCEPTIONS ( 
    IACUC_PROTOCOL_EXCEPTIONS_ID NUMBER(12,0) NOT NULL, 
    SPECIES_CODE NUMBER(4,0) NOT NULL, 
    PROTOCOL_ID NUMBER(12,0) NOT NULL,
    PROTOCOL_NUMBER VARCHAR2(20) NOT NULL, 
    SEQUENCE_NUMBER NUMBER(3,0) NOT NULL, 
    EXCEPTION_ID NUMBER(3,0) NOT NULL, 
    EXCEPTION_CATEGORY_CODE NUMBER(3,0) NOT NULL, 
    EXCEPTION_DESCRIPTION VARCHAR2(1000) NOT NULL, 
    EXCEPTION_COUNT NUMBER(8,0), 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2(60) NOT NULL, 
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2(36) NOT NULL) 
/


ALTER TABLE IACUC_PROTOCOL_EXCEPTIONS 
ADD CONSTRAINT PK_IACUC_PROTOCOL_EXCEPTIONS 
PRIMARY KEY (IACUC_PROTOCOL_EXCEPTIONS_ID) 
/

