alter TABLE COI_DISC_DETAILS add (COPIED_COI_DISC_DETAILS_ID NUMBER(12,0), ORIGINAL_COI_DISCLOSURE_ID  NUMBER(12,0))
/
alter TABLE COI_DISC_DETAILS add COI_DISCL_PROJECT_ID NUMBER(12,0) NOT NULL
/
alter TABLE COI_DISC_DETAILS modify COI_DISCLOSURE_ID NUMBER(12,0) NULL
/
