DELIMITER /

ALTER TABLE VALID_IACUC_PROTO_ACT_CORESP 
ADD CONSTRAINT FK_VALID_IACUC_PROT_ACT_CORS_1 
FOREIGN KEY (PROTO_CORRESP_TYPE_CODE) 
REFERENCES IACUC_PROTOCOL_CORRESP_TYPE (PROTO_CORRESP_TYPE_CODE)
/


ALTER TABLE VALID_IACUC_PROTO_ACT_CORESP 
ADD CONSTRAINT FK_VALID_IACUC_PROT_ACT_CORS_2 
FOREIGN KEY (PROTOCOL_ACTION_TYPE_CODE) 
REFERENCES IACUC_PROTOCOL_ACTION_TYPE (PROTOCOL_ACTION_TYPE_CODE)
/

DELIMITER ;
