INSERT INTO PERSON_TRAINING (PERSON_TRAINING_ID,PERSON_ID,TRAINING_NUMBER,TRAINING_CODE,SCORE,DATE_REQUESTED,DATE_SUBMITTED,DATE_ACKNOWLEDGED,FOLLOWUP_DATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (1,'10000000001',1,(SELECT TRAINING_CODE FROM TRAINING WHERE DESCRIPTION = 'Johns Hopkins - Human Subjects'),'100',TO_DATE('20080101','YYYYMMDD'),TO_DATE('20080102','YYYYMMDD'),TO_DATE('20080103','YYYYMMDD'),TO_DATE('20090104','YYYYMMDD'),'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_TRAINING (PERSON_TRAINING_ID,PERSON_ID,TRAINING_NUMBER,TRAINING_CODE,SCORE,DATE_REQUESTED,DATE_SUBMITTED,DATE_ACKNOWLEDGED,FOLLOWUP_DATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (2,'10000000002',1,(SELECT TRAINING_CODE FROM TRAINING WHERE DESCRIPTION = 'MIT Human Subjects Training via Traincasters'),'100',TO_DATE('20080101','YYYYMMDD'),TO_DATE('20080201','YYYYMMDD'),TO_DATE('20080201','YYYYMMDD'),TO_DATE('20100101','YYYYMMDD'),'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_TRAINING (PERSON_TRAINING_ID,PERSON_ID,TRAINING_NUMBER,TRAINING_CODE,SCORE,DATE_REQUESTED,DATE_SUBMITTED,DATE_ACKNOWLEDGED,FOLLOWUP_DATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (3,'10000000001',2,(SELECT TRAINING_CODE FROM TRAINING WHERE DESCRIPTION = 'Beth Israel Deaconess Medical Center - Human Subjects'),'95',TO_DATE('20080101','YYYYMMDD'),TO_DATE('20080201','YYYYMMDD'),TO_DATE('20080201','YYYYMMDD'),TO_DATE('20100101','YYYYMMDD'),'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_TRAINING (PERSON_TRAINING_ID,PERSON_ID,TRAINING_NUMBER,TRAINING_CODE,SCORE,DATE_REQUESTED,DATE_SUBMITTED,DATE_ACKNOWLEDGED,FOLLOWUP_DATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (4,'10000000002',2,(SELECT TRAINING_CODE FROM TRAINING WHERE DESCRIPTION = 'MIT Human Subjects Training via Traincasters'),null,TO_DATE('20080101','YYYYMMDD'),TO_DATE('20080201','YYYYMMDD'),TO_DATE('20080201','YYYYMMDD'),TO_DATE('20100101','YYYYMMDD'),'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_TRAINING (PERSON_TRAINING_ID,PERSON_ID,TRAINING_NUMBER,TRAINING_CODE,SCORE,DATE_REQUESTED,DATE_SUBMITTED,DATE_ACKNOWLEDGED,FOLLOWUP_DATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (5,'10000000001',3,(SELECT TRAINING_CODE FROM TRAINING WHERE DESCRIPTION = 'NIH Training - Human Subjects'),null,TO_DATE('20080101','YYYYMMDD'),TO_DATE('20080201','YYYYMMDD'),TO_DATE('20080201','YYYYMMDD'),TO_DATE('20100101','YYYYMMDD'),'Y','admin',SYSDATE,SYS_GUID(),1)
/
