DELIMITER /
INSERT INTO KRIM_EXT_ID_TYP_T (EXT_ID_TYP_CD,NM,DISPLAY_SORT_CD,ENCR_REQ_IND,ACTV_IND,OBJ_ID,VER_NBR)
    VALUES ('ERAC','Electronic Research Admin Commons User','08','N','Y',UUID(),1)
/
DELIMITER ;
