set sqlblanklines on
set define off
SPOOL EMBEDDEDSERVER_ORACLE.log
PROMPT schema.sql
@RICE/EMBEDDEDSERVER_ORACLE/sql/schema.sql
PROMPT KREN_CHNL_PRODCR_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREN_CHNL_PRODCR_T.sql
PROMPT KREN_CHNL_SUBSCRP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREN_CHNL_SUBSCRP_T.sql
PROMPT KREN_CHNL_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREN_CHNL_T.sql
PROMPT KREN_CNTNT_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREN_CNTNT_TYP_T.sql
PROMPT KREN_PRIO_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREN_PRIO_T.sql
PROMPT KREN_PRODCR_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREN_PRODCR_T.sql
PROMPT KREN_RECIP_DELIV_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREN_RECIP_DELIV_T.sql
PROMPT KREN_RECIP_LIST_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREN_RECIP_LIST_T.sql
PROMPT KREN_RVWER_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREN_RVWER_T.sql
PROMPT KREW_DOC_TYP_ATTR_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_DOC_TYP_ATTR_T.sql
PROMPT KREW_DOC_TYP_PLCY_RELN_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_DOC_TYP_PLCY_RELN_T.sql
PROMPT KREW_DOC_TYP_PROC_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_DOC_TYP_PROC_T.sql
PROMPT KREW_DOC_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_DOC_TYP_T.sql
PROMPT KREW_EDL_ASSCTN_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_EDL_ASSCTN_T.sql
PROMPT KREW_EDL_DEF_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_EDL_DEF_T.sql
PROMPT KREW_RTE_NODE_CFG_PARM_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_RTE_NODE_CFG_PARM_T.sql
PROMPT KREW_RTE_NODE_LNK_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_RTE_NODE_LNK_T.sql
PROMPT KREW_RTE_NODE_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_RTE_NODE_T.sql
PROMPT KREW_RULE_ATTR_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_RULE_ATTR_T.sql
PROMPT KREW_RULE_EXPR_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_RULE_EXPR_T.sql
PROMPT KREW_RULE_EXT_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_RULE_EXT_T.sql
PROMPT KREW_RULE_EXT_VAL_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_RULE_EXT_VAL_T.sql
PROMPT KREW_RULE_RSP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_RULE_RSP_T.sql
PROMPT KREW_RULE_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_RULE_T.sql
PROMPT KREW_RULE_TMPL_ATTR_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_RULE_TMPL_ATTR_T.sql
PROMPT KREW_RULE_TMPL_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_RULE_TMPL_T.sql
PROMPT KREW_STYLE_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_STYLE_T.sql
PROMPT KREW_USR_OPTN_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KREW_USR_OPTN_T.sql
PROMPT KRIM_ADDR_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ADDR_TYP_T.sql
PROMPT KRIM_AFLTN_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_AFLTN_TYP_T.sql
PROMPT KRIM_ATTR_DEFN_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ATTR_DEFN_T.sql
PROMPT KRIM_EMAIL_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_EMAIL_TYP_T.sql
PROMPT KRIM_EMP_STAT_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_EMP_STAT_T.sql
PROMPT KRIM_EMP_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_EMP_TYP_T.sql
PROMPT KRIM_ENTITY_CACHE_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ENTITY_CACHE_T.sql
PROMPT KRIM_ENTITY_EMAIL_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ENTITY_EMAIL_T.sql
PROMPT KRIM_ENTITY_ENT_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ENTITY_ENT_TYP_T.sql
PROMPT KRIM_ENTITY_NM_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ENTITY_NM_T.sql
PROMPT KRIM_ENTITY_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ENTITY_T.sql
PROMPT KRIM_ENT_NM_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ENT_NM_TYP_T.sql
PROMPT KRIM_ENT_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ENT_TYP_T.sql
PROMPT KRIM_EXT_ID_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_EXT_ID_TYP_T.sql
PROMPT KRIM_GRP_MBR_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_GRP_MBR_T.sql
PROMPT KRIM_GRP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_GRP_T.sql
PROMPT KRIM_PERM_ATTR_DATA_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_PERM_ATTR_DATA_T.sql
PROMPT KRIM_PERM_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_PERM_T.sql
PROMPT KRIM_PERM_TMPL_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_PERM_TMPL_T.sql
PROMPT KRIM_PHONE_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_PHONE_TYP_T.sql
PROMPT KRIM_PRNCPL_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_PRNCPL_T.sql
PROMPT KRIM_ROLE_MBR_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ROLE_MBR_T.sql
PROMPT KRIM_ROLE_PERM_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ROLE_PERM_T.sql
PROMPT KRIM_ROLE_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_ROLE_T.sql
PROMPT KRIM_RSP_TMPL_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_RSP_TMPL_T.sql
PROMPT KRIM_TYP_ATTR_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_TYP_ATTR_T.sql
PROMPT KRIM_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRIM_TYP_T.sql
PROMPT KRNS_CAMPUS_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRNS_CAMPUS_T.sql
PROMPT KRNS_CMP_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRNS_CMP_TYP_T.sql
PROMPT KRNS_NMSPC_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRNS_NMSPC_T.sql
PROMPT KRNS_NTE_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRNS_NTE_TYP_T.sql
PROMPT KRNS_PARM_DTL_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRNS_PARM_DTL_TYP_T.sql
PROMPT KRNS_PARM_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRNS_PARM_T.sql
PROMPT KRNS_PARM_TYP_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRNS_PARM_TYP_T.sql
PROMPT KRSB_MSG_PYLD_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRSB_MSG_PYLD_T.sql
PROMPT KRSB_MSG_QUE_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRSB_MSG_QUE_T.sql
PROMPT KRSB_QRTZ_LOCKS.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KRSB_QRTZ_LOCKS.sql
PROMPT KR_COUNTRY_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KR_COUNTRY_T.sql
PROMPT KR_STATE_T.sql
@RICE/EMBEDDEDSERVER_ORACLE/datasql/KR_STATE_T.sql
PROMPT schema-constraints.sql
@RICE/EMBEDDEDSERVER_ORACLE/sql/schema-constraints.sql
@RICE/EMBEDDEDSERVER_ORACLE/demo-server-dataset-cleanup.sql
@RICE/EMBEDDEDSERVER_ORACLE/bootstrap-server-dataset-cleanup.sql
quit
