-- Committee Schedule Action Items Demo Data
INSERT INTO COMM_SCHEDULE_ACT_ITEMS (COMM_SCHEDULE_ACT_ITEMS_ID,SCHEDULE_ID_FK,ACTION_ITEM_NUMBER,SCHEDULE_ACT_ITEM_TYPE_CODE,ITEM_DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
VALUES (SEQ_MEETING_ID.NEXTVAL,(SELECT ID FROM COMM_SCHEDULE WHERE SCHEDULED_DATE = '19-JUL-10'),1,'1','Other business item',TO_TIMESTAMP('06-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'quickstart',0,SYS_GUID());

INSERT INTO COMM_SCHEDULE_ACT_ITEMS (COMM_SCHEDULE_ACT_ITEMS_ID,SCHEDULE_ID_FK,ACTION_ITEM_NUMBER,SCHEDULE_ACT_ITEM_TYPE_CODE,ITEM_DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
VALUES (SEQ_MEETING_ID.NEXTVAL,(SELECT ID FROM COMM_SCHEDULE WHERE SCHEDULED_DATE = '19-JUL-10'),2,'2','New membership consideration item',TO_TIMESTAMP('06-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'quickstart',0,SYS_GUID());

INSERT INTO COMM_SCHEDULE_ACT_ITEMS (COMM_SCHEDULE_ACT_ITEMS_ID,SCHEDULE_ID_FK,ACTION_ITEM_NUMBER,SCHEDULE_ACT_ITEM_TYPE_CODE,ITEM_DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
VALUES (SEQ_MEETING_ID.NEXTVAL,(SELECT ID FROM COMM_SCHEDULE WHERE SCHEDULED_DATE = '19-JUL-10'),3,'3','non-compliance item',TO_TIMESTAMP('06-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'quickstart',0,SYS_GUID());

INSERT INTO COMM_SCHEDULE_ACT_ITEMS (COMM_SCHEDULE_ACT_ITEMS_ID,SCHEDULE_ID_FK,ACTION_ITEM_NUMBER,SCHEDULE_ACT_ITEM_TYPE_CODE,ITEM_DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
VALUES (SEQ_MEETING_ID.NEXTVAL,(SELECT ID FROM COMM_SCHEDULE WHERE SCHEDULED_DATE = '19-JUL-10'),4,'4','Protocol deviation item',TO_TIMESTAMP('06-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'quickstart',0,SYS_GUID());

INSERT INTO COMM_SCHEDULE_ACT_ITEMS (COMM_SCHEDULE_ACT_ITEMS_ID,SCHEDULE_ID_FK,ACTION_ITEM_NUMBER,SCHEDULE_ACT_ITEM_TYPE_CODE,ITEM_DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
VALUES (SEQ_MEETING_ID.NEXTVAL,(SELECT ID FROM COMM_SCHEDULE WHERE SCHEDULED_DATE = '19-JUL-10'),5,'5','Adverse event item',TO_TIMESTAMP('06-JUL-10','DD-MON-RR HH.MI.SSXFF AM'),'quickstart',0,SYS_GUID());
