INSERT INTO DOCUMENT_NEXTVALUE (DOCUMENT_NUMBER,NEXT_VALUE,OBJ_ID,PROPERTY_NAME,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (4073,2,SYS_GUID(),'actionId',TO_DATE( '20100923222743', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO DOCUMENT_NEXTVALUE (DOCUMENT_NUMBER,NEXT_VALUE,OBJ_ID,PROPERTY_NAME,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (4074,2,SYS_GUID(),'actionId',TO_DATE( '20100923223606', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO DOCUMENT_NEXTVALUE (DOCUMENT_NUMBER,NEXT_VALUE,OBJ_ID,PROPERTY_NAME,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (4074,2,SYS_GUID(),'submissionNumber',TO_DATE( '20100923223606', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO DOCUMENT_NEXTVALUE (DOCUMENT_NUMBER,NEXT_VALUE,OBJ_ID,PROPERTY_NAME,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (4076,5,SYS_GUID(),'actionId',TO_DATE( '20100923230201', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO DOCUMENT_NEXTVALUE (DOCUMENT_NUMBER,NEXT_VALUE,OBJ_ID,PROPERTY_NAME,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (4076,2,SYS_GUID(),'submissionNumber',TO_DATE( '20100923230201', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO DOCUMENT_NEXTVALUE (DOCUMENT_NUMBER,NEXT_VALUE,OBJ_ID,PROPERTY_NAME,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (4078,5,SYS_GUID(),'actionId',TO_DATE( '20100923230206', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO DOCUMENT_NEXTVALUE (DOCUMENT_NUMBER,NEXT_VALUE,OBJ_ID,PROPERTY_NAME,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (4078,2,SYS_GUID(),'submissionNumber',TO_DATE( '20100923230206', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO DOCUMENT_NEXTVALUE (DOCUMENT_NUMBER,NEXT_VALUE,OBJ_ID,PROPERTY_NAME,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (4079,5,SYS_GUID(),'actionId',TO_DATE( '20100923230838', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO DOCUMENT_NEXTVALUE (DOCUMENT_NUMBER,NEXT_VALUE,OBJ_ID,PROPERTY_NAME,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (4079,2,SYS_GUID(),'submissionNumber',TO_DATE( '20100923230838', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO DOCUMENT_NEXTVALUE (DOCUMENT_NUMBER,NEXT_VALUE,OBJ_ID,PROPERTY_NAME,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (4081,5,SYS_GUID(),'actionId',TO_DATE( '20100923230843', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO DOCUMENT_NEXTVALUE (DOCUMENT_NUMBER,NEXT_VALUE,OBJ_ID,PROPERTY_NAME,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (4081,2,SYS_GUID(),'submissionNumber',TO_DATE( '20100923230843', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
