INSERT INTO PROTOCOL_LOCATION (OBJ_ID,ORGANIZATION_ID,PROTOCOL_ID,PROTOCOL_LOCATION_ID,PROTOCOL_NUMBER,PROTOCOL_ORG_TYPE_CODE,ROLODEX_ID,SEQUENCE_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'000001',(SELECT PROTOCOL_ID FROM PROTOCOL WHERE PROTOCOL_NUMBER = '1009000013'),SEQ_PROTOCOL_ID.NEXTVAL,'0','1',1,0,TO_DATE( '20100923222743', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO PROTOCOL_LOCATION (OBJ_ID,ORGANIZATION_ID,PROTOCOL_ID,PROTOCOL_LOCATION_ID,PROTOCOL_NUMBER,PROTOCOL_ORG_TYPE_CODE,ROLODEX_ID,SEQUENCE_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'000001',(SELECT PROTOCOL_ID FROM PROTOCOL WHERE PROTOCOL_NUMBER = '1009000019'),SEQ_PROTOCOL_ID.NEXTVAL,'0','1',1,0,TO_DATE( '20100923223606', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO PROTOCOL_LOCATION (OBJ_ID,ORGANIZATION_ID,PROTOCOL_ID,PROTOCOL_LOCATION_ID,PROTOCOL_NUMBER,PROTOCOL_ORG_TYPE_CODE,ROLODEX_ID,SEQUENCE_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'000001',(SELECT PROTOCOL_ID FROM PROTOCOL WHERE PROTOCOL_NUMBER = '1009000028' AND SEQUENCE_NUMBER = 0),SEQ_PROTOCOL_ID.NEXTVAL,'0','1',1,0,TO_DATE( '20100923230201', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO PROTOCOL_LOCATION (OBJ_ID,ORGANIZATION_ID,PROTOCOL_ID,PROTOCOL_LOCATION_ID,PROTOCOL_NUMBER,PROTOCOL_ORG_TYPE_CODE,ROLODEX_ID,SEQUENCE_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'000001',(SELECT PROTOCOL_ID FROM PROTOCOL WHERE PROTOCOL_NUMBER = '1009000028' AND SEQUENCE_NUMBER = 1),SEQ_PROTOCOL_ID.NEXTVAL,'1009000028','1',1,1,TO_DATE( '20100923230206', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO PROTOCOL_LOCATION (OBJ_ID,ORGANIZATION_ID,PROTOCOL_ID,PROTOCOL_LOCATION_ID,PROTOCOL_NUMBER,PROTOCOL_ORG_TYPE_CODE,ROLODEX_ID,SEQUENCE_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'000001',(SELECT PROTOCOL_ID FROM PROTOCOL WHERE PROTOCOL_NUMBER = '1009000049' AND SEQUENCE_NUMBER = 0),SEQ_PROTOCOL_ID.NEXTVAL,'0','1',1,0,TO_DATE( '20100923230838', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO PROTOCOL_LOCATION (OBJ_ID,ORGANIZATION_ID,PROTOCOL_ID,PROTOCOL_LOCATION_ID,PROTOCOL_NUMBER,PROTOCOL_ORG_TYPE_CODE,ROLODEX_ID,SEQUENCE_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'000001',(SELECT PROTOCOL_ID FROM PROTOCOL WHERE PROTOCOL_NUMBER = '1009000049' AND SEQUENCE_NUMBER = 1),SEQ_PROTOCOL_ID.NEXTVAL,'1009000049','1',1,1,TO_DATE( '20100923230843', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
