-- Unit Demo Data

INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'IU-UNIV','BLOOMINGTON CAMPUS','BL-BL',SYSDATE,'admin',1)
/
INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'BL-RCEN','IND INST ON DISABILITY/COMMNTY','BL-IIDC',SYSDATE,'admin',1)
/
INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'BL-RUGS','RESEARCH CENTERS','BL-RCEN',SYSDATE,'admin',1)
/
INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'BL-BL','OFFICE OF VP FOR RESEARCH','BL-RUGS',SYSDATE,'admin',1)
/
INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'IN-MDEP','CARDIOLOGY','IN-CARD',SYSDATE,'admin',1)
/
INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'IN-CARD','CARDIOLOGY RECHARGE CTR','IN-CARR',SYSDATE,'admin',1)
/
INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'IU-UNIV','IND UNIV-PURDUE UNIV INDPLS','IN-IN',SYSDATE,'admin',1)
/
INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'IN-MED','MEDICINE DEPT','IN-MDEP',SYSDATE,'admin',1)
/
INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'IN-IN','SCHOOL OF MEDICINE','IN-MED',SYSDATE,'admin',1)
/
INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'IN-MED','PEDIATRICS','IN-PED',SYSDATE,'admin',1)
/
INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'IN-PED','PED-EMERGENCY ROOM SERVICES','IN-PERS',SYSDATE,'admin',1)
/
INSERT INTO UNIT (OBJ_ID,PARENT_UNIT_NUMBER,UNIT_NAME,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES (SYS_GUID(),'000001','UNIVERSITY LEVEL','IU-UNIV',SYSDATE,'admin',1)
/
