INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'courseName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - Pending/In Prog'),SYS_GUID(),TO_DATE( '20100923222741', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'courseName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - Withdrawn'),SYS_GUID(),TO_DATE( '20100923223605', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'courseName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - SMRR' AND VER_NBR = 8),SYS_GUID(),TO_DATE( '20100923230155', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'courseName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - SMRR' AND VER_NBR = 3),SYS_GUID(),TO_DATE( '20100923230205', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'courseName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - SRR' AND VER_NBR = 8),SYS_GUID(),TO_DATE( '20100923230833', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'courseName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - SRR' AND VER_NBR = 3),SYS_GUID(),TO_DATE( '20100923230842', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'instructorName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - Pending/In Prog'),SYS_GUID(),TO_DATE( '20100923222741', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'instructorName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - Withdrawn'),SYS_GUID(),TO_DATE( '20100923223605', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'instructorName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - SMRR' AND VER_NBR = 8),SYS_GUID(),TO_DATE( '20100923230155', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'instructorName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - SMRR' AND VER_NBR = 3),SYS_GUID(),TO_DATE( '20100923230205', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'instructorName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - SRR' AND VER_NBR = 8),SYS_GUID(),TO_DATE( '20100923230833', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
INSERT INTO CUSTOM_ATTRIBUTE_DOC_VALUE (CUSTOM_ATTRIBUTE_ID,DOCUMENT_NUMBER,OBJ_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ((SELECT ID FROM CUSTOM_ATTRIBUTE WHERE NAME = 'instructorName'),(SELECT DOC_HDR_ID FROM KRNS_DOC_HDR_T WHERE FDOC_DESC = 'Staged for Admin Corr - SRR' AND VER_NBR = 3),SYS_GUID(),TO_DATE( '20100923230842', 'YYYYMMDDHH24MISS' ),'quickstart',0)
/
