-- Rate Class Demo Data

set define off

INSERT INTO RATE_CLASS (DESCRIPTION,ICR_TYPE_CODE,OBJ_ID,RATE_CLASS_CODE,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('MTDC',35,SYS_GUID(),'1','O',SYSDATE,'admin',1)
/
INSERT INTO RATE_CLASS (DESCRIPTION,OBJ_ID,RATE_CLASS_CODE,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Lab Allocation - Salaries',SYS_GUID(),'10','Y',SYSDATE,'admin',1)
/
INSERT INTO RATE_CLASS (DESCRIPTION,OBJ_ID,RATE_CLASS_CODE,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Lab Allocation - M&S',SYS_GUID(),'11','L',SYSDATE,'admin',1)
/
INSERT INTO RATE_CLASS (DESCRIPTION,OBJ_ID,RATE_CLASS_CODE,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Lab Allocation - Utilities',SYS_GUID(),'12','L',SYSDATE,'admin',1)
/
INSERT INTO RATE_CLASS (DESCRIPTION,ICR_TYPE_CODE,OBJ_ID,RATE_CLASS_CODE,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('TDC',11,SYS_GUID(),'2','O',SYSDATE,'admin',1)
/
INSERT INTO RATE_CLASS (DESCRIPTION,ICR_TYPE_CODE,OBJ_ID,RATE_CLASS_CODE,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('S&W',36,SYS_GUID(),'3','O',SYSDATE,'admin',1)
/
INSERT INTO RATE_CLASS (DESCRIPTION,ICR_TYPE_CODE,OBJ_ID,RATE_CLASS_CODE,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Fund with Transaction Fee (FUNSN)',11,SYS_GUID(),'4','O',SYSDATE,'admin',1)
/
INSERT INTO RATE_CLASS (DESCRIPTION,OBJ_ID,RATE_CLASS_CODE,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Employee Benefits',SYS_GUID(),'5','E',TO_DATE( '20010627000000', 'YYYYMMDDHH24MISS' ),'admin',1)
/
INSERT INTO RATE_CLASS (DESCRIPTION,OBJ_ID,RATE_CLASS_CODE,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Inflation',SYS_GUID(),'7','I',SYSDATE,'admin',1)
/
INSERT INTO RATE_CLASS (DESCRIPTION,OBJ_ID,RATE_CLASS_CODE,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Vacation',SYS_GUID(),'8','V',SYSDATE,'admin',1)
/
INSERT INTO RATE_CLASS (DESCRIPTION,OBJ_ID,RATE_CLASS_CODE,RATE_CLASS_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR)
  VALUES ('Other',SYS_GUID(),'9','X',SYSDATE,'admin',1)
/
