-- Questionnaire Demo Data
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR) 
  VALUES ('3091','IRB Long V1',SYS_GUID(),6)
/
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR) 
  VALUES ('3092','IRB Short V1',SYS_GUID(),6)
/
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR) 
  VALUES ('3093','IRB Long V2',SYS_GUID(),6)
/

-- Committee Demo Data
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR) 
  VALUES ('3094','IRB Committee',SYS_GUID(),9)
/

-- Protocol Demo Data
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('4073','Staged for Admin Corr - Pending/In Prog',SYS_GUID(),2)
/
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('4074','Staged for Admin Corr - Withdrawn',SYS_GUID(),5)
/
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('4075','Researcher/Protocol# 1009000019',SYS_GUID(),3)
/
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('4076','Staged for Admin Corr - SMRR',SYS_GUID(),8)
/
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('4077','Researcher/Protocol# 1009000028',SYS_GUID()',3)
/
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('4078','Staged for Admin Corr - SMRR',SYS_GUID(),3)
/
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('4079','Staged for Admin Corr - SRR',SYS_GUID(),8)
/
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('4080','Researcher/Protocol# 1009000049',SYS_GUID(),3)
/
INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,FDOC_DESC,OBJ_ID,VER_NBR)
  VALUES ('4081','Staged for Admin Corr - SRR',SYS_GUID(),3)
/
