delimiter /
TRUNCATE TABLE KREW_RTE_BRCH_ST_T
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2071,2074,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2071,2075,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2100,2103,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2100,2104,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2164,2167,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2164,2168,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2169,2175,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2220,2223,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2220,2224,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2262,2265,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2262,2266,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2267,2270,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2267,2271,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2320,2323,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2320,2324,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2448,2450,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2448,2451,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2472,2474,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2472,2475,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2479,2481,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2479,2482,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2524,2530,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2531,2533,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2531,2534,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2535,2543,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2546,2548,'true',2)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorFinal',2546,2549,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2630,2636,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2637,2643,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2644,2650,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2665,2671,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2684,2690,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2800,2806,'true',1)
/
INSERT INTO KREW_RTE_BRCH_ST_T (KEY_CD,RTE_BRCH_ID,RTE_BRCH_ST_ID,VAL,VER_NBR)
  VALUES ('System.PostProcessorProcessed',2874,2880,'true',1)
/
delimiter ;
