create table AWARD_SYNC_STATUS (
  AWARD_SYNC_STATUS_ID NUMBER(22,0),
  AWARD_ID  NUMBER(22,0),
  AWARD_NUMBER VARCHAR2(12),
  PARENT_AWARD_ID	NUMBER(22,0) NOT NULL,  
  STEP_SUCCESS CHAR(1) NOT NULL,
  STATUS VARCHAR2(4000),
  SYNC_COMPLETE CHAR(1) NOT NULL,
  UPDATE_TIMESTAMP  DATE NOT NULL,
  UPDATE_USER       VARCHAR2(60) NOT NULL,
  VER_NBR           NUMBER(8,0) NOT NULL,
  OBJ_ID            VARCHAR2(36) NOT NULL
);

ALTER TABLE AWARD_SYNC_STATUS
	ADD CONSTRAINT PK_AWARD_SYNC_STATUS
		PRIMARY KEY (AWARD_SYNC_STATUS_ID);
		