CREATE OR REPLACE VIEW OSP$AWARD_SCIENCE_CODE(MIT_AWARD_NUMBER,SEQUENCE_NUMBER,SCIENCE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) AS 
SELECT B.AWARD_NUMBER,
       B.SEQUENCE_NUMBER,
       A.SCIENCE_KEYWORD_CODE,
       A.UPDATE_TIMESTAMP,
       A.UPDATE_USER
FROM   AWARD_SCIENCE_KEYWORD A,
       AWARD B
WHERE  A.AWARD_ID = B.AWARD_ID;