CREATE OR REPLACE VIEW OSP$PROTOCOL_DOCUMENT_TYPE AS 
SELECT T.TYPE_CD,
       T.DESCRIPTION,
       T.UPDATE_TIMESTAMP,
       T.UPDATE_USER,
       G.GROUP_CD
FROM   PROTOCOL_ATTACHMENT_TYPE T,
       PROTOCOL_ATTACHMENT_GROUP G,
       PROTOCOL_ATTACHMENT_TYPE_GROUP TG
WHERE  T.TYPE_CD = TG.TYPE_CD 
       AND G.GROUP_CD = TG.GROUP_CD;