CREATE OR REPLACE VIEW OSP$TEMPLATE_REPORT_TERMS(TEMPLATE_CODE,REPORT_CLASS_CODE,REPORT_CODE,FREQUENCY_CODE,FREQUENCY_BASE_CODE,OSP_DISTRIBUTION_CODE,DUE_DATE,CONTACT_TYPE_CODE,ROLODEX_ID,NUMBER_OF_COPIES,UPDATE_TIMESTAMP,UPDATE_USER) AS 
SELECT A.AWARD_TEMPLATE_CODE,
       A.REPORT_CLASS_CODE,
       A.REPORT_CODE,
       A.FREQUENCY_CODE,
       A.FREQUENCY_BASE_CODE,
       A.OSP_DISTRIBUTION_CODE,
       A.DUE_DATE,
       B.CONTACT_TYPE_CODE,
       B.ROLODEX_ID,
       B.NUMBER_OF_COPIES,
       A.UPDATE_TIMESTAMP,
       A.UPDATE_USER
FROM   AWARD_TEMPLATE_REPORT_TERMS A,
       AWARD_TEMPL_REP_TERMS_RECNT B
WHERE  A.TEMPLATE_REPORT_TERMS_ID = B.TEMPLATE_REPORT_TERMS_ID;