DELIMITER /

INSERT INTO KRNS_PARM_T (APPL_NMSPC_CD,NMSPC_CD,PARM_DTL_TYP_CD,PARM_NM,VER_NBR,PARM_TYP_CD,TXT,PARM_DESC_TXT,CONS_CD,OBJ_ID) 
   VALUES ('KC','KC-GEN','All','SYSTEM_NOTIFICATION_PRODUCER_ID',1,'CONFG','1000','Code corresponding to System Notification Producer','A',UUID())
/
INSERT INTO KRNS_PARM_T (APPL_NMSPC_CD,NMSPC_CD,PARM_DTL_TYP_CD,PARM_NM,VER_NBR,PARM_TYP_CD,TXT,PARM_DESC_TXT,CONS_CD,OBJ_ID) 
   VALUES ('KC','KC-GEN','All','NORMAL_NOTIFICATION_PRIORITY_ID',1,'CONFG','1','Code corresponding to Normal Notification Priority','A',UUID())
/
INSERT INTO KRNS_PARM_T (APPL_NMSPC_CD,NMSPC_CD,PARM_DTL_TYP_CD,PARM_NM,VER_NBR,PARM_TYP_CD,TXT,PARM_DESC_TXT,CONS_CD,OBJ_ID) 
   VALUES ('KC','KC-GEN','All','SIMPLE_NOTIFICATION_CONTENT_TYPE_ID',1,'CONFG','1','Code corresponding to Simple Notification Type','A',UUID())
/
INSERT INTO KRNS_PARM_T (APPL_NMSPC_CD,NMSPC_CD,PARM_DTL_TYP_CD,PARM_NM,VER_NBR,PARM_TYP_CD,TXT,PARM_DESC_TXT,CONS_CD,OBJ_ID) 
   VALUES ('KC','KC-GEN','All','KC_NOTIFICATION_CHANNEL_ID',1,'CONFG','1000','Code corresponding to KC Notification Channel','A',UUID())
/

DELIMITER ;
