set define off
set sqlblanklines on
spool KR-RELEASE-3_1-Demo-ORACLE-Install.log
@ORACLE/KR_DEMO1_KREW_ACTN_ITM_T.sql
@ORACLE/KR_DEMO1_KREW_ACTN_RQST_T.sql
@ORACLE/KR_DEMO1_KREW_ACTN_TKN_T.sql
@ORACLE/KR_DEMO1_KREW_DOC_HDR_CNTNT_T.sql
@ORACLE/KR_DEMO1_KREW_DOC_HDR_T.sql
@ORACLE/KR_DEMO1_KREW_INIT_RTE_NODE_INSTN_T.sql
@ORACLE/KR_DEMO1_KREW_OUT_BOX_ITM_T.sql
@ORACLE/KR_DEMO1_KREW_RTE_BRCH_ST_T.sql
@ORACLE/KR_DEMO1_KREW_RTE_BRCH_T.sql
@ORACLE/KR_DEMO1_KREW_RTE_NODE_INSTN_LNK_T.sql
@ORACLE/KR_DEMO1_KREW_RTE_NODE_INSTN_T.sql
@ORACLE/KR_DEMO1_KRIM_ENTITY_T.sql
@ORACLE/KR_DEMO1_KRIM_PHONE_TYP_T.sql
@ORACLE/KR_DEMO2_KREN_NTFCTN_T.sql
@ORACLE/KR_DEMO2_KRIM_ENTITY_ENT_TYP_T.sql
@ORACLE/KR_DEMO2_KRIM_ENTITY_NM_T.sql
@ORACLE/KR_DEMO2_KRIM_PRNCPL_T.sql
@ORACLE/KR_DEMO2_KRNS_CAMPUS_T.sql
@ORACLE/KR_DEMO3_KREN_NTFCTN_MSG_DELIV_T.sql
@ORACLE/KR_DEMO3_KREN_RECIP_T.sql
@ORACLE/KR_DEMO3_KREN_SNDR_T.sql
@ORACLE/KR_DEMO3_KRIM_ENTITY_ADDR_T.sql
@ORACLE/KR_DEMO3_KRIM_ENTITY_EMAIL_T.sql
@ORACLE/KR_DEMO3_KRIM_ENTITY_EMP_INFO_T.sql
@ORACLE/KR_DEMO3_KRIM_ENTITY_PHONE_T.sql
@ORACLE/KR_DEMO3_KRIM_GRP_MBR_T.sql
@ORACLE/KR_DEMO3_KRIM_ROLE_MBR_T.sql
@ORACLE/KR_DEMO4_KRIM_ROLE_MBR_ATTR_DATA_T.sql
@ORACLE/KR_DEMO5_KRIM_ROLE_MBR_T.sql
@ORACLE/KR_DEMO6_KRIM_ROLE_MBR_ATTR_DATA_T.sql
@ORACLE/KR_SEQUENCE_RESET.sql
commit;
exit
