INSERT INTO FORMULATED_TYPE ( FORMULATED_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) VALUES ( '1', 'X-Ray', sysdate, 'admin', sys_guid(), 1 )
/
INSERT INTO FORMULATED_TYPE ( FORMULATED_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) VALUES ( '2', 'Overnight Stay', sysdate, 'admin', sys_guid(), 1 )
/
INSERT INTO FORMULATED_TYPE ( FORMULATED_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) VALUES ( 3, 'Computing-IS Support', sysdate, 'admin', sys_guid(), 1 ) 
/
INSERT INTO FORMULATED_TYPE ( FORMULATED_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) VALUES ( 4, 'Laboratory use- restock', sysdate, 'admin', sys_guid(), 1 )
/
