
CREATE OR REPLACE VIEW OSP$ORGANIZATION_AUDIT   ( 
ORGANIZATION_ID, FISCAL_YEAR, AUDIT_ACCEPTED, AUDIT_COMMENT, UPDATE_TIMESTAMP, UPDATE_USER 
)
AS select ORGANIZATION_ID, FISCAL_YEAR, AUDIT_ACCEPTED, AUDIT_COMMENT, UPDATE_TIMESTAMP, UPDATE_USER
	from ORGANIZATION_AUDIT;
