create or replace view OSP$VALID_SP_REV_APPROVAL as 
	select SPECIAL_REVIEW_CODE,APPROVAL_TYPE_CODE,PROTOCOL_NUMBER_FLAG,APPROVAL_DATE_FLAG,APPLICATION_DATE_FLAG,UPDATE_TIMESTAMP,
	UPDATE_USER
	from VALID_SP_REV_APPROVAL;