delimiter /
TRUNCATE TABLE LOCATION_TYPE
/
INSERT INTO LOCATION_TYPE (LOCATION_TYPE_CODE,LOCATION_TYPE_DESC,UPDATE_TIMESTAMP,UPDATE_USER)
  VALUES (1,'Proposal Organization',STR_TO_DATE( '20100111000000', '%Y%m%d%H%i%s' ),'KRADEV')
/
INSERT INTO LOCATION_TYPE (LOCATION_TYPE_CODE,LOCATION_TYPE_DESC,UPDATE_TIMESTAMP,UPDATE_USER)
  VALUES (2,'Performing Organization',STR_TO_DATE( '20100111000000', '%Y%m%d%H%i%s' ),'KRADEV')
/
INSERT INTO LOCATION_TYPE (LOCATION_TYPE_CODE,LOCATION_TYPE_DESC,UPDATE_TIMESTAMP,UPDATE_USER)
  VALUES (3,'Other Organization',STR_TO_DATE( '20100111000000', '%Y%m%d%H%i%s' ),'KRADEV')
/
INSERT INTO LOCATION_TYPE (LOCATION_TYPE_CODE,LOCATION_TYPE_DESC,UPDATE_TIMESTAMP,UPDATE_USER)
  VALUES (4,'Performance Site',STR_TO_DATE( '20100111000000', '%Y%m%d%H%i%s' ),'KRADEV')
/
delimiter ;
