CREATE TABLE VALID_NARR_FORMS (
  	VALID_NARR_FORMS_ID DECIMAL(12,0) NOT NULL,
  	FORM_NAME VARCHAR(100) NOT NULL, 
	NARRATIVE_TYPE_CODE VARCHAR(3) NOT NULL, 
	MANDATORY VARCHAR(3), 
	UPDATE_TIMESTAMP DATE NOT NULL, 
	UPDATE_USER VARCHAR(60) NOT NULL
);
ALTER TABLE VALID_NARR_FORMS 
	ADD CONSTRAINT PK_VALID_NARR_FORMS 
	PRIMARY KEY (VALID_NARR_FORMS_ID);
	
