CREATE TABLE IACUC_PROTO_STUDY_CUSTOM_DATA ( 
    IACUC_PROT_STUD_CUST_DATA_ID NUMBER(12,0) NOT NULL, 
    PROTOCOL_ID NUMBER(12,0) NOT NULL, 
    PROTOCOL_NUMBER VARCHAR2(20) NOT NULL, 
    SEQUENCE_NUMBER NUMBER(4,0) NOT NULL, 
    STUDY_GROUP_ID NUMBER(6,0) NOT NULL, 
    PROC_CUSTOM_ATTRIBUTE_ID NUMBER(12,0) NOT NULL,
    VALUE VARCHAR2(2000), 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2(60) NOT NULL, 
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2(36) NOT NULL) 
/


ALTER TABLE IACUC_PROTO_STUDY_CUSTOM_DATA 
ADD CONSTRAINT PK_IACUC_PROTO_STUDY_CUSTOM_DA 
PRIMARY KEY (IACUC_PROT_STUD_CUST_DATA_ID) 
/

