CREATE TABLE IACUC_PROTO_CORRESPONDENCE (
    ID 						NUMBER(12),
    PROTOCOL_NUMBER 		VARCHAR2(20) NOT NULL,
    SEQUENCE_NUMBER		 	NUMBER(4) NOT NULL,
    ACTION_ID 				NUMBER(6) NOT NULL,
    PROTOCOL_ID 			NUMBER(12) NOT NULL,
    ACTION_ID_FK 			NUMBER(12) NOT NULL,
    PROTO_CORRESP_TYPE_CODE VARCHAR2(3) NOT NULL,
    FINAL_FLAG 				CHAR(1) NOT NULL,
    UPDATE_TIMESTAMP 		DATE,
    UPDATE_USER 			VARCHAR2(60),
    VER_NBR 				NUMBER(8) default 1 NOT NULL,
    CORRESPONDENCE 			BLOB NOT NULL,
    OBJ_ID 					VARCHAR2(36) NOT NULL,
    CREATE_TIMESTAMP 		DATE,
    CREATE_USER 			VARCHAR2(60),
    FINAL_FLAG_TIMESTAMP 	DATE )
/
ALTER TABLE IACUC_PROTO_CORRESPONDENCE
ADD CONSTRAINT IACUC_PROTO_CORRESPONDENCEP1
PRIMARY KEY (ID)
/
