INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'ageByFiscalYear','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'race','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'handicappedFlag','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'handicapType','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'veteranFlag','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'veteranType','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'hasVisa','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'visaCode','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'visaType','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'visaRenewalDate','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'directoryDepartment','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'vacationAccrualFlag','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'onSabbaticalFlag','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'idProvided','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'idVerified','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'countryOfCitizenship','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'citizenshipTypeCode','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'educationLevel','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'yearGraduated','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'major','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'degree','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO PERSON_EDITABLE_FIELDS (PERSON_EDITABLE_FIELD_ID,MODULE_CODE,FIELD_NAME,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR)
    VALUES (SEQ_PERSON_EDITABLE_FIELD.NEXTVAL,(SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION = 'Development Proposal'),'school','Y','admin',SYSDATE,SYS_GUID(),1)
/
