-- Rice Fixes
drop sequence krew_actn_rqst_s;
CREATE SEQUENCE "KRRELEASE"."KREW_ACTN_RQST_S" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2573 NOCACHE ORDER NOCYCLE ;

drop sequence krew_actn_tkn_s;
CREATE SEQUENCE "KRRELEASE"."KREW_ACTN_TKN_S" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2356 NOCACHE ORDER NOCYCLE ;

-- irbadmin
INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000112','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-PROTOCOL' AND role_nm = 'Protocol Aggregator'),KRIM_ROLE_MBR_ID_S.nextval,1);

INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000112','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-PROTOCOL' AND role_nm = 'ProtocolApprover'),KRIM_ROLE_MBR_ID_S.nextval,1);

INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000112','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'IRB Administrator'),KRIM_ROLE_MBR_ID_S.nextval,1);

INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000112','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-WKFLW' AND role_nm = 'IRBApprover'),KRIM_ROLE_MBR_ID_S.nextval,1);


INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'000001',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'unitNumber'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000112' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'IRB Administrator')),1);

INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'Y',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'subunits'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000112' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'IRB Administrator')),1);


-- irbresearcher 
INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000116','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-PROTOCOL' AND role_nm = 'Protocol Aggregator'),KRIM_ROLE_MBR_ID_S.nextval,1);

INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000116','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-PROTOCOL' AND role_nm = 'ProtocolApprover'),KRIM_ROLE_MBR_ID_S.nextval,1);

INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000116','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-PROTOCOL' AND role_nm = 'Protocol Viewer'),KRIM_ROLE_MBR_ID_S.nextval,1);

INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000116','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'Protocol Creator'),KRIM_ROLE_MBR_ID_S.nextval,1);

INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000116','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-WKFLW' AND role_nm = 'IRBApprover'),KRIM_ROLE_MBR_ID_S.nextval,1);


INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'000001',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'unitNumber'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000116' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-PROTOCOL' AND role_nm = 'Protocol Aggregator')),1);

INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'000001',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'unitNumber'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000116' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'Protocol Creator')),1);

INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'Y',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'subunits'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000116' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'Protocol Creator')),1);


-- irbreviewer 
INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000117','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'IRB Reviewer'),KRIM_ROLE_MBR_ID_S.nextval,1);


INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'000001',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'unitNumber'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000117' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'IRB Reviewer')),1);

INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'Y',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'subunits'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000117' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'IRB Reviewer')),1);



-- irbadmin-card
INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000113','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'IRB Administrator'),KRIM_ROLE_MBR_ID_S.nextval,1);


INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'IN-CARD',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'unitNumber'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000113' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'IRB Administrator')),1);

INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'Y',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'subunits'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000113' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'IRB Administrator')),1);


-- irbaggregator
INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000114','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-PROTOCOL' AND role_nm = 'Protocol Aggregator'),KRIM_ROLE_MBR_ID_S.nextval,1);


INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'000001',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'unitNumber'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000114' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-PROTOCOL' AND role_nm = 'Protocol Aggregator')),1);


-- irbcreate 
INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000115','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'Protocol Creator'),KRIM_ROLE_MBR_ID_S.nextval,1);


INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'000001',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'unitNumber'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000115' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'Protocol Creator')),1);
   
INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'Y',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'subunits'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000115' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-UNT' AND role_nm = 'Protocol Creator')),1);

-- irbviewer
INSERT INTO KRIM_ROLE_MBR_T (LAST_UPDT_DT,MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (SYSDATE,'10000000118','P',SYS_GUID(),
(SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-PROTOCOL' AND role_nm = 'Protocol Viewer'),KRIM_ROLE_MBR_ID_S.nextval,1);

INSERT INTO KRIM_ROLE_MBR_ATTR_DATA_T (ATTR_DATA_ID,ATTR_VAL,KIM_ATTR_DEFN_ID,KIM_TYP_ID,OBJ_ID,ROLE_MBR_ID,VER_NBR)
  VALUES (KRIM_ATTR_DATA_ID_S.NEXTVAL,'000001',
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'unitNumber'),
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NMSPC_CD = 'KC-SYS' AND NM = 'UnitHierarchy'),SYS_GUID(),
(SELECT MAX(ROLE_MBR_ID) FROM KRIM_ROLE_MBR_T WHERE MBR_ID = '10000000118' 
   AND ROLE_ID = (SELECT role_id FROM KRIM_ROLE_T WHERE NMSPC_CD = 'KC-PROTOCOL' AND role_nm = 'Protocol Viewer')),1);


COMMIT;