INSERT INTO SUBCONTRACT_COPYRIGHT_TYPE (COPYRIGHT_TYPE_CODE,DESCRIPTION,OBJ_ID,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER)
VALUES ('1','Subrecipient Grants',SYS_GUID(),1,SYSDATE,'admin')
/
INSERT INTO SUBCONTRACT_COPYRIGHT_TYPE(COPYRIGHT_TYPE_CODE,DESCRIPTION,OBJ_ID,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER)
VALUES ('2','Subrecipient Shall Grant',SYS_GUID(),1,SYSDATE,'admin')
/
