CREATE SEQUENCE SEQUENCE_IPPUCS_ID INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_PROPOSAL_NUMBER INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_PROTO_NOTIFICATION_TEMPL INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_VALID_SUBM_REVW_TYPE_QUAL INCREMENT BY 1 START WITH 1 NOCACHE;
