CREATE OR REPLACE VIEW OSP$PROTOCOL_EXEMPT_CHKLST AS SELECT
    PROTOCOL_NUMBER,
    SEQUENCE_NUMBER,
    SUBMISSION_NUMBER,
    EXEMPT_STUDIES_CHECKLIST_CODE,
    UPDATE_TIMESTAMP,
    UPDATE_USER
FROM PROTOCOL_EXEMPT_CHKLST;
