-- View for Coeus compatibility 
CREATE OR REPLACE VIEW OSP$COMM_SCHEDULE_ATTENDANCE AS SELECT 
    COMM_SCHEDULE.SCHEDULE_ID, 
    COMM_SCHEDULE_ATTENDANCE.PERSON_ID, 
    COMM_SCHEDULE_ATTENDANCE.GUEST_FLAG, 
    COMM_SCHEDULE_ATTENDANCE.ALTERNATE_FLAG, 
    COMM_SCHEDULE_ATTENDANCE.ALTERNATE_FOR, 
    COMM_SCHEDULE_ATTENDANCE.NON_EMPLOYEE_FLAG, 
    COMM_SCHEDULE_ATTENDANCE.COMMENTS, 
    COMM_SCHEDULE_ATTENDANCE.UPDATE_TIMESTAMP, 
    COMM_SCHEDULE_ATTENDANCE.UPDATE_USER
FROM COMM_SCHEDULE_ATTENDANCE,
     COMM_SCHEDULE
WHERE COMM_SCHEDULE.ID = COMM_SCHEDULE_ATTENDANCE.SCHEDULE_ID_FK;

