CREATE or REPLACE VIEW OSP$PROTOCOL_ACTIONS AS SELECT
    PROTOCOL_NUMBER,
    SEQUENCE_NUMBER,
    SUBMISSION_NUMBER,
    ACTION_ID,
    COMMENTS,
    ACTION_DATE,
    UPDATE_TIMESTAMP,
    UPDATE_USER
FROM PROTOCOL_ACTIONS;
