-- View for Coeus compatibility 
CREATE OR REPLACE VIEW OSP$QUESTIONNAIRE_ANSWERS AS SELECT 
    QUESTIONNAIRE_ANSWER.QUESTIONNAIRE_AH_ID_FK, 
    QUESTION.QUESTION_ID, 
    QUESTIONNAIRE_ANSWER.QUESTION_NUMBER, 
    QUESTIONNAIRE_ANSWER.ANSWER_NUMBER, 
    QUESTIONNAIRE_ANSWER.ANSWER, 
    QUESTIONNAIRE_ANSWER.UPDATE_TIMESTAMP, 
    QUESTIONNAIRE_ANSWER.UPDATE_USER
FROM QUESTIONNAIRE_ANSWER,
     QUESTION
WHERE QUESTION.QUESTION_REF_ID = QUESTIONNAIRE_ANSWER.QUESTION_REF_ID_FK;
