set define off
set sqlblanklines on
spool KC-RELEASE-3_1_SP4-Upgrade-ORACLE-Install.log
@ORACLE/SEQUENCES/KC_SEQ_All.sql
@ORACLE/TABLES/KC_TBL_COMM_SCHEDULE.sql
@ORACLE/TABLES/KC_TBL_EPS_PROP_PERSON_EXT.sql
@ORACLE/TABLES/KC_TBL_NOTIFICATION.sql
@ORACLE/TABLES/KC_TBL_SPECIAL_REVIEW_USAGE.sql
@ORACLE/TABLES/KC_TBL_SPONSOR_FORMS.sql
@ORACLE/TABLES/KC_TBL_SPONSOR_FORM_TEMPLATES.sql
@ORACLE/DML/KC_DML_BS1_BUDGET_PERSONS.sql
@ORACLE/DML/KC_DML_BS1_CITIZENSHIP_TYPE_T.sql
@ORACLE/DML/KC_DML_BS1_COEUS_SUB_MODULE.sql
@ORACLE/DML/KC_DML_BS1_COMM_SCHEDULE.sql
@ORACLE/DML/KC_DML_BS1_PERSON_APPOINTMENT.sql
@ORACLE/DML/KC_DML_BS1_SPECIAL_REVIEW_USAGE.sql
@ORACLE/DML/KC_DML_BS1_TRAINING_STIPEND_RATES.sql
@ORACLE/DML/KC_DML_BS2_APPOINTMENT_TYPE.sql
@ORACLE/DML/KC_DML_BS2_SPONSOR_FORMS.sql
@ORACLE/CONSTRAINTS/KC_FK_EPS_PROP_PERSON_EXT.sql
@ORACLE/CONSTRAINTS/KC_FK_NOTIFICATION.sql
commit;
exit
