\. MYSQL/DML/KR_DML_BS1_KRIM_ENTITY_T.sql
\. MYSQL/DML/KR_DML_BS1_KRIM_PERM_T.sql
\. MYSQL/DML/SR/KR_DML_BS1_KRNS_PARM_T.sql
\. MYSQL/DML/KR_DML_BS2_KRIM_ENTITY_ENT_TYP_T.sql
\. MYSQL/DML/SR/KR_DML_BS2_KRIM_ROLE_PERM_T.sql
\. MYSQL/DML/KR_DML_BS2_KRIM_ROLE_RSP_ACTN_T.sql
\. MYSQL/DML/KR_DML_BS3_KRIM_PERM_T.sql
\. MYSQL/DML/SR/KR_DML_BS3_KRIM_PRNCPL_T.sql
\. MYSQL/DML/KR_DML_BS3_KRIM_ROLE_T.sql
\. MYSQL/DML/KR_DML_BS4_KRIM_GRP_MBR_T.sql
\. MYSQL/DML/KR_DML_BS4_KRIM_PERM_ATTR_DATA_T.sql
\. MYSQL/DML/KR_DML_BS4_KRIM_ROLE_PERM_T.sql
commit;
exit
