DELIMITER /
  CREATE TABLE SUBAWARD_STATUS 
   (	SUBAWARD_STATUS_CODE DECIMAL(3,0) NOT NULL, 
	DESCRIPTION VARCHAR(200) NOT NULL, 
	UPDATE_TIMESTAMP DATE NOT NULL, 
	UPDATE_USER VARCHAR(60) NOT NULL, 
	VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, 
	OBJ_ID VARCHAR(36) NOT NULL 
  ) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_bin
/
ALTER TABLE SUBAWARD_STATUS
  ADD CONSTRAINT PK_SUBAWARD_STATUS_TYPE PRIMARY KEY (SUBAWARD_STATUS_CODE)
/
DELIMITER ;
