DELIMITER /
ALTER TABLE PROTOCOL_CORRESPONDENCE ADD CREATE_TIMESTAMP DATE
/
ALTER TABLE PROTOCOL_CORRESPONDENCE ADD CREATE_USER VARCHAR(60)
/
ALTER TABLE PROTOCOL_CORRESPONDENCE ADD FINAL_FLAG_TIMESTAMP DATE
/
DELIMITER ;
