DELIMITER /
CREATE TABLE FIN_ENTITIES_DATA_GROUPS ( 
    DATA_GROUP_ID DECIMAL(3,0) NOT NULL, 
    DATA_GROUP_NAME VARCHAR(30) NOT NULL, 
    DATA_GROUP_SORT_ID DECIMAL(3,0) NOT NULL, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR(60) NOT NULL, 
    VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR(36) NOT NULL)
/
ALTER TABLE FIN_ENTITIES_DATA_GROUPS 
ADD CONSTRAINT PK_FIN_ENTITIES_DATA_GROUPS 
PRIMARY KEY (DATA_GROUP_ID)
/
DELIMITER ;
