DELIMITER /
CREATE TABLE FINANCIAL_ENTITY_REPORTER  ( 
    FINANCIAL_ENTITY_REPORTER_ID   DECIMAL(12,0) NOT NULL,
    PERSON_ID                      VARCHAR(40) NULL,
    REPORTER_ROLE_ID               VARCHAR(12) NULL,
    UPDATE_TIMESTAMP               DATE NULL,
    UPDATE_USER                    VARCHAR(60) NULL,
    VER_NBR                        DECIMAL(8,0) DEFAULT 1 NOT NULL,
    OBJ_ID                         VARCHAR(36) NOT NULL
)
/
ALTER TABLE FINANCIAL_ENTITY_REPORTER 
ADD CONSTRAINT PK_FINANCIAL_ENTITY_REPORTER 
PRIMARY KEY (FINANCIAL_ENTITY_REPORTER_ID)
/
DELIMITER ;
