DELIMITER /
CREATE TABLE FINANCIAL_ENTITY_CONTACT_INFO
   (
    FIN_ENTITY_CONTACT_INFO_ID DECIMAL(12,0) NOT NULL,
    PERSON_FIN_INT_DISCLOSURE_ID DECIMAL(12,0) NOT NULL, 
    ADDRESS_LINE_1 VARCHAR(80) NOT NULL,
    ADDRESS_LINE_2 VARCHAR(80),
    ADDRESS_LINE_3 VARCHAR(80),
    WEB_ADDRESS_1 VARCHAR(200),
    WEB_ADDRESS_2 VARCHAR(200),
    CITY VARCHAR(30) NOT NULL,
    STATE VARCHAR(30),
    POSTAL_CODE VARCHAR(15) NOT NULL,
    COUNTRY_CODE CHAR(3) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    UPDATE_USER VARCHAR(60) NOT NULL,
    VER_NBR DECIMAL(8,0) DEFAULT 1  NOT NULL,
    OBJ_ID VARCHAR(36) NOT NULL
)
/
ALTER TABLE FINANCIAL_ENTITY_CONTACT_INFO 
ADD CONSTRAINT PK_FIN_ENTITY_CONTACT_INFO 
PRIMARY KEY (FIN_ENTITY_CONTACT_INFO_ID)
/

DELIMITER ;
