DELIMITER /
DELETE FROM NOTIFICATION_TYPE_RECIPIENT WHERE NOTIFICATION_TYPE_ID =
(SELECT NOTIFICATION_TYPE_ID FROM NOTIFICATION_TYPE WHERE MODULE_CODE=8 AND ACTION_CODE='205' AND ROLE_NAME LIKE '%Disclosure Reviewer')
/

DELIMITER ;
