DELIMITER /

UPDATE NOTIFICATION_TYPE SET SUBJECT='{DISCLOSURE_TYPE} Disclosure has been approved.' WHERE MODULE_CODE='8' AND ACTION_CODE='204'
/
UPDATE NOTIFICATION_TYPE SET SUBJECT='{DISCLOSURE_TYPE} Disclosure has been disapproved.' WHERE MODULE_CODE='8' AND ACTION_CODE='304'
/
DELIMITER ;
