
CREATE OR REPLACE VIEW OSP$USER ( 
  USER_ID, USER_NAME, NON_MIT_PERSON_FLAG, PERSON_ID, USER_TYPE, UNIT_NUMBER, STATUS, UPDATE_TIMESTAMP, UPDATE_USER  ) 
  AS select USER_NAME,FULL_NAME,'N',PERSON_ID,null,HOME_UNIT,'A',UPDATE_TIMESTAMP,UPDATE_USER
	from PERSON;
