DELIMITER /
alter table BUDGET_SUB_AWARD_PERIOD_DETAIL
    add constraint FK1_BUDGET_SUBAWARD_PER_DET foreign key (SUBAWARD_NUMBER, BUDGET_ID)
    references BUDGET_SUB_AWARDS (SUB_AWARD_NUMBER, BUDGET_ID)
/

DELIMITER ;
