INSERT INTO KRIM_GRP_ID_BS_S VALUES (NULL);
INSERT INTO KRIM_GRP_T (GRP_ID, GRP_NM, NMSPC_CD, GRP_DESC, KIM_TYP_ID, ACTV_IND, LAST_UPDT_DT, OBJ_ID) 
  VALUES ((SELECT MAX(ID) FROM KRIM_GRP_ID_BS_S), 'QuestionnaireAdmin', 'KC-WKFLW', 'Questionnaire Blanket Approver', 1, 'Y', NOW(), UUID());
  
COMMIT;