TRUNCATE TABLE KREN_RECIP_LIST_T DROP STORAGE
/
INSERT INTO KREN_RECIP_LIST_T (CHNL_ID,RECIP_ID,RECIP_LIST_ID,RECIP_TYP_CD)
  VALUES (4,'testuser1',1,'USER')
/
INSERT INTO KREN_RECIP_LIST_T (CHNL_ID,RECIP_ID,RECIP_LIST_ID,RECIP_TYP_CD)
  VALUES (4,'testuser3',2,'USER')
/
