DELIMITER /

INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-AB','Award Budget',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-ADM','Kuali Coeus-Office of Sponsored Projects',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-AWARD','Award',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-B','Budget','RICE','Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-COMMITTEE','KC IRB Committee',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-GEN','General Kuali Coeus',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-IDM','Kuali Coeus KIM IDM & AuthZ',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-IP','Institutional Proposal',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-M','Maintenance','RICE','Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-PD','Proposal Development','RICE','Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-PROTOCOL','KC IRB Protocol',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-QUESTIONNAIRE','KC Questionnaire',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-SYS','Kuali Coeus System',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-T','Time And Money',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-UNT','Kuali Coeus - Department',null,'Y',UUID(),1)
/
INSERT INTO KRCR_NMSPC_T (NMSPC_CD,NM,APPL_ID,ACTV_IND,OBJ_ID,VER_NBR) 
    VALUES ('KC-WKFLW','KC Workflow Infrastructure',null,'Y',UUID(),1)
/

DELIMITER ;
