
/*
 * 
 */

package gov.grants.apply.webservices.applicantintegrationservices_v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Jun 25 11:36:48 EDT 2009
 * Generated source version: 2.1.3
 * 
 */


//@WebServiceClient(name = "ApplicantIntegrationServices", 
//                  wsdlLocation = "file:/Users/geo/eclipse/workspace/kc_project/src/main/config/wsdl/ApplicantIntegrationServices-V1_1.wsdl",
//                  targetNamespace = "http://apply.grants.gov/WebServices/ApplicantIntegrationServices-V1.0") 
public class ApplicantIntegrationServices extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://apply.grants.gov/WebServices/ApplicantIntegrationServices-V1.0", "ApplicantIntegrationServices");
    public final static QName ApplicantIntegrationSoapPort = new QName("http://apply.grants.gov/WebServices/ApplicantIntegrationServices-V1.0", "ApplicantIntegrationSoapPort");
//    public final static QName SERVICE = new QName("http://localhost:8080/app-s2s-server/services/ApplicantIntegrationServices-V1.0", "ApplicantIntegrationServices");
//    public final static QName ApplicantIntegrationSoapPort = new QName("http://localhost:8080/app-s2s-server/services/ApplicantIntegrationServices-V1.0", "ApplicantIntegrationSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/geo/eclipse/workspace/kc_project/src/main/config/wsdl/ApplicantIntegrationServices-V1_1.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/Users/geo/eclipse/workspace/kc_project/src/main/config/wsdl/ApplicantIntegrationServices-V1_1.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ApplicantIntegrationServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ApplicantIntegrationServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public ApplicantIntegrationServices() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ApplicantIntegrationPortType
     */
    @WebEndpoint(name = "ApplicantIntegrationSoapPort")
    public ApplicantIntegrationPortType getApplicantIntegrationSoapPort() {
        return super.getPort(ApplicantIntegrationSoapPort, ApplicantIntegrationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApplicantIntegrationPortType
     */
    @WebEndpoint(name = "ApplicantIntegrationSoapPort")
    public ApplicantIntegrationPortType getApplicantIntegrationSoapPort(WebServiceFeature... features) {
        return super.getPort(ApplicantIntegrationSoapPort, ApplicantIntegrationPortType.class, features);
    }

}
