--
-- Kuali Coeus, a comprehensive research administration system for higher education.
-- 
-- Copyright 2005-2015 Kuali, Inc.
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as
-- published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
-- 
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
--

delimiter /
TRUNCATE TABLE CONTACT_TYPE
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','Technical/Scientific Officer--1','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','Awarding Office Contact--1','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('3','Payment/Fiscal Reporting Contact','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('4','Intellectual Property Contact','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('5','Property Office Contact-1','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('6','Subcontracting Reporting Contact','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('7','Final Report Submission Address ','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('8','Other','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('9','Procurement Reporting Contact-1','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('10','Close-out Contact','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('11','Report Submission Address--1','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('12','Report Submission Address-2','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('13','Administrative Contact--1','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('14','Awarding Office Contact--2','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('15','Technical/Scientific Officer--2','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('16','Property Office Contact-2','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('17','Procurement Reporting Contact-2','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('18','Procurement Reporting Contact-3','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('19','Procurement Reporting Contact-4','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('20','Procurement Reporting Contact-5','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('21','Property Office Contact-3','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('22','Administrative Contact--2','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('23','Technical/Scientific Officer--3','admin',NOW(),UUID(),1)
/
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('24','Report Submission Address-3','admin',NOW(),UUID(),1)
/
delimiter ;
