delimiter /
TRUNCATE TABLE PROPOSAL_STATUS
/
INSERT INTO PROPOSAL_STATUS (PROPOSAL_STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (1,'Pending','admin',NOW(),UUID(),1)
/
INSERT INTO PROPOSAL_STATUS (PROPOSAL_STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (2,'Funded','admin',NOW(),UUID(),1)
/
INSERT INTO PROPOSAL_STATUS (PROPOSAL_STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (3,'Rejected','admin',NOW(),UUID(),1)
/
INSERT INTO PROPOSAL_STATUS (PROPOSAL_STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (4,'Deactivated','admin',NOW(),UUID(),1)
/
INSERT INTO PROPOSAL_STATUS (PROPOSAL_STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (5,'Withdrawn','admin',NOW(),UUID(),1)
/
INSERT INTO PROPOSAL_STATUS (PROPOSAL_STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (6,'Do Not Use -- Revision Requested','admin',NOW(),UUID(),1)
/
INSERT INTO PROPOSAL_STATUS (PROPOSAL_STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (7,'Held for Funds Availability','admin',NOW(),UUID(),1)
/
INSERT INTO PROPOSAL_STATUS (PROPOSAL_STATUS_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (8,'Void','admin',NOW(),UUID(),1)
/
delimiter ;
