INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 6, 'Subcontracting Reporting Contact', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 5, 'Property Office Contact-1', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 4, 'Intellectual Property Contact', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 3, 'Payment/Fiscal Reporting Contact', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 2, 'Awarding Office Contact--1', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 1, 'Technical/Scientific Officer--1', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( -1, ' ', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 8, 'Other', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 7, 'Final Report Submission Address ', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 9, 'Procurement Reporting Contact-1', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 10, 'Close-out Contact', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 11, 'Report Submission Address--1', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 12, 'Report Submission Address-2', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 13, 'Administrative Contact--1', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 14, 'Awarding Office Contact--2', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 15, 'Technical/Scientific Officer--2', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 16, 'Property Office Contact-2', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 17, 'Procurement Reporting Contact-2', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 18, 'Procurement Reporting Contact-3', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 19, 'Procurement Reporting Contact-4', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 20, 'Procurement Reporting Contact-5', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 21, 'Property Office Contact-3', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 22, 'Administrative Contact--2', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 23, 'Technical/Scientific Officer--3', sysdate, user ); 
INSERT INTO CONTACT_TYPE ( CONTACT_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER ) 
VALUES ( 24, 'Report Submission Address-3', sysdate, user ); 