
INSERT INTO MAIL_TYPE(MAIL_TYPE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
  VALUES(1, 'Regular',  sysdate,user);

INSERT INTO MAIL_TYPE(MAIL_TYPE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
  VALUES(2, 'Electronic',  sysdate,user);

INSERT INTO MAIL_TYPE(MAIL_TYPE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
  VALUES(3, 'Delivery Service',  sysdate,user);

