ALTER TABLE AWARD_PERSON_CREDIT_SPLITS 
    ADD CONSTRAINT FK_AP_CREDIT_SPLIT_AP 
            FOREIGN KEY (AWARD_PERSON_ID) 
                REFERENCES AWARD_PERSONS (AWARD_PERSON_ID) ;

ALTER TABLE AWARD_PERSON_CREDIT_SPLITS 
    ADD CONSTRAINT FK_AP_CREDIT_SPLIT_ICT 
            FOREIGN KEY (INV_CREDIT_TYPE_CODE) 
                REFERENCES INV_CREDIT_TYPE (INV_CREDIT_TYPE_CODE) ; 