ALTER TABLE AWD_BGT_DET_CAL_AMTS_EXT 
    ADD CONSTRAINT FK_AWD_BGT_DET_CAL_AMTS_EXT FOREIGN KEY (BUDGET_DETAILS_CAL_AMTS_ID) 
                REFERENCES BUDGET_DETAILS_CAL_AMTS (BUDGET_DETAILS_CAL_AMTS_ID) ;