ALTER TABLE BUDGET_RATE_AND_BASE 
    ADD CONSTRAINT FK_BUDGET_RATE_AND_BASE FOREIGN KEY (BUDGET_ID) 
                REFERENCES BUDGET;

ALTER TABLE BUDGET_RATE_AND_BASE 
    ADD CONSTRAINT FK2_BUDGET_RATE_AND_BASE FOREIGN KEY (BUDGET_DETAILS_CAL_AMTS_ID) 
                REFERENCES BUDGET_DETAILS_CAL_AMTS (BUDGET_DETAILS_CAL_AMTS_ID) ;

ALTER TABLE BUDGET_RATE_AND_BASE 
    ADD CONSTRAINT FK1_BUDGET_RATE_AND_BASE FOREIGN KEY (BUDGET_DETAILS_ID) 
                REFERENCES BUDGET_DETAILS (BUDGET_DETAILS_ID) ;
