-- Foreign Key Constraint(s) 
ALTER TABLE BATCH_CORRESPONDENCE 
    ADD CONSTRAINT FK_BATCH_CORRESPONDENCE_2 
            FOREIGN KEY (FINAL_ACTION_CORRESP_TYPE) 
                REFERENCES PROTO_CORRESP_TYPE (PROTO_CORRESP_TYPE_CODE) ;

ALTER TABLE BATCH_CORRESPONDENCE 
    ADD CONSTRAINT FK_BATCH_CORRESPONDENCE 
            FOREIGN KEY (FINAL_ACTION_TYPE_CODE) 
                REFERENCES PROTOCOL_ACTION_TYPE (PROTOCOL_ACTION_TYPE_CODE) ;