-- Foreign Key Constraint(s) 
ALTER TABLE COMM_SCHEDULE_MINUTES 
    ADD CONSTRAINT FK_COMM_SCHEDULE_MINUTES_3 FOREIGN KEY (PROTOCOL_CONTINGENCY_CODE) 
                REFERENCES PROTOCOL_CONTINGENCY (PROTOCOL_CONTINGENCY_CODE) ;

ALTER TABLE COMM_SCHEDULE_MINUTES 
    ADD CONSTRAINT FK_COMM_SCHEDULE_MINUTES_2 FOREIGN KEY (MINUTE_ENTRY_TYPE_CODE) 
                REFERENCES MINUTE_ENTRY_TYPE (MINUTE_ENTRY_TYPE_CODE) ;
                
ALTER TABLE COMM_SCHEDULE_MINUTES 
    ADD CONSTRAINT COMM_SCHEDULE_MINUTES_PRO_FK1 
            FOREIGN KEY (REVIEWER_ID_FK) 
                REFERENCES PROTOCOL_REVIEWERS (PROTOCOL_REVIEWER_ID) ENABLE;