-- Foreign Key Constraint(s)
ALTER TABLE PROPOSAL_SCIENCE_KEYWORD 
ADD CONSTRAINT FK_PROPOSAL_SCIENCE_KEYWORD2 
FOREIGN KEY (SCIENCE_KEYWORD_CODE) 
REFERENCES SCIENCE_KEYWORD (SCIENCE_KEYWORD_CODE);

ALTER TABLE PROPOSAL_SCIENCE_KEYWORD 
ADD CONSTRAINT FK_PROPOSAL_SCIENCE_KEYWORD 
FOREIGN KEY (PROPOSAL_ID) 
REFERENCES PROPOSAL (PROPOSAL_ID);

