ALTER TABLE PROTOCOL_ATTACHMENT_PA_TO_PROT
    ADD CONSTRAINT FK_PA_PA_TO_PROT_PROTOCOL 
    FOREIGN KEY (PROTOCOL_ID_FK) 
    REFERENCES PROTOCOL (PROTOCOL_ID);

ALTER TABLE PROTOCOL_ATTACHMENT_PA_TO_PROT
    ADD CONSTRAINT FK_PA_PA_TO_PROT_ATTACH
    FOREIGN KEY (PA_PROTOCOL_FK)
    REFERENCES PROTOCOL_ATTACHMENT_PROTOCOL (PA_PROTOCOL_ID);
