INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (1, 1, 1, SYSDATE, USER) ;

INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (2, 2, 1, SYSDATE, USER) ;

INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (3, 3, 1, SYSDATE, USER) ;

INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (4, 4, 1, SYSDATE, USER) ;

INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (5, 5, 1, SYSDATE, USER) ;

INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (6, 6, 1, SYSDATE, USER) ;

INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (7, 7, 1, SYSDATE, USER) ;

INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (8, 8, 1, SYSDATE, USER) ;

INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (9, 9, 1, SYSDATE, USER) ;

INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (10, 10, 1, SYSDATE, USER) ;

INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (12, 9, 2, SYSDATE, USER) ;

INSERT INTO PROTOCOL_ATTACHMENT_TYPE_GROUP (TYPE_GROUP_ID, TYPE_CD, GROUP_CD, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (11, 11, 2, SYSDATE, USER) ;

COMMIT;