INSERT INTO CORRESPONDENT_TYPE (CORRESPONDENT_TYPE_CODE, DESCRIPTION, QUALIFIER, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (1, 'Administrator', 'P', SYSDATE, USER) ;

INSERT INTO CORRESPONDENT_TYPE (CORRESPONDENT_TYPE_CODE, DESCRIPTION, QUALIFIER, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (2, 'CRC', 'P', SYSDATE, USER) ;

COMMIT;