CREATE TABLE TEMPEPY AS 
SELECT *
FROM   EPS_PROP_YNQ
WHERE  QUESTION_ID IN('11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '999', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'EC1', 'EC2', 'EO', 'FG', 'G3', 'G4', 'G6', 'G7', 'G8', 'G9', 'H0', 'H1', 'H2', 'H5', 'H6', 'H7', 'H8', 'H9', 'I7', 'I8', 'J1', 'J2', 'J4', 'NR', 'P002', 'P003', 'P007', 'P008', 'P1', 'P2', 'P3', 'P4', 'P5') ;

CREATE TABLE TEMPEPPY AS 
SELECT *
FROM   EPS_PROP_PERS_YNQ
WHERE  QUESTION_ID IN('11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '999', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'EC1', 'EC2', 'EO', 'FG', 'G3', 'G4', 'G6', 'G7', 'G8', 'G9', 'H0', 'H1', 'H2', 'H5', 'H6', 'H7', 'H8', 'H9', 'I7', 'I8', 'J1', 'J2', 'J4', 'NR', 'P002', 'P003', 'P007', 'P008', 'P1', 'P2', 'P3', 'P4', 'P5') ;

DELETE FROM eps_prop_ynq
WHERE  QUESTION_ID IN('11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '999', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'EC1', 'EC2', 'EO', 'FG', 'G3', 'G4', 'G6', 'G7', 'G8', 'G9', 'H0', 'H1', 'H2', 'H4', 'H5', 'H6', 'H7', 'H8', 'H9', 'I7', 'I8', 'J1', 'J2', 'J4', 'NR', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'Z1', 'Z2', 'Z3') ;

DELETE FROM eps_prop_pers_ynq
WHERE  QUESTION_ID IN('11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '999', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'EC1', 'EC2', 'EO', 'FG', 'G3', 'G4', 'G6', 'G7', 'G8', 'G9', 'H0', 'H1', 'H2', 'H4', 'H5', 'H6', 'H7', 'H8', 'H9', 'I7', 'I8', 'J1', 'J2', 'J4', 'NR', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'Z1', 'Z2', 'Z3') ;

DELETE FROM YNQ_EXPLANATION
WHERE  QUESTION_ID IN('11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '999', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'EC1', 'EC2', 'EO', 'FG', 'G3', 'G4', 'G6', 'G7', 'G8', 'G9', 'H0', 'H1', 'H2', 'H4', 'H5', 'H6', 'H7', 'H8', 'H9', 'I7', 'I8', 'J1', 'J2', 'J4', 'NR', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'Z1', 'Z2', 'Z3') ;

DELETE FROM YNQ
WHERE  QUESTION_ID IN('11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '999', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'EC1', 'EC2', 'EO', 'FG', 'G3', 'G4', 'G6', 'G7', 'G8', 'G9', 'H0', 'H1', 'H2', 'H4', 'H5', 'H6', 'H7', 'H8', 'H9', 'I7', 'I8', 'J1', 'J2', 'J4', 'NR', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'Z1', 'Z2', 'Z3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('EO', 'Is the proposal subject to review by state executive order 12372 process?', 'P', 3, NULL, 'Y', 'I', TO_DATE ('06-OCT-05', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '11E86190CADF4B27B0679D6DC655C0CC') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('P1', 'Can you certify that the information submitted within this application is true, complete and accurate to the best of your knowledge?   That any false, fictitious, or fraudulent statements or claims may subject you, as the PI/Co-PI/Co-I to criminal, civil or administrative penalties?  That you agree to accept responsibility for the scientific conduct of the project and to provide the required', 'I', 2, NULL, NULL, 'A', TO_DATE ('28-JUN-06', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, 'EC2EA2D2E1FD4362854F45DDAF741C57') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('P2', 'Is there any potential for a perceived or real conflict of interest as defined in MIT''s Policies and Procedures with regard to this proposal?', 'I', 2, NULL, NULL, 'A', TO_DATE ('28-JUN-06', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '2293BA26F25843AAB5929C499A3889CB') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('P3', 'If this is a NIH/NSF proposal have you submitted the required financial disclosures in the web based Coeus Conflict of Interest module?', 'I', 2, NULL, NULL, 'A', TO_DATE ('28-JUN-06', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '38BB2BE503124EAABFD1A3266EEA1290') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('P4', 'Have lobbying activities been conducted on behalf of this proposal?', 'I', 2, NULL, NULL, 'A', TO_DATE ('28-JUN-06', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '879D6A9136AD48CDA6BA715C8E1B5947') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('P5', 'Are you currently debarred, suspended, proposed for debarment, declared ineligible or voluntarily excluded from current transactions by a federal department or agency?', 'I', 2, NULL, NULL, 'A', TO_DATE ('28-JUN-06', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '76EA764B9A334DCDAF32130C328EDD26') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C6', 'For this entity, do you have stock, stock options, equity or other interests in excess of 5 percent of the ownership interest (aggregate for yourself, your spouse and your dependent children)?', 'F', 2, NULL, NULL, 'A', TO_DATE ('08-JUL-08', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '653A79675F7542748D33BA2F7881046F') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C5', 'For this entity, do you have stock, stock options, or other interests of significant monetary value in excess of $10,000 in fair market value (aggregate for yourself, your spouse and your dependent children)?', 'F', 2, NULL, NULL, 'A', TO_DATE ('08-JUL-08', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, 'D3431A27F1264EF48D71F5B0BF6B4214') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C7', 'Do you have stock, stock options, or other interests of significant monetary value in excess of $10,000 in fair market value (aggregate for yourself, your spouse, and your dependent children)?', 'C', 2, NULL, NULL, 'A', TO_DATE ('08-JUL-08', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '53DC5831F75F4AE8A78CD57F5A12F928') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C8', 'Do you have stock, stock options, equity or other interests in excess of 5 percent of the ownership interest in any company (aggregate for yourself, your spouse, and your dependent children)?', 'C', 2, NULL, NULL, 'A', TO_DATE ('08-JUL-08', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '9FC4BC4BEF5E487199F49DDBE60D75E2') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('EC1', 'Will any equipment be exported by MIT in the course of this project?', 'P', 2, NULL, NULL, 'A', TO_DATE ('28-MAR-07', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '35BC5FFD8064415AB80778C960A90AB4') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('EC2', 'Will this project require any export controlled information to be received on campus? Contact Jennifer Ponting 3-2822 if you have questions.', 'P', 2, NULL, NULL, 'A', TO_DATE ('28-MAR-07', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '49F03305DF8A430BAEBECDC52823E0EF') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('28', 'Is this a clinical trial?', 'P', 2, NULL, NULL, 'A', TO_DATE ('20-FEB-09', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, 'FCF835CC0FA64438A1803BC57313A7C9') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('29', 'Is the Government permitted to disclose the project title, and the contact information of the signing official, to organizations that may be interested in contacting you for further information ?', 'P', 2, NULL, NULL, 'A', TO_DATE ('20-FEB-09', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '8F028EDD7CF54A4AB28EF32A4AAFDA23') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('30', 'Is this organization being created in order to submit applications as an individual rather than as a company, state, local or tribal government, academia, or other type of organization?', 'O', 2, NULL, NULL, 'A', TO_DATE ('20-FEB-09', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, 'AC318774A0554C0FA3E48574E1A9C270') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('31', 'Is this proposal an NSF Accomplishment Based renewal?', 'P', 2, NULL, NULL, 'A', TO_DATE ('20-FEB-09', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '2484392649A740218052607676FCA8C1') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('32', 'Is the Government permitted to disclose the project title, and the contact information of the signing official, to organizations that may be interested in contacting you for further information?', 'P', 2, NULL, NULL, 'I', TO_DATE ('11-MAR-09', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, 'EF20CAA8A9FF4BFF93F1705DC97EA988') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('999', 'test question', 'P', 2, 'N', 'N', 'A', TO_DATE ('27-MAY-09', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '1076DFE26CEB4C2D8EB6C0712703EF9B') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('14', 'This is an NSF Small Grant for Exploratory Research', 'P', 2, NULL, NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38361E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C3', 'For any entity (company or public or non-proft organization) did you receive in last 12 months, or do you expect to receive in the next 12 months, salary director''s fees, consulting payments, honoraria, royalties or other payments for patents, copyrights or other intellectual property, or any other payments exceeding $10,000 (aggregate for yourself, your spouse, and your dependent children)', 'C', 2, 'Y', NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38363E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C4', 'Do you have stock, stock options, or other interests of significant monetary value either in excess of $10,000 in fair market value or in excess of 5 percent of the ownership interest in any company? (In either case, aggregate for yourself, your spouse and your dependent children; in the case of stock in companies that are not publicly traded, use most recent sales price recognized by the company)', 'C', 2, 'Y', NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38364E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('15', 'Is this proposal being submitted to other agencies?  If so, please list agency acronyms in explanation separated by commas.', 'P', 2, 'Y', NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38365E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('16', 'Have all inventions or patents been previously reported?  Answer NA if there are no inventions or patents.', 'P', 3, NULL, NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38366E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('18', 'Are human embryonic stem cells used?  If so, list the registration numbers of the cell lines in the comment.', 'P', 2, 'Y', NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38367E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('17', 'Is this a Phase III Clinical Trial as defined by NIH?', 'P', 2, NULL, NULL, 'A', TO_DATE ('19-MAY-05', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38368E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('19', 'Are you currently serving, or have you previously served, as a PI, co-PI or Program Director on any Federally funded project?', 'P', 2, NULL, NULL, 'A', TO_DATE ('01-JUL-05', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38369E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('20', 'Does the proposal contain high resolution graphics or other graphics where exact color representation is required for proper interpretation (GPG, Chapter I.G.1)?', 'P', 2, NULL, NULL, 'A', TO_DATE ('01-JUL-05', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B3836AE7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('21', 'Is the proposal a full application related to submission of a preliminary application?', 'P', 2, NULL, NULL, 'A', TO_DATE ('01-JUL-05', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B3836BE7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('22', 'Is the principal investigator changing with this application?  If so, please enter last and first names of previous investigator in explanation. Please enter LAST NAME, FIRST NAME.', 'P', 2, 'Y', NULL, 'A', TO_DATE ('17-OCT-06', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B3836CE7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('23', 'Has the grantee institution changed with this application? If so, enter name of previous institution in explanation field.', 'P', 2, 'Y', NULL, 'A', TO_DATE ('17-OCT-06', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B3836DE7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('24', 'Is the principal investigator participating in this project as an employee of the U.S. Government? If so,  please click on ''More'' for instructions.', 'P', 2, 'Y', NULL, 'A', TO_DATE ('31-OCT-06', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B3836EE7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('25', 'Is the principal investigator participating in this project as an employee of a foreign organization?', 'P', 2, NULL, NULL, 'A', TO_DATE ('31-OCT-06', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B3836FE7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('26', 'For Dept. of Education, Check "Yes" or "No" only if assistance is being requested under a program that gives special consideration to novice applicants. Otherwise, check "Not Applicable".', 'P', 3, 'Y', NULL, 'A', TO_DATE ('28-NOV-06', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38370E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('11', 'Is there space change on this proposal', 'P', 2, 'Y', NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38349E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('H1', 'Project involves the International Cooperative activities?', 'P', 2, 'Y', 'Y', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B3834BE7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('FG', 'Application is Certified  ', 'P', 2, 'N', 'N', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B3834CE7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('G9', 'This Project is in Violation of an Environmental Compliance Regulation', 'P', 2, 'Y', 'Y', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38350E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('J4', 'Project Requires Inter-Government Review for Activities that affect State or Local Government or Possible National Security Implications', 'P', 2, NULL, NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38351E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C1', 'From this entity did you receive in the last 12 months, or do you expect to receive in the next 12 months, salary, director''s fee, consulting payments, honoraria, royalties or other payments for patents, copyrights or other intellectual property, or any other payments that will exceed $10,000 (aggregate for yourself, your spouse, and your dependant children)?', 'F', 2, 'Y', NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38353E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('G3', 'Hazardous Materials are Used or Produced', 'P', 2, 'Y', 'Y', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38354E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('H2', 'Human Anatomical Substances Are Used   ', 'P', 2, 'Y', NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38356E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('G4', 'Genetically Engineered organisms are Used or Produced', 'P', 2, 'Y', 'Y', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38357E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('12', 'NSF Beginning Investigator ', 'P', 2, NULL, NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B3835FE7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('13', 'NIH Beginning Investigator', 'P', 2, NULL, NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38360E7A8E0404F8189D817C3') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('P002', 'Is there a space change on this proposal?', 'P', 3, 'Y', 'Y', 'I', TO_DATE ('01-NOV-07', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '392C8C65-583C-2EC1-0828-0A0F83297C23') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('P007', 'NSF Beginning Investigator?', 'P', 3, NULL, NULL, 'I', TO_DATE ('06-NOV-07', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '3EBEEDE5260B3150E043814FD8813150') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('P008', 'NIH Beginning Investigator?', 'P', 2, NULL, NULL, 'I', TO_DATE ('06-NOV-07', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '3EBEEDE5260D3150E043814FD8813150') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('NR', 'No Restrictions', 'O', 2, NULL, NULL, 'I', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8B30235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('H7', 'Organization Provides a Smoke Free Workplace', 'O', 2, 'N', 'N', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8B40235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('H6', 'Organization Certifies Compliance with the Code of Federal Regulations Regarding Research Misconduct', 'O', 2, 'N', 'N', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8B50235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('H5', 'Organization Certifies Compliance With the Drug-Free Workplace Act', 'O', 2, 'N', 'N', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8B60235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('J2', 'Rate Negotiated ', 'O', 2, 'N', 'N', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8B70235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('G7', 'Facilities are Properly Accredited or Authorized', 'O', 2, 'N', 'N', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8B80235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('J1', 'Military Services Barred from Recruitment Activities at the Proposing Organization''s Site(s)', 'O', 2, 'Y', 'Y', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8B90235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('H0', 'Organization Certifies Compliance with Federal Lobbing Regulation', 'O', 2, 'N', 'N', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8BA0235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('I8', 'Organization has been Placed on the Federal Debarment and Suspension List', 'O', 2, 'Y', 'Y', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8BB0235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('I7', 'Organization has Delinquent Federal Debts', 'O', 2, 'Y', 'Y', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8BC0235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('H9', 'Organization Certifies Compliance with the Code of Federal Regulations Regarding Responsibility of Applicants for Promoting Objectivity in Research for which Public Health Service (PHS) Funding is Sought', 'O', 2, 'N', 'N', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8BD0235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('H8', 'Organization Certifies Compliance with Federal Discrimination Regulations ', 'O', 2, 'N', 'N', 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , NULL, TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '497F7EB7C8BE0235E0404F8189D86503') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('27', 'If this project has an actual or potential impact on the environment, has an exemption been authorized or an environmental assessment (EA) or environmental impact statement (EIS) been performed?  If yes, please explain in comments.', 'P', 3, 'YN', NULL, 'A', TO_DATE ('01-JUN-08', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '2077B242-EF68-2448-8D72-9BD539A921BB') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('G8', 'Proprietary or Privileged Information will be contained in the Application', 'P', 2, NULL, NULL, 'A', TO_DATE ('01-JUN-08', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 2, 'E2FBDBBD-B0D3-8AF3-49E2-39B49E27BC32') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('G6', 'Historical Sites Are Affected', 'P', 2, NULL, NULL, 'A', TO_DATE ('01-JUN-08', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '9A5AC511-54B8-C209-175A-B1F18D3C08FC') ;

INSERT INTO YNQ (QUESTION_ID, DESCRIPTION, QUESTION_TYPE, NO_OF_ANSWERS, EXPLANATION_REQUIRED_FOR, DATE_REQUIRED_FOR, STATUS, EFFECTIVE_DATE, GROUP_NAME, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C2', 'For this entity, do you have stock, stock options, or other interests of significant monetary value either in excess of $10,000 in fair market value or in excess of 5 percent of the ownership interest in a company? (In either case, aggregate for yourself, your spouse and your dependant children; in the case of stock in companies that are not publicly traded, use the most recent sales price)', 'F', 2, 'Y', NULL, 'A', TO_DATE ('01-JAN-00', 'DD-MON-RR') , 'General Y/N Questions', TO_DATE ('15-SEP-09', 'DD-MON-RR') , 'KCDEV', 1, '4F69F5B38348E7A8E0404F8189D817C3') ;

COMMIT;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('P1', 'E', TO_DATE ('28-JUN-06', 'DD-MON-RR') , 'OSPA', 1, '6AC05D43AE2F4D5D8D222980A24933DF') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C6', 'E', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, '31A80692FC1E4CCE86F11DCB3368D576') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C6', 'P', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, 'EB18E9604C534C32A3D2FEE5FC777B33') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C6', 'R', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, '66A37C94725842A38051CE51AFAFFF0F') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C5', 'E', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, '92F652EEA4F4470E9EE136DAD0642553') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C5', 'P', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, 'DDB02F5AF3FD40D182A335E1A72A1F69') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C5', 'R', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, 'F474E73D261A43B18F68C8755C0B8947') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C7', 'E', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, 'E6730EC23B47413DA6A43CF0240A9ECE') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C7', 'P', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, '1ABAD2DB6FB543F1BD962E6B0E2F7A59') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C7', 'R', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, '7C1AE831833046348FC19F4AB10FC12E') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C8', 'E', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, 'CD456B0838114894B96F1A1B7C5609A9') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C8', 'P', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, '4A4EC01679ED447490534FBF0B8BD59A') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C8', 'R', TO_DATE ('07-JUL-08', 'DD-MON-RR') , 'ELE', 1, 'A45AA51F6A6C4AD48CFB2C7F159632AE') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C3', 'R', TO_DATE ('08-JUL-08', 'DD-MON-RR') , 'CWOOD', 1, '6E1B7B1BFCB54B8A9029D0EAA8891965') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C1', 'R', TO_DATE ('08-JUL-08', 'DD-MON-RR') , 'CWOOD', 1, 'A6D1FF46F72C49ED842E388E14230B20') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('26', 'E', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B3838EE7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C1', 'E', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B3838FE7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C1', 'P', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B38390E7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C2', 'E', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B38391E7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('12', 'E', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B38388E7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('13', 'E', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B38389E7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('15', 'E', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B3838AE7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('16', 'E', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B3838BE7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('18', 'E', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B3838CE7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('24', 'E', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B3838DE7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C2', 'P', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B38392E7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C3', 'P', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B38393E7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C3', 'E', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B38394E7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C4', 'E', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B38395E7A8E0404F8189D817C3') ;

INSERT INTO YNQ_EXPLANATION (QUESTION_ID, EXPLANATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES('C4', 'P', TO_DATE ('11-JUN-08', 'DD-MON-RR') , 'KRACNV', 1, '4F69F5B38396E7A8E0404F8189D817C3') ;

COMMIT;

INSERT INTO eps_prop_ynq SELECT *FROM TEMPEPY WHERE TEMPEPY.QUESTION_ID IN(SELECT QUESTION_ID FROM YNQ) ;

INSERT INTO eps_prop_pers_ynq SELECT *FROM TEMPEPPY;

COMMIT;

DROP TABLE TEMPEPY;

DROP TABLE TEMPEPPY;