INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (1, 'human_subjects', 'No', 'This award has no human protocols attached', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (2, 'human_subjects', 'Unknown', 'Unkown if this award has human subjects', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (3, 'interest_revenue', '2', 'MIT has committed interest to the project', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (4, 'interest_revenue', '1', 'Sponsor requires interest be applied to the project', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (5, 'yes_no_flag', 'Yes', 'Yes', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (6, 'yes_no_flag', 'No', 'No', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (7, 'PI_Question', 'Z1', NULL, SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (8, 'PI_Question', 'Z2', NULL, SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (9, 'PI_Question', 'Z3', NULL, SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (10, 'PI_Question', 'Z4', NULL, SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (11, 'human_subjects', 'Yes', 'This award has human protocols attached', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (12, 'PI_Question', 'Z5', NULL, SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (13, 'Sponsor_routing', 'DOD', 'DOD sponsors', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (14, 'Sponsor_routing', 'DOE', 'DOE sponsors', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (15, 'Sponsor_routing', 'NASA', 'NASA sponsors', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (16, 'Sponsor_routing', 'NIH', 'NIH sponsors', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (17, 'Sponsor_routing', 'NSF', 'NSF sponsors', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (18, 'interest_revenue', '4', 'Account originally created as a non-sponsored account', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (19, 'interest_revenue', '5', 'Account is an endowment and is being replaced', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (20, 'interest_revenue', '3', 'MIT has committed interest to an internal order', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (21, 'revenue', 'Non-Transferable', 'Revenue is non-transferable', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (22, 'revenue', 'Transferable', 'Revenue may be transfered ', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (23, 'interest_revenue', '0', 'Undetermined or Non Interest Bearing', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (24, 'AppointmentTypes', '1', '9M DURA TION', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (25, 'AppointmentTypes', '2', '10M DURATION', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (26, 'AppointmentTypes', '3', '11M DURATION', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (27, 'AppointmentTypes', '4', '12M DURATION', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (28, 'AppointmentTypes', '5', 'REG EMPLOYEE', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (29, 'AppointmentTypes', '6', 'SUM EMPLOYEE', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (30, 'AppointmentTypes', '7', 'TMP EMPLOYEE', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (31, 'PeriodTypes', 'CY', 'Calendar', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (32, 'PeriodTypes', 'SP', 'Summer', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (33, 'PeriodTypes', 'CC', 'Cycle', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (34, 'PeriodTypes', 'AP', 'Academic', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (35, 'ProjectRoles', '1', 'Undefined', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (36, 'ProjectRoles', '2', 'Investigator', SYSDATE, USER) ;

INSERT INTO ARG_VALUE_LOOKUP (ARG_VALUE_LOOKUP_ID, ARGUMENT_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (37, 'ProjectRoles', '3', 'Co-Investigator', SYSDATE, USER) ;

COMMIT;