/*Load Script For REPORT_CLASS Table*/ 
INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, GENERATE_REPORT_REQUIREMENTS)
VALUES('1', 'Financial', SYSDATE, USER, 'Y') ;

INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, GENERATE_REPORT_REQUIREMENTS)
VALUES('3', 'Intellectual Property', SYSDATE, USER, 'Y') ;

INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, GENERATE_REPORT_REQUIREMENTS)
VALUES('5', 'Procurement', SYSDATE, USER, 'Y') ;

INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, GENERATE_REPORT_REQUIREMENTS)
VALUES('2', 'Property', SYSDATE, USER, 'y') ;

INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, GENERATE_REPORT_REQUIREMENTS)
VALUES('4', 'Technical/Management', SYSDATE, USER, 'Y') ;

INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, GENERATE_REPORT_REQUIREMENTS)
VALUES('7', 'Proposals Due', SYSDATE, USER, 'Y') ;

COMMIT;