INSERT INTO IP_REVIEW_REQ_TYPE (IP_REVIEW_REQ_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (1, 'Expedited', SYSDATE, user) ;

INSERT INTO IP_REVIEW_REQ_TYPE (IP_REVIEW_REQ_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (2, 'Special', SYSDATE, user) ;

INSERT INTO IP_REVIEW_REQ_TYPE (IP_REVIEW_REQ_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (3, 'Standard', SYSDATE, user) ;

INSERT INTO IP_REVIEW_REQ_TYPE (IP_REVIEW_REQ_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (4, 'Other', SYSDATE, user) ;

COMMIT;