INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (1, 1, 1, 'C', 'Does this project involve human subjects?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (2, 1, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (3, 1, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (4, 1, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (5, 2, 1, 'C', 'Does this project involve animal subjects?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (6, 5, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (7, 5, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (8, 5, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (9, 3, 1, 'C', 'Are you involved in recruiting and/or obtaining consent of human subjects to participate in this study?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (10, 9, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (11, 9, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (12, 9, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (13, 4, 1, 'C', 'Will the entity provide a drug, device, vaccine or procedure for use in the protocol?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (14, 13, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (15, 13, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (16, 13, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (17, 5, 1, 'C', 'Are you the inventor of any drug, device, vaccine or procedure associated with this protocol?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (18, 17, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (19, 17, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (20, 17, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (21, 6, 1, 'C', 'Will Non-University Investigators be involved with the PI or Co-PI in the design, conduct or reporting of the activities associated with the project (e.g., subcontractors, consultants, others with significant responsibilities)?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (22, 21, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (23, 21, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (24, 21, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (25, 7, 1, 'C', 'Please explain where we can find the institutions'' policies that indicate compliance with the funding agency''s regulations.  You may also attach materials and enter "See attached".', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (26, 25, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (27, 25, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (28, 25, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (29, 8, 1, 'C', 'Please indicate the protocol number.', 'A', 1, 6, 'org.kuali.kra.irb.Protocol', 'protocolNumber', NULL, 1, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (30, 29, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (31, 29, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (32, 29, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (33, 9, 1, 'C', 'Please indicate the name of the drug, device, vaccine or procedure.', 'A', 1, 5, NULL, NULL, 1, 1, 50, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (34, 33, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (35, 33, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (36, 33, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (37, 10, 1, 'C', 'Are you a consultant with this entity?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (38, 37, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (39, 37, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (40, 37, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (41, 11, 1, 'C', 'Do you have a written consulting agreement (non-University agreement) with this entity?  If yes, please attach a copy of the agreement to this report.', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (42, 41, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (43, 41, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (44, 41, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (45, 12, 1, 'C', 'Please describe in detail the frequency and nature of your consulting activities with this entity.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (46, 45, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (47, 45, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (48, 45, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (49, 13, 1, 'C', 'Will the terms of your consulting in any way restrict the release of information or other dissemination of research results by faculty/researchers involved in the project?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (50, 49, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (51, 49, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (52, 49, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (53, 14, 1, 'C', 'Do you, your spouse, registered domestic partner, or any dependent child(ren) hold a position of management or employment with this entity?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (54, 53, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (55, 53, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (56, 53, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (57, 15, 1, 'C', 'Please indicate the positions held.', 'A', 1, 5, NULL, NULL, 7, 7, 50, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (58, 57, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (59, 57, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (60, 57, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (61, 16, 1, 'C', 'Please describe the responsibilities of your position(s) with the entity and how they relate to the project funded by the entity.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (62, 61, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (63, 61, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (64, 61, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (65, 17, 1, 'C', 'Do you, your spouse, registered domestic partner, or any dependent child(ren) hold an equity interest in this entity?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (66, 65, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (67, 65, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (68, 65, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (69, 18, 1, 'C', 'Please indicate the type of equity interest that you, your spouse, registered domestic partner, or any dependent child(ren) have in this entity.', 'A', 1, 5, NULL, NULL, 4, 4, 50, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (70, 69, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (71, 69, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (72, 69, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (73, 19, 1, 'C', 'Is the equity publicly traded?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (74, 73, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (75, 73, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (76, 73, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (77, 20, 1, 'C', 'What is the current total market value of the equity you, your spouse, registered domestic partner, and any dependent children hold in this entity?', 'A', 1, 5, NULL, NULL, 1, 1, 50, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (78, 77, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (79, 77, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (80, 77, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (81, 21, 1, 'C', 'Please provide an internal estimate of the value of the equity.', 'A', 1, 5, NULL, NULL, 1, 1, 50, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (82, 81, 'E', 'Branch from Equity publicly traded', SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (83, 81, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (84, 81, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (85, 22, 1, 'C', 'Please indicate the total percentage of equity held in this entity.', 'A', 1, 3, NULL, NULL, 1, 1, 3, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (86, 85, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (87, 85, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (88, 85, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (89, 23, 1, 'C', 'For non-governmental sponsored projects, is the entity supporting full direct and indirect costs of this project? If a gift or Material Transfer Agreement indicate "Not Applicable."', 'A', 1, 2, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (90, 89, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (91, 89, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (92, 89, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (93, 24, 1, 'C', 'List any other entity funding this research and their amount of support. Also identify any University funds that will be supplementing the project.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (94, 93, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (95, 93, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (96, 93, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (97, 25, 1, 'C', 'Will the research be conducted in the entity''s facilities?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (98, 97, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (99, 97, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (100, 97, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (101, 26, 1, 'C', 'How many hours per week will be spent in the entity''s facilities?', 'A', 1, 5, NULL, NULL, 1, 1, 50, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (102, 101, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (103, 101, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (104, 101, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (105, 27, 1, 'C', 'Will any of the entity''s personnel work on the research?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (106, 105, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (107, 105, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (108, 105, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (109, 28, 1, 'C', 'Please explain what the entities'' personnel will be doing on the research.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (110, 109, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (111, 109, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (112, 109, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (113, 29, 1, 'C', 'Please indicate the amount received in the past 12 months.', 'A', 1, 5, NULL, NULL, 1, 1, 50, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (114, 113, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (115, 113, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (116, 113, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (117, 30, 1, 'C', 'Please explain.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (118, 117, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (119, 117, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (120, 117, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (121, 31, 1, 'C', 'Have you received honoraria income from the entity?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (122, 121, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (123, 121, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (124, 121, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (125, 32, 1, 'C', 'Please describe the nature and frequency of your activities with this entity.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (126, 125, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (127, 125, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (128, 125, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (129, 33, 1, 'C', 'Are your activities with this entity related to the subject of the proposed research?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (130, 129, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (131, 129, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (132, 129, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (133, 34, 1, 'C', 'Please describe how activities with this entity are related to the subject of the proposed research.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (134, 133, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (135, 133, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (136, 133, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (137, 35, 1, 'C', 'Is entity a subcontractor, consortium member, supplier of goods, lessor, or otherwise involved with the project?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (138, 137, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (139, 137, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (140, 137, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (141, 36, 1, 'C', 'Please explain how they are involved with the project.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (142, 141, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (143, 141, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (144, 141, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (145, 37, 1, 'C', 'Are you the inventor of any device, vaccine, procedure, drug or any other product associated with this research?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (146, 145, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (147, 145, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (148, 145, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (149, 38, 1, 'C', 'Does the entity manufacture or commercialize any device, vaccine, procedure, drug or any other product associated with this research?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (150, 149, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (299, 149, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (300, 149, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (151, 39, 1, 'C', 'Please explain what the entity does that is associated with this research.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (152, 151, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (153, 151, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (154, 151, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (155, 40, 1, 'C', 'Is it reasonable to anticipate that the entity will be, or could be, directly and significantly affected by the design, conduct or reporting of the research activity?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (156, 155, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (157, 155, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (158, 155, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (159, 41, 1, 'C', 'Please explain how the entity might be impacted by the design, conduct or reporting of the research activity.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (160, 159, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (161, 159, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (162, 159, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (163, 42, 1, 'C', 'Is the entity a non-profit foundation?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (164, 163, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (165, 163, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (166, 163, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (167, 43, 1, 'C', 'Do you have a financial interest in the company(ies) that is (are) providing funds to this non-profit foundation?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (168, 167, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (169, 167, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (170, 167, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (171, 44, 1, 'C', 'If the sponsoring foundation is primarily a vehicle for one or two companies or a closely cooperating group of businesses, please identify these firms:', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (172, 171, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (173, 171, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (174, 171, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (175, 45, 1, 'C', 'Will the project purchase/lease any device/material from the entity?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (176, 175, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (177, 175, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (178, 175, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (179, 46, 1, 'C', 'Please provide name of any devices/materials and approximate cost.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (180, 179, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (181, 179, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (182, 179, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (183, 47, 1, 'C', 'Excluding gifts, contracts or grants administered by the University, have you, your spouse, registered domestic partner or dependent child(ren) received income from this entity in the past 12 months?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (184, 183, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (185, 183, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (186, 183, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (187, 48, 1, 'C', 'Please indicate the nature of income you received from this entity.', 'A', 1, 5, NULL, NULL, 4, 4, 50, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (188, 187, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (189, 187, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (190, 187, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (191, 49, 1, 'C', 'Please explain how you are keeping your interests and obligations to the entity separate from your University activities.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (192, 191, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (193, 191, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (194, 191, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (195, 50, 1, 'C', 'Were you part of a formal committee/body that made the decision which led to the award?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (196, 195, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (197, 195, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (198, 195, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (199, 51, 1, 'C', 'Were you present when the decision which led to the award was made?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (200, 199, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (201, 199, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (202, 199, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (203, 52, 1, 'C', 'Please describe the proceedings or enter "see attachment" and upload a copy of the minutes.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (204, 203, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (205, 203, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (206, 203, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (207, 53, 1, 'C', 'Does the project involves testing of any drugs or devices or the development of a product?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (208, 207, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (209, 207, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (210, 207, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (211, 54, 1, 'C', 'Briefly describe the research project (or enter "see attachment" and upload a statement of work/abstract).', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (212, 211, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (213, 211, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (214, 211, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (215, 55, 1, 'C', 'Provide a detailed description of the research project (or enter "see attachment" and upload a statement of work/abstract).', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (216, 215, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (217, 215, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (218, 215, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (219, 56, 1, 'C', 'Is the entity providing any proprietary data, materials or equipment?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (220, 219, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (221, 219, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (222, 219, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (223, 57, 1, 'C', 'Explain what control on access to the research will be necessary.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (224, 223, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (225, 223, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (226, 223, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (227, 58, 1, 'C', 'Does the entity participate in deciding the direction of the research?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (228, 227, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (229, 227, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (230, 227, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (231, 59, 1, 'C', 'Please explain what role the entity will play in participating or deciding the direction of the research.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (232, 231, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (233, 231, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (234, 231, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (235, 60, 1, 'C', 'For non-governmental sponsored projects: Will the contract, grant or gift that will fund this research require the granting of an exclusive license or option to the entity?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (236, 235, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (237, 235, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (238, 235, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (239, 61, 1, 'C', 'Please explain how it is documented in a research agreement or clinical trial agreement:', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (240, 239, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (241, 239, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (242, 239, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (243, 62, 1, 'C', 'Does the entity hold rights in a pending patent application/issued patent/copyright in which you, your spouse, registered domestic partner, or domestic child(ren) are inventor(s)/author(s)?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (244, 243, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (245, 243, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (246, 243, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (247, 63, 1, 'C', 'Has the entity licensed rights from the University?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (248, 247, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (249, 247, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (250, 247, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (251, 64, 1, 'C', 'Please indicate the invention/copyright disclosure number.', 'A', 1, 5, NULL, NULL, 1, 1, 50, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (252, 251, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (253, 251, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (254, 251, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (255, 65, 1, 'C', 'Does the entity have ownership rights?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (256, 255, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (257, 255, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (258, 255, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (259, 66, 1, 'C', 'Please explain how the entity acquired ownership rights.', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (260, 259, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (261, 259, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (262, 259, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (263, 67, 1, 'C', 'Does the entity have ownership rights on existing intellectual property?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (264, 263, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (265, 263, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (266, 263, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (267, 68, 1, 'C', 'Are any undergraduate, graduate or postdoctoral students involved in the project?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (268, 267, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (269, 267, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (270, 267, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (271, 69, 1, 'C', 'How many undergraduates, graduates and/or postdocs are involved and in what capacity?', 'A', 1, 5, NULL, NULL, 1, 1, 1000, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (272, 271, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (273, 271, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (274, 271, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (275, 70, 1, 'C', 'Are there any constraints or restrictions imposed on the reporting of student work?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (276, 275, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (277, 275, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (278, 275, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (279, 71, 1, 'C', 'Are you the advisor to any of these students?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (280, 279, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (281, 279, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (282, 279, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (283, 72, 1, 'C', 'Do you hold a position (such as board member, scientific advisor, director, officer, partner, trustee or employee) with any single business entity that could reasonably appear to benefit by the proposed research?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (284, 283, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (285, 283, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (286, 283, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (287, 73, 1, 'C', 'Do you have an equity interest (stock, stock options, real estate, investment or other ownership) with any single business entity that could reasonably appear to benefit by the proposed research?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (288, 287, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (289, 287, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (290, 287, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (291, 74, 1, 'C', 'Do you receive income (such as consulting fees, honoraria, travel reimbursement, or other income) from any single business entity that could reasonably appear to benefit by the proposed research?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (292, 291, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (293, 291, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (294, 291, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (295, 75, 1, 'C', 'Do you have rights to a pending application or issued patent to an invention(s), license rights, or copyright for software that has a direct relationship to the project?', 'A', 1, 1, NULL, NULL, NULL, NULL, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (296, 295, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (297, 295, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (298, 295, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (301, 76, 1, 'C', 'State:', 'A', 3, 6, 'org.kuali.kra.bo.State', 'description', NULL, 1, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (302, 301, 'E', 'All 50 states including DC ', SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (303, 301, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (304, 301, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (305, 77, 1, 'C', 'Country:', 'A', 3, 6, 'org.kuali.kra.bo.Country', 'countryName', NULL, 1, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (306, 305, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (307, 305, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (308, 305, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (309, 78, 1, 'C', 'Start Date:', 'A', 3, 4, NULL, NULL, 1, 1, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (310, 309, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (311, 309, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (312, 309, 'P', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION (QUESTION_REF_ID, QUESTION_ID, SEQUENCE_NUMBER, SEQUENCE_STATUS, QUESTION, STATUS, GROUP_TYPE_CODE, QUESTION_TYPE_ID, LOOKUP_CLASS, LOOKUP_RETURN, DISPLAYED_ANSWERS, MAX_ANSWERS, ANSWER_MAX_LENGTH, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (313, 79, 1, 'C', 'End Date:', 'A', 3, 4, NULL, NULL, 1, 1, NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (314, 313, 'E', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (315, 313, 'R', NULL, SYSDATE, USER) ;

INSERT INTO QUESTION_EXPLANATION (QUESTION_EXPLANATION_ID, QUESTION_REF_ID_FK, EXPLANATION_TYPE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES (316, 313, 'P', NULL, SYSDATE, USER) ;

COMMIT;