INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(2, 1, 1, 1, 0, 'N', NULL, NULL, STR_TO_DATE('20091219160851','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(3, 1, 33, 2, 0, 'N', NULL, NULL, STR_TO_DATE('20091219160851','%Y%m%d%H%i%s'), 'quickstart', 2, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(4, 1, 85, 3, 0, 'N', NULL, NULL, STR_TO_DATE('20091219160851','%Y%m%d%H%i%s'), 'quickstart', 3, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(5, 1, 89, 4, 0, 'N', NULL, NULL, STR_TO_DATE('20091219160851','%Y%m%d%H%i%s'), 'quickstart', 4, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(6, 1, 301, 5, 0, 'N', NULL, NULL, STR_TO_DATE('20091219160851','%Y%m%d%H%i%s'), 'quickstart', 5, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(7, 1, 309, 6, 0, 'N', NULL, NULL, STR_TO_DATE('20091219160851','%Y%m%d%H%i%s'), 'quickstart', 6, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(8, 1, 9, 7, 1, 'N', '4', 'Y', STR_TO_DATE('20091219160851','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(9, 1, 33, 8, 1, 'N', '4', 'Y', STR_TO_DATE('20091219160851','%Y%m%d%H%i%s'), 'quickstart', 2, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(10, 1, 37, 9, 3, 'N', '8', '5', STR_TO_DATE('20091219160851','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(11, 1, 313, 10, 6, 'N', '11', '01/01/2010', STR_TO_DATE('20091219160851','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(12, 1, 69, 11, 7, 'N', '1', 'N', STR_TO_DATE('20091219160851','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(15, 14, 1, 1, 0, 'N', NULL, NULL, STR_TO_DATE('20091222084052','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(16, 14, 69, 2, 0, 'N', NULL, NULL, STR_TO_DATE('20091222084052','%Y%m%d%H%i%s'), 'quickstart', 2, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(17, 14, 17, 3, 2, 'Y', '1', 'GOOG', STR_TO_DATE('20091222084052','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(19, 18, 1, 1, 0, 'N', NULL, NULL, STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(20, 18, 33, 2, 0, 'N', NULL, NULL, STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 2, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(21, 18, 85, 3, 0, 'N', NULL, NULL, STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 3, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(22, 18, 89, 4, 0, 'N', NULL, NULL, STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 4, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(23, 18, 301, 5, 0, 'N', NULL, NULL, STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 5, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(24, 18, 309, 6, 0, 'N', NULL, NULL, STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 6, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(25, 18, 9, 7, 1, 'N', '4', 'Y', STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(26, 18, 33, 8, 1, 'N', '4', 'Y', STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 2, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(27, 18, 37, 9, 3, 'N', '8', '5', STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(28, 18, 305, 10, 5, 'Y', '4', 'Arizona', STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(29, 18, 313, 11, 6, 'N', '11', '01/01/2010', STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());


INSERT INTO QUESTIONNAIRE_QUESTIONS(QUESTIONNAIRE_QUESTIONS_ID, QUESTIONNAIRE_REF_ID_FK, QUESTION_REF_ID_FK, QUESTION_NUMBER, PARENT_QUESTION_NUMBER, CONDITION_FLAG, CONDITION_TYPE, CONDITION_VALUE, UPDATE_TIMESTAMP, UPDATE_USER, QUESTION_SEQ_NUMBER, VER_NBR, OBJ_ID) 
VALUES(30, 18, 69, 12, 7, 'N', '1', 'N', STR_TO_DATE('20091223141759','%Y%m%d%H%i%s'), 'quickstart', 1, 1, UUID());



