--
-- Kuali Coeus, a comprehensive research administration system for higher education.
-- 
-- Copyright 2005-2015 Kuali, Inc.
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as
-- published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
-- 
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
--

INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4091,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4092,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4092,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4093,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4093,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4094,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4094,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4095,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4095,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4096,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4096,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4097,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4097,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4098,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4098,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4099,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4099,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4100,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4100,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4101,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4101,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4101,'A',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4102,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4102,'B',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),'Award Hierarchy Sync Routed Document',1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4103,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4103,'B',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),'Award Hierarchy Sync Routed Document',1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4104,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4104,'B',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),'Award Hierarchy Sync Routed Document',1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4105,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4105,'B',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),'Award Hierarchy Sync Routed Document',1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4106,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4106,'B',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),'Award Hierarchy Sync Routed Document',1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4107,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4107,'B',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),'Award Hierarchy Sync Routed Document',1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4108,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4108,'B',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),'Award Hierarchy Sync Routed Document',1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4109,'S',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
INSERT INTO KREW_ACTN_TKN_T (ACTN_TKN_ID,DOC_HDR_ID,ACTN_CD,PRNCPL_ID,ANNOTN,DOC_VER_NBR,CUR_IND,ACTN_DT,VER_NBR) 
    VALUES (KREW_ACTN_TKN_S.NEXTVAL,4109,'C',(SELECT PRNCPL_ID FROM KRIM_PRNCPL_T WHERE PRNCPL_NM = 'quickstart'),null,1,1,SYSDATE,1)
/
