
INSERT INTO KRIM_PERM_T (PERM_ID, OBJ_ID, VER_NBR, PERM_TMPL_ID, NMSPC_CD, NM, DESC_TXT)
VALUES(KRIM_PERM_ID_BS_S.NEXTVAL, SYS_GUID(), 1, (SELECT PERM_TMPL_ID FROM KRIM_PERM_TMPL_T 
WHERE NM = 'Default' AND NMSPC_CD='KUALI'), 'KC-COIDISCLOSURE', 'View COI Undisclosed Events', 'View COI Undisclosed Events permission')
/

INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND)
VALUES (KRIM_ROLE_PERM_ID_BS_S.NEXTVAL, SYS_GUID(), 1, (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE 
ROLE_NM = 'COI Administrator' AND NMSPC_CD='KC-COIDISCLOSURE'), (SELECT PERM_ID FROM KRIM_PERM_T WHERE NM = 'View COI Undisclosed Events' AND NMSPC_CD='KC-COIDISCLOSURE'), 'Y')
/

