delimiter /
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Proposal Development Document - Initial Approval','Proposal Initial Approval','KC-WKFLW','9CD01DC99ECFDF6CE040DC0A1F8A7146','10000','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Proposal Development Document - OSP Office Approval','Proposal OSP Office Approval','KC-WKFLW','9CD01DC99ED0DF6CE040DC0A1F8A7146','10001','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Proposal Development Document - Key Personnel Approval','Proposal Persons Approval','KC-WKFLW','9CD01DC99ED1DF6CE040DC0A1F8A7146','10002','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Proposal Development Document - Custom Approval','Proposal Custom Approval','KC-WKFLW','9CD01DC99ED2DF6CE040DC0A1F8A7146','10003','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Proposal Development Document - Departmental Approval','Proposal Departmental Approval','KC-WKFLW','9CD01DC99ED3DF6CE040DC0A1F8A7146','10004','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Protocol Document - IRBApprove','IRB Approve','KC-WKFLW','9CD01DC99ED4DF6CE040DC0A1F8A7146','10005','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Protocol Document - AssignedToCommittee','IRB AssignedToCommittee','KC-WKFLW','9CD01DC99ED5DF6CE040DC0A1F8A7146','10006','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Protocol Document - AssignedToAgenda','IRB AssignedToAgenda','KC-WKFLW','9CD01DC99ED6DF6CE040DC0A1F8A7146','10007','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Protocol Document - IRBReview','IRB Review','KC-WKFLW','9CD01DC99ED7DF6CE040DC0A1F8A7146','10008','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Protocol Document - IRBReceipt','IRB Receipt','KC-WKFLW','9CD01DC99ED8DF6CE040DC0A1F8A7146','10009','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Award Budget Document - Initial Approval','Award Budget InitialApproval','KC-WKFLW','9CD01DC99ED9DF6CE040DC0A1F8A7146','10010','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Award Budget Document - OSP Approval','Award Budget OSPApproval','KC-WKFLW','9CD01DC99EDADF6CE040DC0A1F8A7146','10011','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Protocol Document - IRB Reviewer approves online review','IRB Reviewer Approve Online Review','KC-WKFLW','9CD01EC8DB1625C0E040DC0A1F8A7151','10012','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Protocol Online Review Document - IRB Admin approves online review','IRB Admin Approve Online Review','KC-WKFLW','9CD01EC8DB1725C0E040DC0A1F8A7151','10013','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','Protocol Online Review Document - IRB Admin approves online review request made by PI during protocol submission.','IRB Admin Approve Review Request','KC-WKFLW','9CD01EC8DB1825C0E040DC0A1F8A7151','10014','1',1)
/
INSERT INTO KRIM_RSP_T (ACTV_IND,DESC_TXT,NM,NMSPC_CD,OBJ_ID,RSP_ID,RSP_TMPL_ID,VER_NBR)
  VALUES ('Y','ProtocolUnitApprovalResponsibility','ProtocolUnitApprovalResponsibility','KC-WKFLW','9CD01EC8DB1925C0E040DC0A1F8A7151','10015','1',1)
/
delimiter ;