INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2005',TO_DATE('20040701','YYYYMMDD'),'F','000001',12,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2005',TO_DATE('20040701','YYYYMMDD'),'N','000001',12,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2006',TO_DATE('20050701','YYYYMMDD'),'F','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2006',TO_DATE('20050701','YYYYMMDD'),'N','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2007',TO_DATE('20060701','YYYYMMDD'),'F','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2007',TO_DATE('20060701','YYYYMMDD'),'N','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2008',TO_DATE('20070701','YYYYMMDD'),'F','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2008',TO_DATE('20070701','YYYYMMDD'),'N','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2009',TO_DATE('20080701','YYYYMMDD'),'F','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2009',TO_DATE('20080701','YYYYMMDD'),'N','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2010',TO_DATE('20090701','YYYYMMDD'),'F','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2010',TO_DATE('20090701','YYYYMMDD'),'N','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2011',TO_DATE('20100701','YYYYMMDD'),'F','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2011',TO_DATE('20100701','YYYYMMDD'),'N','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2012',TO_DATE('20110701','YYYYMMDD'),'F','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Salaries') AND DESCRIPTION = 'Lab Allocation - Salaries'),'2012',TO_DATE('20110701','YYYYMMDD'),'N','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2003',TO_DATE('20020701','YYYYMMDD'),'N','000001',3.6,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2005',TO_DATE('20040701','YYYYMMDD'),'F','000001',6,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2005',TO_DATE('20040701','YYYYMMDD'),'N','000001',6,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2006',TO_DATE('20050701','YYYYMMDD'),'F','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2006',TO_DATE('20050701','YYYYMMDD'),'N','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2007',TO_DATE('20060701','YYYYMMDD'),'F','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2007',TO_DATE('20060701','YYYYMMDD'),'N','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2008',TO_DATE('20070701','YYYYMMDD'),'F','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2008',TO_DATE('20070701','YYYYMMDD'),'N','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2009',TO_DATE('20080701','YYYYMMDD'),'F','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2009',TO_DATE('20080701','YYYYMMDD'),'N','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2010',TO_DATE('20090701','YYYYMMDD'),'F','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2010',TO_DATE('20090701','YYYYMMDD'),'N','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2011',TO_DATE('20100701','YYYYMMDD'),'F','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - M&S') AND DESCRIPTION = 'Lab Allocation - M&S'),'2011',TO_DATE('20100701','YYYYMMDD'),'N','000001',1,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Utilities'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Utilities') AND DESCRIPTION = 'Lab Allocation - Utilities'),'2003',TO_DATE('20020701','YYYYMMDD'),'F','000001',0,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Utilities'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Utilities') AND DESCRIPTION = 'Lab Allocation - Utilities'),'2005',TO_DATE('20040701','YYYYMMDD'),'F','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO INSTITUTE_LA_RATES (RATE_CLASS_CODE,RATE_TYPE_CODE,FISCAL_YEAR,START_DATE,ON_OFF_CAMPUS_FLAG,UNIT_NUMBER,RATE,ACTIVE_FLAG,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ((SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Utilities'),(SELECT RATE_TYPE_CODE FROM RATE_TYPE WHERE RATE_CLASS_CODE = (SELECT RATE_CLASS_CODE FROM RATE_CLASS WHERE DESCRIPTION = 'Lab Allocation - Utilities') AND DESCRIPTION = 'Lab Allocation - Utilities'),'2005',TO_DATE('20040701','YYYYMMDD'),'N','000001',8,'Y','admin',SYSDATE,SYS_GUID(),1)
/
