INSERT INTO SEQ_VALID_SUBM_REVW_TYPE_QUAL VALUES (NULL);

INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (VALID_PROTO_SUB_TYPE_QUAL_ID, SUBMISSION_TYPE_CODE, SUBMISSION_TYPE_QUAL_CODE, UPDATE_TIMESTAMP, UPDATE_USER ) 
SELECT MAX(ID), 112, 1, NOW(), 'KRADEV' FROM SEQ_VALID_SUBM_REVW_TYPE_QUAL;

INSERT INTO SEQ_VALID_SUBM_REVW_TYPE_QUAL VALUES (NULL);

INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (VALID_PROTO_SUB_TYPE_QUAL_ID, SUBMISSION_TYPE_CODE, SUBMISSION_TYPE_QUAL_CODE, UPDATE_TIMESTAMP, UPDATE_USER ) 
SELECT MAX(ID), 112, 8, NOW(), 'KRADEV' FROM SEQ_VALID_SUBM_REVW_TYPE_QUAL;

INSERT INTO SEQ_VALID_SUBM_REVW_TYPE_QUAL VALUES (NULL);

INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (VALID_PROTO_SUB_TYPE_QUAL_ID, SUBMISSION_TYPE_CODE, SUBMISSION_TYPE_QUAL_CODE, UPDATE_TIMESTAMP, UPDATE_USER ) 
SELECT MAX(ID), 112, 9, NOW(), 'KRADEV' FROM SEQ_VALID_SUBM_REVW_TYPE_QUAL;

INSERT INTO SEQ_VALID_SUBM_REVW_TYPE_QUAL VALUES (NULL);

INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (VALID_PROTO_SUB_TYPE_QUAL_ID, SUBMISSION_TYPE_CODE, SUBMISSION_TYPE_QUAL_CODE, UPDATE_TIMESTAMP, UPDATE_USER ) 
SELECT MAX(ID), 112, 12, NOW(), 'KRADEV' FROM SEQ_VALID_SUBM_REVW_TYPE_QUAL;

INSERT INTO SEQ_VALID_SUBM_REVW_TYPE_QUAL VALUES (NULL);

INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (VALID_PROTO_SUB_TYPE_QUAL_ID, SUBMISSION_TYPE_CODE, SUBMISSION_TYPE_QUAL_CODE, UPDATE_TIMESTAMP, UPDATE_USER ) 
SELECT MAX(ID), 112, 13, NOW(), 'KRADEV' FROM SEQ_VALID_SUBM_REVW_TYPE_QUAL;

INSERT INTO SEQ_VALID_SUBM_REVW_TYPE_QUAL VALUES (NULL);

INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (VALID_PROTO_SUB_TYPE_QUAL_ID, SUBMISSION_TYPE_CODE, SUBMISSION_TYPE_QUAL_CODE, UPDATE_TIMESTAMP, UPDATE_USER ) 
SELECT MAX(ID), 112, 2, NOW(), 'KRADEV' FROM SEQ_VALID_SUBM_REVW_TYPE_QUAL;

INSERT INTO SEQ_VALID_SUBM_REVW_TYPE_QUAL VALUES (NULL);

INSERT INTO VALID_PROTO_SUB_TYPE_QUAL (VALID_PROTO_SUB_TYPE_QUAL_ID, SUBMISSION_TYPE_CODE, SUBMISSION_TYPE_QUAL_CODE, UPDATE_TIMESTAMP, UPDATE_USER ) 
SELECT MAX(ID), 112, 3, NOW(), 'KRADEV' FROM SEQ_VALID_SUBM_REVW_TYPE_QUAL;

COMMIT;