DELIMITER /

ALTER TABLE COI_DISCLOSURE ADD REVIEW_STATUS_CODE VARCHAR(3)
/

ALTER TABLE COI_DISCLOSURE
	ADD CONSTRAINT UQ_COI_DISCLOSURE UNIQUE (COI_DISCLOSURE_NUMBER, SEQUENCE_NUMBER)
/

DELIMITER ;
