--
-- Kuali Coeus, a comprehensive research administration system for higher education.
-- 
-- Copyright 2005-2015 Kuali, Inc.
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as
-- published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
-- 
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
--

INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 1, 'Approval Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 2, 'Adverse Event Notification Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 3, 'Agenda', sysdate, 'admin', 'Y', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 4, 'Minutes', sysdate, 'admin', 'Y', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 5, 'Adverse Event Reporting Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 6, 'Ammendment Approval letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 7, 'Approval Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 8, 'Approval Withheld Pending Clarification Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 9, 'Continuation Approval Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 10, 'Correspondent Action Notification', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 11, 'Deactivated Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 12, 'Disapproval Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 13, 'Expiration Notification Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 14, 'Expired Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 15, 'Failed Administrative PreReview', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 16, 'Hold Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 17, 'Lift Hold Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 18, 'Notification of Administrative Correction', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 19, 'Notification of Deactivation', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 20, 'Notification Of Iacuc Review Comp', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 21, 'Notified Committee Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 22, 'Notify IACUC Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 23, 'Over Usage Of Animals', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 24, 'Renewal Reminder Notification', sysdate, 'admin', 'Y', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 25, 'Request To Deactivate Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 26, 'Suspension Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 27, 'Tabled Deferral Notification Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 28, 'Termination Letter', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 29, 'Withdrawal Confirmation Notification', sysdate, 'admin', 'P', SYS_GUID(), 1 ) 
/
