/* Foreign Key Constraint(s) */ 
ALTER TABLE PROTOCOL_ONLN_RVWS 
    ADD CONSTRAINT FK6_PROTOCOL_ONLN_RVW_DOCUMENT FOREIGN KEY (DOCUMENT_NUMBER) 
                REFERENCES PROTOCOL_ONLN_RVW_DOCUMENT (DOCUMENT_NUMBER) ;
                