\. MYSQL/DML/KR_DML_BS1_KRIM_ID_CLEAN.sql
\. MYSQL/DML/KR_DML_BS2_KRIM_ID_CLEAN.sql
\. MYSQL/DML/KR_DML_BS3_KRIM_PERM_T.sql
\. MYSQL/DML/KR_DML_BS4_KRIM_PERM_ATTR_DATA_T.sql
\. MYSQL/DML/KR_DML_BS4_KRIM_ROLE_T.sql
\. MYSQL/DML/KR_DML_BS5_KRIM_ROLE_PERM_T.sql
\. MYSQL/DML/KR_DML_BS7_KREW_DOC_HDR_T.sql
\. MYSQL/DML/KR_DML_BS7_KRNS_PARM_T.sql
\. MYSQL/DML/KR_DML_BS8_KREW_ACTN_TKN_T.sql
\. MYSQL/DML/KR_DML_BS8_KREW_DOC_HDR_CNTNT_T.sql
\. MYSQL/DML/KR_DML_BS8_KREW_RTE_NODE_INSTN_T.sql
\. MYSQL/DML/KR_DML_BS9_KREW_ACTN_RQST_T.sql
commit;
