DELIMITER /
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '001', 'General Info', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '002', 'Protocol Personnel', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '004', 'Areas of Research', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '006', 'Subjects', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '007', 'Special Review', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '008', 'Add/Modify Attachments', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '016', 'Protocol References', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '017', 'Protocol Organizations', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '023', 'Others', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '024', 'Funding Source', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '025', 'Protocol Permissions', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '026', 'Questionnaire', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '031', 'Procedures', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '032', 'Species/Groups', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '033', 'Exceptions', NOW(), 'admin', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_MODULES (PROTOCOL_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, OBJ_ID, VER_NBR ) 
VALUES ( '036', 'Three Rs', NOW(), 'admin', UUID(), 1 ) 
/
DELIMITER ;
