DELIMITER /
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 1, 'Approval Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 2, 'Adverse Event Notification Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 3, 'Agenda', NOW(), 'admin', 'Y', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 4, 'Minutes', NOW(), 'admin', 'Y', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 5, 'Adverse Event Reporting Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 6, 'Ammendment Approval letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 7, 'Approval Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 8, 'Approval Withheld Pending Clarification Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 9, 'Continuation Approval Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 10, 'Correspondent Action Notification', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 11, 'Deactivated Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 12, 'Disapproval Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 13, 'Expiration Notification Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 14, 'Expired Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 15, 'Failed Administrative PreReview', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 16, 'Hold Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 17, 'Lift Hold Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 18, 'Notification of Administrative Correction', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 19, 'Notification of Deactivation', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 20, 'Notification Of Iacuc Review Comp', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 21, 'Notified Committee Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 22, 'Notify IACUC Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 23, 'Over Usage Of Animals', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 24, 'Renewal Reminder Notification', NOW(), 'admin', 'Y', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 25, 'Request To Deactivate Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 26, 'Suspension Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 27, 'Tabled Deferral Notification Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 28, 'Termination Letter', NOW(), 'admin', 'P', UUID(), 1 ) 
/
INSERT INTO IACUC_PROTOCOL_CORRESP_TYPE ( PROTO_CORRESP_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, MODULE_ID, OBJ_ID, VER_NBR ) 
VALUES ( 29, 'Withdrawal Confirmation Notification', NOW(), 'admin', 'P', UUID(), 1 ) 
/
DELIMITER ;
