-- View for Coeus compatibility 
CREATE OR REPLACE VIEW OSP$PROP_UNIT_ADMINISTRATORS AS SELECT 
    PROPOSAL_NUMBER, 
    SEQUENCE_NUMBER, 
    UNIT_ADMINISTRATOR_TYPE_CODE, 
    ADMINISTRATOR, 
    UPDATE_TIMESTAMP, 
    UPDATE_USER
FROM PROP_UNIT_ADMINISTRATORS;
