-- View for Coeus compatibility 
CREATE OR REPLACE VIEW OSP$PROPOSAL_CUSTOM_DATA AS SELECT 
	PROPOSAL_NUMBER,        
	SEQUENCE_NUMBER,        
	CA.NAME COLUMN_NAME,            
	PCD.VALUE COLUMN_VALUE,           
	PCD.UPDATE_TIMESTAMP UPDATE_TIMESTAMP,       
	PCD.UPDATE_USER UPDATE_USER            
FROM PROPOSAL_CUSTOM_DATA PCD, CUSTOM_ATTRIBUTE CA
WHERE PCD.CUSTOM_ATTRIBUTE_ID = CA.ID;
