-- View for Coeus compatibility 
CREATE OR REPLACE VIEW OSP$QUESTION_EXPLANATION AS SELECT 
    QUESTION_ID, 
    EXPLANATION_TYPE, 
    EXPLANATION, 
    UPDATE_TIMESTAMP, 
    UPDATE_USER
FROM QUESTION_EXPLANATION;
