INSERT INTO KRIM_PERM_ID_S VALUES (NULL);

INSERT INTO KRIM_PERM_T (PERM_ID, PERM_TMPL_ID, NMSPC_CD, NM, DESC_TXT, ACTV_IND, VER_NBR, OBJ_ID) 
SELECT MAX(ID), (SELECT PERM_TMPL_ID FROM KRIM_PERM_TMPL_T WHERE NM = 'Populate Group' AND NMSPC_CD = 'KR-IDM'), 'KC-SYS', 'Populate KC Groups', 'Authorizes users to modify the information on the Assignees Tab of the Group Document and the Group section of the Membership Tab on the Person Document for groups with namespaces beginning with KC.','Y',1,UUID() FROM KRIM_PERM_ID_S;

INSERT INTO KRIM_ATTR_DATA_ID_S VALUES (NULL);

INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID, PERM_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL, VER_NBR, OBJ_ID) 
SELECT MAX(ID), (SELECT PERM_ID FROM KRIM_PERM_T WHERE NM = 'Populate KC Groups' AND NMSPC_CD = 'KC-SYS'), (SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM = 'Group' AND NMSPC_CD = 'KR-IDM'), (SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NM = 'namespaceCode' AND NMSPC_CD = 'KR-NS'), 'KC*', 1, UUID() FROM KRIM_ATTR_DATA_ID_S; 

INSERT INTO KRIM_ROLE_PERM_ID_S VALUES (NULL);

INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, ROLE_ID, PERM_ID, ACTV_IND, VER_NBR, OBJ_ID) 
SELECT MAX(ID), (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM = 'Manager' AND NMSPC_CD = 'KC-SYS'), (SELECT PERM_ID FROM KRIM_PERM_T WHERE NM = 'Populate KC Groups' AND NMSPC_CD = 'KC-SYS'), 'Y', 1, UUID() FROM KRIM_ROLE_PERM_ID_S;

INSERT INTO KRIM_ROLE_PERM_ID_S VALUES (NULL);

INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, ROLE_ID, PERM_ID, ACTV_IND, VER_NBR, OBJ_ID) 
SELECT MAX(ID), (SELECT ROLE_ID FROM KRIM_ROLE_T WHERE ROLE_NM = 'Technical Administrator' AND NMSPC_CD = 'KC-SYS'), (SELECT PERM_ID FROM KRIM_PERM_T WHERE NM = 'Populate KC Groups' AND NMSPC_CD = 'KC-SYS'), 'Y', 1, UUID() FROM KRIM_ROLE_PERM_ID_S;

COMMIT;