CREATE TABLE IACUC_PERSON_TRAINING ( 
    IACUC_PERSON_TRAINING_ID NUMBER(12,0) NOT NULL, 
    PERSON_TRAINING_ID NUMBER(12,0) NOT NULL, 
    PERSON_ID VARCHAR2(40) NOT NULL, 
    SPECIES_CODE NUMBER(4,0) NOT NULL, 
    PROCEDURE_CODE NUMBER(4,0) NOT NULL, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2(60) NOT NULL, 
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2(36) NOT NULL) 
/


ALTER TABLE IACUC_PERSON_TRAINING 
ADD CONSTRAINT PK_IACUC_PERSON_TRAINING 
PRIMARY KEY (IACUC_PERSON_TRAINING_ID) 
/

