CREATE TABLE IACUC_PROTOCOL_STUDY_GROUP_DTL ( 
    IACUC_PROTO_STUDY_GRP_DTL_ID NUMBER(12,0) NOT NULL, 
    IACUC_PROTO_STUDY_GRP_HDR_ID NUMBER(12,0) NOT NULL, 
    SPECIES_CODE NUMBER(4) NOT NULL,
    MAX_PAIN_CATEGORY_CODE NUMBER(3,0) NOT NULL, 
    TOTAL_SPECIES_COUNT NUMBER(12,0) NOT NULL, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2(60) NOT NULL, 
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2(36) NOT NULL) 
/


ALTER TABLE IACUC_PROTOCOL_STUDY_GROUP_DTL 
ADD CONSTRAINT PK_IACUC_PROTO_STUDY_GROUP_DTL 
PRIMARY KEY (IACUC_PROTO_STUDY_GRP_DTL_ID) 
/
