TRUNCATE TABLE REPORT_CLASS DROP STORAGE
/
INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE,DESCRIPTION,GENERATE_REPORT_REQUIREMENTS,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','Financial','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE,DESCRIPTION,GENERATE_REPORT_REQUIREMENTS,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','Property','y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE,DESCRIPTION,GENERATE_REPORT_REQUIREMENTS,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('3','Intellectual Property','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE,DESCRIPTION,GENERATE_REPORT_REQUIREMENTS,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('4','Technical/Management','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE,DESCRIPTION,GENERATE_REPORT_REQUIREMENTS,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('5','Procurement','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE,DESCRIPTION,GENERATE_REPORT_REQUIREMENTS,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('6','Payment/Invoice','Y','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO REPORT_CLASS (REPORT_CLASS_CODE,DESCRIPTION,GENERATE_REPORT_REQUIREMENTS,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('7','Proposals Due','Y','admin',SYSDATE,SYS_GUID(),1)
/
