--
-- Kuali Coeus, a comprehensive research administration system for higher education.
-- 
-- Copyright 2005-2015 Kuali, Inc.
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as
-- published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
-- 
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
--

TRUNCATE TABLE BUDGET_CATEGORY_MAPPING DROP STORAGE
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','04',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Subcontracts'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Other'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Human Subjects'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Vertebrate Animals'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Publication Costs/Documentation/Dissemenation'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Duplicating'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Telephone, Fax'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Equipment Rental'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Service Agreement(s)'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Communications/Marketing'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Software'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Computer Time'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Meeting Costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Other Operating Expenses'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Travel'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Stipends'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','40',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Alteration and Renovations'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','41',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Inpatient Care Costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','42',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Equipment'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','43',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Materials '),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','43',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Postage'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','73',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Travel - Domestic'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','73',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Travel - Foreign'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','81',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Professional Services/Consultant'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NIH_PRINTING','90',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Outpatient costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','01',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Senior Personnel'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','01-Graduates',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Graduate Students'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','01-Other',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Other Personnel'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','01-Other Profs',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Other Professionals'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','01-PostDocs',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Postdoctoral'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','01-Secretarial',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Project Support Staff'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','01-Undergrads',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Undergraduate Students'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','04',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Subcontracts'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Human Subjects'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Vertebrate Animals'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Alteration and Renovations'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Inpatient Care Costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Duplicating'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Telephone, Fax'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Equipment Rental'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Service Agreement(s)'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Communications/Marketing'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Meeting Costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Other Operating Expenses'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Outpatient costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','42',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Equipment'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','43',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Materials '),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','43',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Postage'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','73',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Travel - Domestic'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','74',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Travel - Foreign'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','75',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Stipends'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','77',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Travel'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','78',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Other'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','80',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Publication Costs/Documentation/Dissemenation'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','81',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Professional Services/Consultant'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','82',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Software'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_194','82',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Computer Time'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','01',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Senior Personnel'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','01-Graduates',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Graduate Students'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','01-Other',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Other Personnel'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','01-Other Profs',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Other Professionals'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','01-PostDocs',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Postdoctoral'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','01-Secretarial',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Project Support Staff'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','01-Undergrads',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Undergraduate Students'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','04',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Subcontracts'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Human Subjects'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Vertebrate Animals'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Alteration and Renovations'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Inpatient Care Costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Duplicating'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Telephone, Fax'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Equipment Rental'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Service Agreement(s)'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Communications/Marketing'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Meeting Costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Other Operating Expenses'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Outpatient costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Tuition'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','42',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Equipment'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','43',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Materials '),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','43',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Postage'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','73',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Travel - Domestic'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','74',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Travel - Foreign'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','75',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Stipends'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','77',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Travel'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','78',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Other'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','79',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Subsistence'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','80',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Publication Costs/Documentation/Dissemenation'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','81',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Professional Services/Consultant'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','82',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Software'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('NSF_PRINTING','82',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Computer Time'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','01',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Senior Personnel'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','01-Graduates',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Graduate Students'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','01-Other',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Other Personnel'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','01-Other Profs',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Other Professionals'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','01-PostDocs',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Postdoctoral'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','01-Secretarial',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Project Support Staff'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','01-Undergrads',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Undergraduate Students'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','04',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Subcontracts'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Human Subjects'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Vertebrate Animals'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Inpatient Care Costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Duplicating'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Telephone, Fax'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Service Agreement(s)'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Communications/Marketing'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Software'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Meeting Costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Other Operating Expenses'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','39',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Outpatient costs'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','40',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Alteration and Renovations'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','42',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Equipment'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','43',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Materials '),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','43',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Postage'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','45',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Equipment Rental'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','73',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Travel - Domestic'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','74',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Travel - Foreign'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','75',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Stipends'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','76',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Tuition'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','77',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Travel'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','78',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Other'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','79',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Trainee/Participant Costs - Subsistence'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','80',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Publication Costs/Documentation/Dissemenation'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','81',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Professional Services/Consultant'),'admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO BUDGET_CATEGORY_MAPPING (MAPPING_NAME,TARGET_CATEGORY_CODE,COEUS_CATEGORY_CODE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('S2S','82',(SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY WHERE DESCRIPTION = 'Computer Time'),'admin',SYSDATE,SYS_GUID(),1)
/
