TRUNCATE TABLE AWARD_TYPE DROP STORAGE
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (1,'Grant','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (2,'NIH Training Grant ','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (3,'Contract','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (4,'Indefinite Delivery Contract ','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (5,'Cooperative Agreement','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (6,'Facilities Agreement','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (7,'Fellowship','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (8,'Consortium Membership','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (9,'Other Transaction Agreement','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (10,'Student Financial Aid','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (11,'Gift','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (12,'Consortium Expenditures','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES (13,'Budget Office WBS','admin',SYSDATE,SYS_GUID(),1)
/
