TRUNCATE TABLE COMM_MEMBERSHIP_TYPE DROP STORAGE
/
INSERT INTO COMM_MEMBERSHIP_TYPE (MEMBERSHIP_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('1','Voting member','admin',SYSDATE,SYS_GUID(),1)
/
INSERT INTO COMM_MEMBERSHIP_TYPE (MEMBERSHIP_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('2','Non-voting member','admin',SYSDATE,SYS_GUID(),1)
/
