INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(1, 'Administrative Amendment', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(2, 'Allotment (Increment)', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(3, 'Continuation (Amendment)', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(4, 'Correction', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(5, 'Date Change', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(6, 'Deobligation', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(7, 'F&A Rate Change', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(8, 'Investigator Change', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(9, 'New', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(10, 'No Cost Extension', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(11, 'Restriction Change', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(12, 'Subaward Change', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(13, 'Supplement', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(14, 'Suspension (Stop Work Order)', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(15, 'Unit Change', SYSDATE, USER, 'Y') ;

INSERT INTO AWARD_TRANSACTION_TYPE (AWARD_TRANSACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, SHOW_IN_ACTION_SUMMARY)
VALUES(16, 'Termination', SYSDATE, USER, 'Y') ;
COMMIT;