/*Load Script For FREQUENCY_BASE Table*/ 
INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES ('2', 'Project Start Date', SYSDATE, USER) ;

INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES ('6', 'As Required', SYSDATE, USER) ;

INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES ('4', 'Project End Date', SYSDATE, USER) ;

INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES ('1', 'Execution Date', SYSDATE, USER) ;

INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES ('3', 'Obligation End Date', SYSDATE, USER) ;

INSERT INTO FREQUENCY_BASE (FREQUENCY_BASE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES ('5', 'Obligation Start Date', SYSDATE, USER) ;

COMMIT;