UPDATE unit_administrator_type 
SET DEFAULT_GROUP_FLAG='C', 
    MULTIPLES_FLAG='N' 
WHERE UNIT_ADMINISTRATOR_TYPE_CODE = '1';

UPDATE unit_administrator_type 
SET DEFAULT_GROUP_FLAG='C', 
    MULTIPLES_FLAG='Y' 
WHERE UNIT_ADMINISTRATOR_TYPE_CODE = '2';

UPDATE unit_administrator_type 
SET DEFAULT_GROUP_FLAG='U', 
    MULTIPLES_FLAG='N' 
WHERE UNIT_ADMINISTRATOR_TYPE_CODE = '3';

UPDATE unit_administrator_type 
SET DEFAULT_GROUP_FLAG='U', 
    MULTIPLES_FLAG='N' 
WHERE UNIT_ADMINISTRATOR_TYPE_CODE = '4';

UPDATE unit_administrator_type 
SET DEFAULT_GROUP_FLAG='U', 
    MULTIPLES_FLAG='Y' 
WHERE UNIT_ADMINISTRATOR_TYPE_CODE = '5';

INSERT INTO unit_administrator_type (UNIT_ADMINISTRATOR_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, DEFAULT_GROUP_FLAG, MULTIPLES_FLAG)
VALUES('6', 'Grants.Gov Proposal Contact', SYSDATE, USER, 'N', 'N') ;

INSERT INTO unit_administrator_type (UNIT_ADMINISTRATOR_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, DEFAULT_GROUP_FLAG, MULTIPLES_FLAG)
VALUES('7', 'Administrative Contact', SYSDATE, USER, 'U', 'Y') ;

INSERT INTO unit_administrator_type (UNIT_ADMINISTRATOR_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, DEFAULT_GROUP_FLAG, MULTIPLES_FLAG)
VALUES('8', 'Financial Contact', SYSDATE, USER, 'U', 'N') ;

COMMIT;