DELIMITER /
ALTER TABLE COI_DISCLOSURE_PERSON_UNITS 
ADD CONSTRAINT FK_COI_DISCLOSURE_PERSON 
FOREIGN KEY (COI_DISCLOSURE_PERSON_ID) 
REFERENCES COI_DISCLOSURE_PERSON (COI_DISCLOSURE_PERSON_ID)
/
DELIMITER ;
