INSERT INTO KRIM_TYP_ATTR_ID_S VALUES (NULL);

INSERT INTO KRIM_TYP_ATTR_T (KIM_TYP_ATTR_ID, OBJ_ID, VER_NBR, SORT_CD, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ACTV_IND) VALUES 
SELECT MAX(ID), UUID(), 1, 'A', 
(SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM = 'Derived Role - Unit Administrator' AND NMSPC_CD = 'KC-WKFLW'), 
(SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NM = 'unitNumber' AND NMSPC_CD = 'KC-SYS'), 'Y' 
FROM KRIM_TYP_ATTR_ID_S;

COMMIT;