INSERT INTO KRIM_RSP_ATTR_DATA_T ( ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL )
VALUES ( 1406, UUID(), 1, 1035, 7, 13, 'ProtocolOnlineReviewDocument');

INSERT INTO KRIM_RSP_ATTR_DATA_T ( ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL )
VALUES ( 1407, UUID(), 1, 1035, 7, 16, 'OnlineReviewer');

INSERT INTO KRIM_RSP_ATTR_DATA_T ( ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL )
VALUES ( 1408, UUID(), 1, 1035, 7, 40, 'false');

INSERT INTO KRIM_RSP_ATTR_DATA_T ( ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL )
VALUES ( 1409, UUID(), 1, 1035, 7, 41, 'false');

COMMIT;