INSERT INTO WATERMARK (WATERMARK_ID, STATUS_CODE, WATERMARK_TEXT, WATERMARK_STATUS, FONT_SIZE, FONT_COLOUR, UPDATE_TIMESTAMP, VER_NBR, OBJ_ID, UPDATE_USER, WATERMARK_TYPE)
VALUES (SEQ_WATERMARK_ID.NEXTVAL, '-1', 'INVALID', 'Y', '50', 'RED', SYSDATE, 0, SYS_GUID(),'admin','TEXT')
/
commit
/
