DELIMITER /
ALTER TABLE KC_KRMS_TERM_FUN_PARAM 
ADD CONSTRAINT FK_KC_KRMS_TERM_FUN_PARAM 
FOREIGN KEY (KC_KRMS_TERM_FUNCTION_ID) 
REFERENCES KC_KRMS_TERM_FUNCTION (KC_KRMS_TERM_FUNCTION_ID)
/
DELIMITER ;
