--
-- Kuali Coeus, a comprehensive research administration system for higher education.
-- 
-- Copyright 2005-2015 Kuali, Inc.
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as
-- published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
-- 
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
--

DELIMITER /
INSERT INTO SEQ_COMMITTEE_ID VALUES(NULL)
/
INSERT INTO COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,MEMBERSHIP_TYPE_CODE,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM SEQ_COMMITTEE_ID),(SELECT ID FROM COMMITTEE WHERE COMMITTEE_NAME = 'KC IRB 1'),'10000000059',null,'Roger Rabbit','0',(SELECT MEMBERSHIP_TYPE_CODE FROM COMM_MEMBERSHIP_TYPE WHERE DESCRIPTION = 'Voting member'),'N',STR_TO_DATE('20010701','%Y%m%d'),STR_TO_DATE('20100701','%Y%m%d'),'','','','quickstart',NOW(),UUID(),0)
/
INSERT INTO SEQ_COMMITTEE_ID VALUES(NULL)
/
INSERT INTO COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,MEMBERSHIP_TYPE_CODE,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM SEQ_COMMITTEE_ID),(SELECT ID FROM COMMITTEE WHERE COMMITTEE_NAME = 'KC IRB 1'),'10000000008',null,'Allyson Cate','0',(SELECT MEMBERSHIP_TYPE_CODE FROM COMM_MEMBERSHIP_TYPE WHERE DESCRIPTION = 'Voting member'),'N',STR_TO_DATE('20080101','%Y%m%d'),STR_TO_DATE('20150701','%Y%m%d'),'','','','quickstart',NOW(),UUID(),0)
/
INSERT INTO SEQ_COMMITTEE_ID VALUES(NULL)
/
INSERT INTO COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,MEMBERSHIP_TYPE_CODE,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM SEQ_COMMITTEE_ID),(SELECT ID FROM COMMITTEE WHERE COMMITTEE_NAME = 'KC IRB 1'),'10000000005',null,'Inez Chew','0',(SELECT MEMBERSHIP_TYPE_CODE FROM COMM_MEMBERSHIP_TYPE WHERE DESCRIPTION = 'Voting member'),'N',STR_TO_DATE('20100701','%Y%m%d'),STR_TO_DATE('20150701','%Y%m%d'),'','Send e-mail','Is trained','quickstart',NOW(),UUID(),0)
/
INSERT INTO SEQ_COMMITTEE_ID VALUES(NULL)
/
INSERT INTO COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,MEMBERSHIP_TYPE_CODE,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM SEQ_COMMITTEE_ID),(SELECT ID FROM COMMITTEE WHERE COMMITTEE_NAME = 'KC IRB 1'),'10000000004',null,'Nicholas Majors','0',(SELECT MEMBERSHIP_TYPE_CODE FROM COMM_MEMBERSHIP_TYPE WHERE DESCRIPTION = 'Non-voting member'),'Y',STR_TO_DATE('20100701','%Y%m%d'),STR_TO_DATE('20150701','%Y%m%d'),'','','Non Voting Training only','quickstart',NOW(),UUID(),0)
/
INSERT INTO SEQ_COMMITTEE_ID VALUES(NULL)
/
INSERT INTO COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,MEMBERSHIP_TYPE_CODE,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM SEQ_COMMITTEE_ID),(SELECT ID FROM COMMITTEE WHERE COMMITTEE_NAME = 'KC IRB 1'),'10000000002',null,'Joe Tester','0',(SELECT MEMBERSHIP_TYPE_CODE FROM COMM_MEMBERSHIP_TYPE WHERE DESCRIPTION = 'Voting member'),'Y',STR_TO_DATE('20100701','%Y%m%d'),STR_TO_DATE('20150701','%Y%m%d'),'','No Email','','quickstart',NOW(),UUID(),0)
/
INSERT INTO SEQ_COMMITTEE_ID VALUES(NULL)
/
INSERT INTO COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,MEMBERSHIP_TYPE_CODE,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM SEQ_COMMITTEE_ID),(SELECT ID FROM COMMITTEE WHERE COMMITTEE_NAME = 'KC IRB 1'),'10000000006',null,'Della Woods','0',(SELECT MEMBERSHIP_TYPE_CODE FROM COMM_MEMBERSHIP_TYPE WHERE DESCRIPTION = 'Voting member'),'N',STR_TO_DATE('20100701','%Y%m%d'),STR_TO_DATE('20150701','%Y%m%d'),'','','','quickstart',NOW(),UUID(),0)
/
INSERT INTO SEQ_COMMITTEE_ID VALUES(NULL)
/
INSERT INTO COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,MEMBERSHIP_TYPE_CODE,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
VALUES ((SELECT (MAX(ID)) FROM SEQ_COMMITTEE_ID),(SELECT ID FROM COMMITTEE WHERE COMMITTEE_NAME = 'KC IRB 1'),'10000000007',null,'Opal Blood','0',(SELECT MEMBERSHIP_TYPE_CODE FROM COMM_MEMBERSHIP_TYPE WHERE DESCRIPTION = 'Voting member'),'N',STR_TO_DATE('20100701','%Y%m%d'),STR_TO_DATE('20150701','%Y%m%d'),'','','','quickstart',NOW(),UUID(),0)
/
DELIMITER ;
