--
-- Kuali Coeus, a comprehensive research administration system for higher education.
-- 
-- Copyright 2005-2015 Kuali, Inc.
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as
-- published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
-- 
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
--

DELIMITER /
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA001','CHAIRMAN OF THE CORPORATION','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA003','PRESIDENT','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA004','PROVOST','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA005','CHANCELLOR','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA006','DEAN / ADMINISTRATION','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA007','VICE PRESIDENT','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA008','ASSOCIATE DEAN','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA014','ASSOCIATE PROVOST','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA017','TREASURER','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA019','DIRECTOR OF LIBRARIES','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA022','VICE PRESIDENT / FACULTY','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA023','DEAN / FACULTY','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA025','EXECUTIVE VICE PRESIDENT','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA037','SECRETARY OF THE CORPORATION','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA040','MEDICAL DIRECTOR AND HEAD, M I T MEDICAL DEPT','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA042','PRESIDENT EMERITUS AND FORMER CHAIRMAN OF THE CORP','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA043','VICE PRESIDENT AND DEAN FOR RESEARCH','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA047','DEAN FOR GRADUATE STUDENTS','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA048','VICE PRESIDENT FOR FEDERAL RELATIONS','admin',NOW(),UUID(),1)
/
INSERT INTO JOB_CODE (JOB_CODE,JOB_TITLE,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) 
    VALUES ('AA049','CO-CHAIRPERSON OF THE COUNCIL ON FACULTY DIVERSITY','admin',NOW(),UUID(),1)
/
DELIMITER ;
