--
-- Kuali Coeus, a comprehensive research administration system for higher education.
-- 
-- Copyright 2005-2015 Kuali, Inc.
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as
-- published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
-- 
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
--

insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Undergraduates',0,7896,to_date('22-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());

insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Undergraduates',1,11064,to_date('09-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Predoctoral',0,20976,to_date('09-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',0,37368,to_date('09-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',1,39360,to_date('09-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',2,42204,to_date('09-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',3,43860,to_date('09-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',4,45504,to_date('09-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',5,47460,to_date('09-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',6,49344,to_date('09-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',7,51552,to_date('09-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Undergraduates',0,7896,to_date('16-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Undergraduates',1,11064,to_date('16-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Predoctoral',0,20976,to_date('16-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',0,37368,to_date('16-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',1,39360,to_date('16-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',2,42204,to_date('16-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',3,43860,to_date('16-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',4,45504,to_date('16-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',5,47460,to_date('16-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',6,49344,to_date('16-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',7,51552,to_date('16-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Undergraduates',13,12345,to_date('22-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Undergraduates',11,12345,to_date('22-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Undergraduates',1,12345,to_date('21-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Postdoctoral',5,5555,to_date('01-JAN-10','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Predoctoral',5,55555,to_date('01-JAN-10','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Undergraduates',11,5555555,to_date('01-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());
insert into TRAINING_STIPEND_RATES (TRAINING_STIPEND_RATES_ID,CAREER_LEVEL,EXPERIENCE_LEVEL,STIPEND_RATE,EFFECTIVE_DATE,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) values (SEQ_TRAINING_STIPEND_RATES_ID.nextval,'Undergraduates',12,12345,to_date('22-DEC-09','DD-MON-RR'),sysdate,'admin',SYS_GUID());

commit;
