UPDATE KRNS_PARM_DTL_TYP_T T SET T.PARM_DTL_TYP_CD = 'Document' where T.PARM_DTL_TYP_CD = 'D' AND NMSPC_CD LIKE 'KC%';
UPDATE KRNS_PARM_DTL_TYP_T T SET T.PARM_DTL_TYP_CD = 'All' where T.PARM_DTL_TYP_CD = 'A' AND NMSPC_CD LIKE 'KC%'; 
UPDATE KRNS_PARM_DTL_TYP_T T SET T.PARM_DTL_TYP_CD = 'Lookup' where T.PARM_DTL_TYP_CD = 'L' AND NMSPC_CD LIKE 'KC%';

COMMIT;
