CREATE OR REPLACE FUNCTION FN_CHECK_PROP_READY_FOR_S2S (

    AS_PROPOSAL_NUMBER   IN OSP$EPS_PROPOSAL.PROPOSAL_NUMBER%TYPE)

RETURN INTEGER IS

    LL_STATUS_CODE NUMBER;

BEGIN

  SELECT OSP$EPS_PROPOSAL.CREATION_STATUS_CODE
  INTO LL_STATUS_CODE
  FROM OSP$EPS_PROPOSAL
  WHERE PROPOSAL_NUMBER = AS_PROPOSAL_NUMBER;

  IF LL_STATUS_CODE in (5,6)  THEN
    RETURN 1;
  ELSE
    RETURN -1;
  END IF;

END ;
/

