/*
 * Kuali Coeus, a comprehensive research administration system for higher education.
 *
 * Copyright 2005-2016 Kuali, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package updateIacucProtocol

import org.kuali.kra.iacuc.actions.submit.IacucProtocolActionUpdateMapping;

import org.kuali.kra.iacuc.actions.submit.IacucProtocolReviewType;
import org.kuali.kra.iacuc.actions.submit.IacucProtocolSubmission;
import org.kuali.kra.iacuc.actions.submit.IacucProtocolSubmissionStatus; 
import org.kuali.kra.iacuc.actions.submit.IacucProtocolSubmissionType;

function void createAuditTrail(IacucProtocolActionUpdateMapping protocolAction) {
	if(protocolAction.getProtocol().getProtocolSubmission() != null) {
		protocolAction.getProtocolAction().setPrevSubmissionStatusCode(protocolAction.getProtocol().getProtocolSubmission().getSubmissionStatusCode());
		protocolAction.getProtocolAction().setSubmissionTypeCode(protocolAction.getProtocol().getProtocolSubmission().getSubmissionTypeCode());
	}
	String currentProtocolStatusCode = protocolAction.getProtocol().getProtocolStatusCode();
    protocolAction.getProtocolAction().setPrevProtocolStatusCode(currentProtocolStatusCode);
}
function void setProtocolSubmissionStatusCode(IacucProtocolActionUpdateMapping protocolAction, String newProtocolSubmissionStatusCode) {
	//TODO Test this with OJB, if you have to find object with new status code and re-attache to protocol submission status???
    protocolAction.getProtocolSubmission().setSubmissionStatusCode(newProtocolSubmissionStatusCode);  
} 
 
function void setNewProtocolSubmission(IacucProtocolActionUpdateMapping protocolAction, String submissionTypeCode, String reviewCode, String submissionStatusCode) {
	IacucProtocolSubmission protocolSubmission = new IacucProtocolSubmission();

	IacucProtocolSubmissionType submissionType = new IacucProtocolSubmissionType();
	submissionType.setSubmissionTypeCode(submissionTypeCode);
	protocolSubmission.setProtocolSubmissionType(submissionType);
	protocolSubmission.setSubmissionTypeCode(submissionTypeCode);
	
	IacucProtocolReviewType protocolReviewType = new IacucProtocolReviewType();
	protocolReviewType.setReviewTypeCode(reviewCode); 
	protocolSubmission.setProtocolReviewType(protocolReviewType);
	protocolSubmission.setProtocolReviewTypeCode(reviewCode);
	
	IacucProtocolSubmissionStatus protocolSubmissionStatus = new IacucProtocolSubmissionStatus();
	protocolSubmissionStatus.setProtocolSubmissionStatusCode(submissionStatusCode);
	protocolSubmission.setSubmissionStatus(protocolSubmissionStatus);
	protocolSubmission.setSubmissionStatusCode(submissionStatusCode);
	
	//TODO check submission number and increment to 1 if mounted bo does not contain latest submission number
	protocolSubmission.setSubmissionNumber(protocolAction.getProtocol().getProtocolSubmission().getSubmissionNumber() + 1);
	
	protocolAction.getProtocolAction().setSubmissionTypeCode(submissionTypeCode);
	//TODO should it be set to one to many or one to one mount
	protocolAction.getProtocol().setProtocolSubmission(protocolSubmission);
	protocolAction.getIacucProtocolAction().setCreatedSubmission(true);
}

function void setProtocolStatusCode(IacucProtocolActionUpdateMapping protocolAction, String newProtocolStatusCode) {
    protocolAction.getProtocol().setProtocolStatusCode(newProtocolStatusCode);  
} 



rule "fn_assign_to_agenda: Submission Status = 103 (Assigned to Agenda); Protocol Status = 101 (Submitted to IACUC)"
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "200")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "103");
	setProtocolStatusCode(protocolAction, "101");
end


rule "fn_SRRReqd: Submission Status = 212 (Major Revisions Required); Protocol Status = 107 (Major Revisions Required)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "211")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "212");
	setProtocolStatusCode(protocolAction, "107");
end


rule "fn_approve: Submission Status = 200;" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "204", protocolNumberARCondition in ("A", "R") )
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "200");
end



rule "fn_approve: Submission Status = 200; Protocol Status = 200" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "204", protocolNumberARCondition not in ("A", "R"))
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "200");
	setProtocolStatusCode(protocolAction, "200");
end



rule "fn_SMRReqd: Submission Status = 210 (Specific Minor Revisions Required); Protocol Status = 104 (Specific Minor Revisions Required)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "209")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "210");
	setProtocolStatusCode(protocolAction, "104");
end

rule "fn_return_to_pi: Submission Status = 209 (Returned To PI); Protocol Status = 102 (Return To PI)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "210")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "209");
	setProtocolStatusCode(protocolAction, "102");
end


//TODO: What is IACUC equivalent of Closed?
//rule "fn_close: Submission Status = 207 (Closed); Protocol Status = 301 (Closed by investigator)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "300", submissionTypeCode == "109")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolSubmissionStatusCode(protocolAction, "207");
//	setProtocolStatusCode(protocolAction, "301");
//end

//TODO: What is IACUC equiv for Closed by IRB Administrator?
//rule "fn_close: Protocol Status = 300 (Closed by IRB Administrator)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "300", submissionTypeCode != "109")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolStatusCode(protocolAction, "300");
//end

rule "fn_terminate: Submission Status = 202 (Terminated); Protocol Status = 303 (Terminated)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "306" )
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "202");
	setProtocolStatusCode(protocolAction, "307");
end

rule "fn_suspend by investigator: Submission Status = 203 (Suspended); Protocol Status =  304 (Suspended)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "307", submissionTypeCode == "111")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "203");
	setProtocolStatusCode(protocolAction, "304");
end

rule "fn_suspend: Submission Status = 203 (Suspended); Protocol Status =  304 (Suspended)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "307", submissionTypeCode != "111")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "203");
	setProtocolStatusCode(protocolAction, "304");
end

rule "fn_expire: Protocol Status =  1308 (Expire)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1302")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "1308");
end


rule "fn_withdraw: Submission Status =  204 (Withdrawn); Protocol Status =  105 (Withdrawn)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "115")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "204");
	setProtocolStatusCode(protocolAction, "105");
end


rule "fn_disapprove: Submission Status = 201(Disapproved); Protocol Status =  306(Disapprove)  " 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "301")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "201");
	setProtocolStatusCode(protocolAction, "303");
end


// following is changed from "exempt" to "review not required"
rule "fn_grantExempt: Submission Status = 1104 (Review Not Required); Protocol Status = 1300" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1207")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1104");
	setProtocolStatusCode(protocolAction, "1300");
end

//TODO: For IACUC, do we get rid of following?
//rule "fn_IRB_Review_Not_Required: fn_grantExempt: Submission Status = 104 (IRB review not nequired) ; Protocol Status = 310" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "210")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolSubmissionStatusCode(protocolAction, "104");
//	setProtocolStatusCode(protocolAction, "310");
//end
 
//IACUC not used 
//rule "fn_request_for_termination: submissionTypeCode = 108, reviewCode = 1, submissionStatusCode = 1104**/" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "104")
//then	
//	setNewProtocolSubmission(protocolAction, "108", "1", "102");
//end

//IACUC not used 
//rule "fn_request_for_suspension: submissionTypeCode = 110, reviewCode = 1, submissionStatusCode = 1104**/" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "106")
//then	
//	setNewProtocolSubmission(protocolAction, "110", "1", "102");
//end

//IACUC not used 
//rule "fn_request_to_close: submissionTypeCode = 109, reviewCode = 1, submissionStatusCode = 1104**/" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "105")
//then	
	//setNewProtocolSubmission(protocolAction, "109", "1", "102");
//end

rule "fn_request_to_deactivate: submissionTypeCode = 102, reviewCode = 1, submissionStatusCode = 101" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "107")
then	
	setNewProtocolSubmission(protocolAction, "102", "1", "101");
end

rule "fn_assign_to_schedule: Updates all the Submission with the given Committee Id & Schedule Id" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1109")
then	
	createAuditTrail(protocolAction);
	//TODO update all protocol submission's and committee schedule, following statement should be removed
	setNewProtocolSubmission(protocolAction, "111", "1", "102");
end

rule "fn_Response_Approve: Submission Status = 1200;" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1205", protocolNumberARCondition in ("A", "R") )
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1200");
end

rule "fn_Response_Approve: Submission Status = 1200; Protocol Status = 1200" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1205", protocolNumberARCondition not in ("A", "R"))
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "1200");
	setProtocolStatusCode(protocolAction, "1200");
end

rule "fn_IACUC_Acknowledge: Submission Status = 205" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "206")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "205");
end

rule "fn_notify_iacuc" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "114")
then	
	createAuditTrail(protocolAction);
	//new submission handled by notify iacuc service
end

// Following 2 statii do not exist in IACUC status table. What to do about them?
//rule "fn_table:  Protocol Status = 105 (Tabled)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1102")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolStatusCode(protocolAction, "105");
//end
//
//rule "fn_table:  Protocol Status = 106 (Tabled)" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "1104")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolStatusCode(protocolAction, "106");
//end

//TODO: What to do about this? Equivalent in IACUC?
//rule "fn_table:  Protocol Defer" 
//salience 100
//when
//	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "201")
//then	
//	createAuditTrail(protocolAction);
//	setProtocolSubmissionStatusCode(protocolAction, "1206");
//	setProtocolStatusCode(protocolAction, "103");
//end

rule "Abandoned:  Protocol Status = 309 " 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "117")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "309");
end



rule "fn_Administratively_Withdraw: Submission Status =  204 (Withdrawn); Protocol Status =  302 (Administratively Withdrawn)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping(actionTypeCode == "300")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "204");
	setProtocolStatusCode(protocolAction, "302");
end



rule "fn_Administratively_Incomplete: Submission Status =  214 (Administratively Incomplete); Protocol Status =  203 (Administratively Incomplete)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping(actionTypeCode == "216")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "214");
	setProtocolStatusCode(protocolAction, "203");
end



rule "fn_Administrative_Approve: Submission Status = 213 (Administratively Approved); Protocol Status = 202 (Administratively Approved)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping(actionTypeCode == "215")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "213");
	setProtocolStatusCode(protocolAction, "202");
end


rule "fn_table_protocol: Submission Status = 206 (Tabled); Protocol Status = 103 (Tabled)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping(actionTypeCode == "203")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "206");
	setProtocolStatusCode(protocolAction, "103");
end

rule "fn_hold_protocol: Protocol Status = 201 (Active - On Hold)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping(actionTypeCode == "305")
then	
	createAuditTrail(protocolAction);
	setProtocolStatusCode(protocolAction, "201");
end

rule "fn_lift_hold_protocol: Submission Status = 208 (Lift Hold); Protocol Status = 200 (Active)" 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping(actionTypeCode == "208")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "208");
	setProtocolStatusCode(protocolAction, "200");
end

rule "fn_deactivate: Submission Status = 207 (Deactivated); Protocol Status = 305 (Deactivated)  " 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "303")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "207");
	setProtocolStatusCode(protocolAction, "305");
end

rule "fn_review_not_required: Submission Status = 102 (Submitted to Committee); Protocol Status = 101 (Submitted to IACUC)  " 
salience 100
when
	protocolAction : IacucProtocolActionUpdateMapping( actionTypeCode == "207")
then	
	createAuditTrail(protocolAction);
	setProtocolSubmissionStatusCode(protocolAction, "104");
	setProtocolStatusCode(protocolAction, "300");
end
