DELIMITER /
CREATE TABLE NEGOTIATION_ATTACHMENT (
	ATTACHMENT_ID				DECIMAL(22) NOT NULL,
	ACTIVITY_ID				    DECIMAL(22) NOT NULL,
	DESCRIPTION				    VARCHAR(200),
	RESTRICTED				    CHAR(1) NOT NULL,
	FILE_ID					    DECIMAL(22) NOT NULL,
	UPDATE_TIMESTAMP     	DATE NOT NULL,
	UPDATE_USER          	VARCHAR(60) NOT NULL,
	VER_NBR              	DECIMAL(8,0) NOT NULL,
	OBJ_ID               	VARCHAR(36) NOT NULL
) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_bin
/

ALTER TABLE NEGOTIATION_ATTACHMENT
	ADD CONSTRAINT NEGOTIATION_ATTACHMENT_PK1
	PRIMARY KEY (ATTACHMENT_ID)
/
DELIMITER ;
