DELIMITER /
CREATE TABLE ORGANIZATION_CORRESPONDENT ( 
    ORGANIZATION_CORRESPONDENT_ID DECIMAL(12,0) NOT NULL, 
    ORGANIZATION_ID VARCHAR(8) NOT NULL, 
    CORRESPONDENT_TYPE_CODE DECIMAL(3,0) NOT NULL, 
    PERSON_ID VARCHAR(40) NULL,
    NON_EMPLOYEE_FLAG VARCHAR(1) NOT NULL, 
    DESCRIPTION VARCHAR(2000), 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR(60) NOT NULL, 
    VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR(36) NOT NULL) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_bin
/
ALTER TABLE ORGANIZATION_CORRESPONDENT 
ADD CONSTRAINT PK_ORGANIZATION_CORRESPONDENT 
PRIMARY KEY (ORGANIZATION_CORRESPONDENT_ID)
/
DELIMITER ;
