CREATE TABLE SUBCONTRACT_EXP_CAT (
	AWARD_NUMBER VARCHAR2(12) NOT NULL,
			
	LARGE_BUSINESS_AMT NUMBER(12,2), 
	SMALL_BUSINESS_AMT NUMBER(12,2), 
	WOMAN_OWNED_AMT NUMBER(12,2), 
	A8_DISADVANTAGE_AMT NUMBER(12,2), 
	HUB_ZONE_AMT NUMBER(12,2), 
	VETERAN_OWNED_AMT NUMBER(12,2), 
	SERVICE_DISABLED_VET_OWNED_AMT NUMBER(12,2), 
	HISTORICAL_BLACK_COLLEGE_AMT NUMBER(12,2),
	
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USER VARCHAR2(60) NOT NULL,
 	VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL,
 	OBJ_ID VARCHAR2(36) NOT NULL)
/

ALTER TABLE SUBCONTRACT_EXP_CAT
ADD CONSTRAINT PK_SUBCONTRACT_EXP_CAT
PRIMARY KEY (AWARD_NUMBER)
/
