DELIMITER /
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('ON', 'CA', UUID(), 1, 'ONTARIO', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('QB', 'CA', UUID(), 1, 'QUEBEC', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('NS', 'CA', UUID(), 1, 'NOVA SCOTIA', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('NB', 'CA', UUID(), 1, 'NEW BRUNSWICK', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('MA', 'CA', UUID(), 1, 'MANITOBA', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('BC', 'CA', UUID(), 1, 'BRITISH COLUMBIA', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('PI', 'CA', UUID(), 1, 'PRINCE EDWARD ISLAND', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('SA', 'CA', UUID(), 1, 'SASKATCHEWAN', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('NL', 'CA', UUID(), 1, 'NEWFOUNDLAND AND lABRADOR', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('AP', 'IN', UUID(), 1, 'ANDHRA PRADESH', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('AR', 'IN', UUID(), 1, 'ARUNACHAL PRADESH', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('AS', 'IN', UUID(), 1, 'ASSAM', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('BR', 'IN', UUID(), 1, 'BIHAR', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('CT', 'IN', UUID(), 1, 'CHHATTISGARH', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('GA', 'IN', UUID(), 1, 'GOA', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('PJ', 'IN', UUID(), 1, 'PUNJAB', 'Y')
/
INSERT INTO KRLC_ST_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD, OBJ_ID, VER_NBR, POSTAL_STATE_NM, ACTV_IND)
VALUES ('WB', 'IN', UUID(), 1, 'WEST BENGAL', 'Y')
/

DELIMITER ;
