CREATE TABLE MINUTE_ENTRY_TYPE (
    MINUTE_ENTRY_TYPE_CODE VARCHAR2 (3) NOT NULL, 
    SORT_ID NUMBER (3, 0) NOT NULL, 
    DESCRIPTION VARCHAR2 (200) NOT NULL, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2 (60) NOT NULL, 
    VER_NBR NUMBER (8, 0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2 (36) NOT NULL) ;

-- Primary Key Constraint  
ALTER TABLE MINUTE_ENTRY_TYPE 
    ADD CONSTRAINT PK_MINUTE_ENTRY_TYPE 
            PRIMARY KEY (MINUTE_ENTRY_TYPE_CODE) ;