CREATE TABLE SPONSOR_TERM_TYPE (
    VER_NBR NUMBER (8, 0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2 (36) NOT NULL, 
    SPONSOR_TERM_TYPE_CODE VARCHAR2 (3) NOT NULL, 
    DESCRIPTION VARCHAR2 (200) NOT NULL, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2 (60) NOT NULL) ;

ALTER TABLE SPONSOR_TERM_TYPE 
    ADD CONSTRAINT PK_SPONSOR_TERM_TYPE 
            PRIMARY KEY (SPONSOR_TERM_TYPE_CODE) ;