CREATE TABLE COMM_SCHEDULE_FREQUENCY (
    FREQUENCY_CODE number (3) NOT NULL, 
    DESCRIPTION varchar2 (200) NOT NULL, 
    NO_OF_DAYS number (3) , 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2 (60) NOT NULL, 
    VER_NBR NUMBER (8, 0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2 (36) NOT NULL) ;
    
ALTER TABLE COMM_SCHEDULE_FREQUENCY 
    ADD CONSTRAINT PK_COMM_SCHEDULE_FREQUENCY 
            PRIMARY KEY (FREQUENCY_CODE) ;