CREATE TABLE PERSON_TRAINING (
    PERSON_TRAINING_ID NUMBER (12, 0) NOT NULL, 
    PERSON_ID VARCHAR2 (9) NOT NULL, 
    TRAINING_NUMBER NUMBER (4, 0) NOT NULL, 
    TRAINING_CODE NUMBER (4, 0) NOT NULL, 
    DATE_REQUESTED DATE, 
    DATE_SUBMITTED DATE, 
    DATE_ACKNOWLEDGED DATE, 
    FOLLOWUP_DATE DATE, 
    SCORE VARCHAR2 (9) , 
    COMMENTS CLOB, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2 (60) NOT NULL, 
    VER_NBR NUMBER (8, 0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2 (36) NOT NULL) ;

ALTER TABLE PERSON_TRAINING 
    ADD CONSTRAINT PK_PERSON_TRAINING 
            PRIMARY KEY (PERSON_TRAINING_ID) ;

ALTER TABLE PERSON_TRAINING 
    ADD CONSTRAINT UQ_PERSON_TRAINING 
            UNIQUE (PERSON_ID, TRAINING_NUMBER) ;