CREATE OR REPLACE procedure GET_PER_BIO_FOR_PERSON
   ( AW_PERSON_ID IN OSP$PERSON_BIO.PERSON_ID%TYPE,
	  cur_generic IN OUT result_sets.cur_generic) is

	PDF_COUNT INTEGER ;
	SOURCE_COUNT INTEGER ;

begin


open cur_generic for

  SELECT OSP$PERSON_BIO.PERSON_ID,
         OSP$PERSON_BIO.BIO_NUMBER,
         OSP$PERSON_BIO.DESCRIPTION,
         OSP$PERSON_BIO.UPDATE_TIMESTAMP,
         OSP$PERSON_BIO.UPDATE_USER,
   		6 PDF_FLAG_BORDER,   -- For setting border of pdf flag in datawindows (6=3D raised)
   		6 SOURCE_FLAG_BORDER, -- For setting border of source flag in datawindows (6=3D raised)
		OSP$PERSON_BIO_PDF.BIO_NUMBER as PDF_BIO_NUMBER,
		OSP$PERSON_BIO_SOURCE.BIO_NUMBER as SOURCE_BIO_NUMBER
    FROM OSP$PERSON_BIO,
		 OSP$PERSON_BIO_PDF,
		 OSP$PERSON_BIO_SOURCE
   WHERE OSP$PERSON_BIO.PERSON_ID = AW_PERSON_ID AND
   		 OSP$PERSON_BIO.PERSON_ID = OSP$PERSON_BIO_PDF.PERSON_ID(+) AND
		 OSP$PERSON_BIO.PERSON_ID = OSP$PERSON_BIO_SOURCE.PERSON_ID(+) AND
		 OSP$PERSON_BIO.BIO_NUMBER = OSP$PERSON_BIO_PDF.BIO_NUMBER(+) AND
		 OSP$PERSON_BIO.BIO_NUMBER = OSP$PERSON_BIO_SOURCE.BIO_NUMBER(+);
end;
/

