-- REM INSERTING into COMM_RESEARCH_AREAS
INSERT INTO COMM_RESEARCH_AREAS (ID,COMMITTEE_ID_FK,RESEARCH_AREA_CODE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
VALUES (1,1,'000001',STR_TO_DATE('05-JUL-10','%d-%b-%y'),'KCDBA',0,UUID());


