-- REM INSERTING into COMM_MEMBERSHIPS
Insert into COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,MEMBERSHIP_TYPE_CODE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
values (1,1,'10000000005',null,'Inez  Chew','0','N',STR_TO_DATE('01-JUL-10','%d-%b-%y'),STR_TO_DATE('01-JUL-15','%d-%b-%y'),'1', NULL,'Send e-mail','Is trained',STR_TO_DATE('05-JUL-10','%d-%b-%y'),'KCDBA',0,UUID());


Insert into COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,MEMBERSHIP_TYPE_CODE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
values (4,1,'10000000006',null,'Della  Woods','0','N',STR_TO_DATE('01-JUL-10','%d-%b-%y'),STR_TO_DATE('01-JUL-15','%d-%b-%y'),'1', NULL, NULL, NULL,STR_TO_DATE('05-JUL-10','%d-%b-%y'),'KCDBA',0,UUID());


Insert into COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,MEMBERSHIP_TYPE_CODE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
values (7,1,'10000000007',null,'Opal  Blood','0','N',STR_TO_DATE('01-JUL-10','%d-%b-%y'),STR_TO_DATE('01-JUL-15','%d-%b-%y'),'1', NULL, NULL, NULL,STR_TO_DATE('05-JUL-10','%d-%b-%y'),'KCDBA',0,UUID());


Insert into COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,MEMBERSHIP_TYPE_CODE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
values (10,1,'10000000008',null,'Allyson  Cate','0','N',STR_TO_DATE('01-JAN-08','%d-%b-%y'),STR_TO_DATE('01-JUL-15','%d-%b-%y'),'1', NULL, NULL, NULL,STR_TO_DATE('05-JUL-10','%d-%b-%y'),'KCDBA',0,UUID());


Insert into COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,MEMBERSHIP_TYPE_CODE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
values (15,1,'10000000059',null,'Roger  Rabbit','0','N',STR_TO_DATE('01-JUL-01','%d-%b-%y'),STR_TO_DATE('01-JUL-10','%d-%b-%y'),'1', NULL, NULL, NULL,STR_TO_DATE('05-JUL-10','%d-%b-%y'),'KCDBA',0,UUID());


Insert into COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,MEMBERSHIP_TYPE_CODE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
values (18,1,'10000000004',null,'Nicholas  Majors','0','Y',STR_TO_DATE('01-JUL-10','%d-%b-%y'),STR_TO_DATE('01-JUL-15','%d-%b-%y'),'2', NULL, NULL,'Non Voting Training only',STR_TO_DATE('05-JUL-10','%d-%b-%y'),'KCDBA',0,UUID());


INSERT INTO COMM_MEMBERSHIPS (COMM_MEMBERSHIP_ID,COMMITTEE_ID_FK,PERSON_ID,ROLODEX_ID,PERSON_NAME,MEMBERSHIP_ID,PAID_MEMBER_FLAG,TERM_START_DATE,TERM_END_DATE,MEMBERSHIP_TYPE_CODE,COMMENTS,CONTACT_NOTES,TRAINING_NOTES,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
VALUES (21,1,'10000000002',NULL,'Joe  Tester','0','Y',STR_TO_DATE('01-JUL-10','%d-%b-%y'),STR_TO_DATE('01-JUL-15','%d-%b-%y'),'1', NULL,'No Email', NULL,STR_TO_DATE('05-JUL-10','%d-%b-%y'),'KCDBA',0,UUID());


