INSERT INTO KREN_RECIP_T (NTFCTN_ID,PRNCPL_ID,RECIP_ID,RECIP_TYP_CD)
  VALUES (1,'irbresearcher',1,'P');

INSERT INTO KREN_RECIP_T (NTFCTN_ID,PRNCPL_ID,RECIP_ID,RECIP_TYP_CD)
  VALUES (1,'quickstart',2,'P');

