ALTER TABLE BUDGET_PERSONS ADD "PERSON_SEQUENCE_NUMBER" NUMBER(3,0) NOT NULL;
ALTER TABLE BUDGET_PERSONS ADD "ROLODEX_ID" NUMBER(6,0);
ALTER TABLE BUDGET_PERSONS MODIFY "PERSON_ID" NULL;
ALTER TABLE BUDGET_PERSONS DROP CONSTRAINT "PK_BUDGET_PERSONS_KRA";
ALTER TABLE BUDGET_PERSONS ADD (CONSTRAINT "PK_BUDGET_PERSONS_KRA" PRIMARY KEY ("PROPOSAL_NUMBER", "VERSION_NUMBER", "PERSON_SEQUENCE_NUMBER"));
ALTER TABLE BUDGET_PERSONS ADD (CONSTRAINT "UK_BUDGET_PERSONS_KRA" UNIQUE ("PROPOSAL_NUMBER", "VERSION_NUMBER", "PERSON_ID","ROLODEX_ID", "JOB_CODE", "EFFECTIVE_DATE"));
ALTER TABLE BUDGET_PERSONS DROP COLUMN APPOINTMENT_TYPE;
ALTER TABLE BUDGET_PERSONS ADD APPOINTMENT_TYPE_CODE VARCHAR2(3);
ALTER TABLE BUDGET_PERSONS ADD (CONSTRAINT "FK_APPOINTMENT_TYPE_CODE_KRA" FOREIGN KEY ("APPOINTMENT_TYPE_CODE")
	  REFERENCES "APPOINTMENT_TYPE" ("APPOINTMENT_TYPE_CODE") ); 

