ALTER TABLE special_review
 MODIFY SPECIAL_REVIEW_CODE	VARCHAR2(3);

ALTER TABLE VALID_SP_REV_APPROVAL
 MODIFY SPECIAL_REVIEW_CODE	VARCHAR2(3);

ALTER TABLE EPS_PROP_SPECIAL_REVIEW
 MODIFY SPECIAL_REVIEW_CODE	VARCHAR2(3);
