CREATE TABLE AWARD
(
  MIT_AWARD_NUMBER               CHAR(10 BYTE)  NOT NULL,
  SEQUENCE_NUMBER                NUMBER(4)      NOT NULL,
  MODIFICATION_NUMBER            VARCHAR2(50 BYTE),
  SPONSOR_AWARD_NUMBER           VARCHAR2(70 BYTE),
  STATUS_CODE                    NUMBER(3)      NOT NULL,
  TEMPLATE_CODE                  NUMBER(5),
  AWARD_EXECUTION_DATE           DATE,
  AWARD_EFFECTIVE_DATE           DATE,
  BEGIN_DATE                     DATE,
  SPONSOR_CODE                   CHAR(6 BYTE)   NOT NULL,
  ACCOUNT_NUMBER                 CHAR(7 BYTE),
  APPRVD_EQUIPMENT_INDICATOR     CHAR(2 BYTE)   NOT NULL,
  APPRVD_FOREIGN_TRIP_INDICATOR  CHAR(2 BYTE)   NOT NULL,
  APPRVD_SUBCONTRACT_INDICATOR   CHAR(2 BYTE)   NOT NULL,
  PAYMENT_SCHEDULE_INDICATOR     CHAR(2 BYTE)   NOT NULL,
  IDC_INDICATOR                  CHAR(2 BYTE)   NOT NULL,
  TRANSFER_SPONSOR_INDICATOR     CHAR(2 BYTE)   NOT NULL,
  COST_SHARING_INDICATOR         CHAR(2 BYTE)   NOT NULL,
  UPDATE_TIMESTAMP               DATE           NOT NULL,
  UPDATE_USER                    VARCHAR2(8 BYTE) NOT NULL,
  SPECIAL_REVIEW_INDICATOR       CHAR(2 BYTE)   NOT NULL,
  SCIENCE_CODE_INDICATOR         CHAR(2 BYTE)   NOT NULL,
  NSF_CODE                       VARCHAR2(15 BYTE)
);

ALTER TABLE AWARD ADD (
  CONSTRAINT PK_AWARD
 PRIMARY KEY
 (MIT_AWARD_NUMBER, SEQUENCE_NUMBER));
