-- Table Script 
CREATE TABLE BATCH_CORRESPONDENCE ( 
    BATCH_CORRESPONDENCE_TYPE_CODE VARCHAR2(3) NOT NULL, 
    DESCRIPTION VARCHAR2(200) NOT NULL, 
    DEFAULT_TIME_WINDOW NUMBER(3,0) NOT NULL, 
    FINAL_ACTION_TYPE_CODE VARCHAR2(3), 
    FINAL_ACTION_CORRESP_TYPE VARCHAR2(3), 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2(60) NOT NULL, 
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL);


-- Primary Key Constraint 
ALTER TABLE BATCH_CORRESPONDENCE 
ADD CONSTRAINT PK_BATCH_CORRESPONDENCE 
PRIMARY KEY (BATCH_CORRESPONDENCE_TYPE_CODE);

-- Foreign Key Constraint(s)
ALTER TABLE BATCH_CORRESPONDENCE 
ADD CONSTRAINT FK_BATCH_CORRESPONDENCE_2 
FOREIGN KEY (FINAL_ACTION_CORRESP_TYPE) 
REFERENCES PROTO_CORRESP_TYPE (PROTO_CORRESP_TYPE_CODE);

ALTER TABLE BATCH_CORRESPONDENCE 
ADD CONSTRAINT FK_BATCH_CORRESPONDENCE 
FOREIGN KEY (FINAL_ACTION_TYPE_CODE) 
REFERENCES PROTOCOL_ACTION_TYPE (PROTOCOL_ACTION_TYPE_CODE);

