CREATE TABLE COMM_DECISION_MOTION_TYPE (
    COMM_DECISION_MOTION_TYPE_CODE VARCHAR2(3) NOT NULL,
    DESCRIPTION VARCHAR2(200) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    UPDATE_USER VARCHAR2(60) NOT NULL,
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL,
    OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL);

ALTER TABLE COMM_DECISION_MOTION_TYPE
ADD CONSTRAINT PK_COMM_DECISION_MOTION_TYPE
PRIMARY KEY (COMM_DECISION_MOTION_TYPE_CODE);