#
# $Id: EPS_PROP_PERSON_ROLE.sql,v 1.1 2007-09-03 21:41:44 lprzybyl Exp $
#
create table EPS_PROP_PERSON_ROLE(
  PROP_PERSON_ROLE_ID VARCHAR(12)   CONSTRAINT EPS_PROP_PERSON_ROLE_N1 not null,
  DESCRIPTION       VARCHAR(25) NOT NULL,
  update_timestamp  date         not null,
  update_user       varchar2 (8) not null,
  VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL,
  OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
  constraint EPS_PROP_PERSON_ROLE_N2
  primary key ( PROP_PERSON_ROLE_ID ) 
);

ALTER TABLE EPS_PROP_PERSON_ROLE 
  ADD ( CONSTRAINT EPS_PROP_PERSON_ROLE_C0
      UNIQUE (OBJ_ID) 
      NOT DEFERRABLE INITIALLY IMMEDIATE);