 CREATE TABLE EPS_PROP_LOCATION 
   (	"PROPOSAL_NUMBER" NUMBER(12,0) constraint EPS_PROP_LOCATIONN1 NOT NULL ENABLE, 
	"LOCATION_SEQUENCE_NUMBER" NUMBER(3,0) constraint EPS_PROP_LOCATIONN2 NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(60) constraint EPS_PROP_LOCATIONN3 NOT NULL ENABLE, 
	"ROLODEX_ID" NUMBER(6,0), 
	"UPDATE_TIMESTAMP" DATE constraint EPS_PROP_LOCATIONN4 NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(8) constraint EPS_PROP_LOCATIONN5 NOT NULL ENABLE, 
	 "VER_NBR" NUMBER(8,0) DEFAULT 1  constraint  EPS_PROP_LOCATIONN6  NOT NULL ENABLE,
	"OBJ_ID" VARCHAR2(36) DEFAULT SYS_GUID()  constraint  EPS_PROP_LOCATIONN7  NOT NULL ENABLE,
	CONSTRAINT "PK_EPS_PROP_LOCATION_KRA" PRIMARY KEY ("PROPOSAL_NUMBER", "LOCATION_SEQUENCE_NUMBER") ENABLE
) 
 
/
 ALTER TABLE EPS_PROP_LOCATION ADD (CONSTRAINT "FK_EPS_PROP_LOCATION_KRA" FOREIGN KEY ("PROPOSAL_NUMBER")
	  REFERENCES "EPS_PROPOSAL" ("PROPOSAL_NUMBER") ) 
 
/
 ALTER TABLE EPS_PROP_LOCATION ADD (CONSTRAINT "FK_EPS_PROP_LOCATION_RLDEX_KRA" FOREIGN KEY ("ROLODEX_ID")
	  REFERENCES "ROLODEX" ("ROLODEX_ID") ) 
/ 