#
# $Id: EPS_PROP_PERSON_UNITS.sql,v 1.3 2008-01-23 22:49:52 lprzybyl Exp $
#
create table EPS_PROP_PERSON_UNITS(
  PROPOSAL_NUMBER     NUMBER(12)   CONSTRAINT EPS_PROP_PERSON_UNITS_N2 not null,
  PROP_PERSON_NUMBER  NUMBER(12)   CONSTRAINT EPS_PROP_PERSON_UNITS_N3 NOT NULL,
  UNIT_NUMBER         VARCHAR2(8)   CONSTRAINT EPS_PROP_PERSON_UNITS_N4 NOT NULL,
  LEAD_UNIT_FLAG      CHAR(1),
  update_timestamp  date         not null,
  update_user       varchar2 (8) not null,
  VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL,
  OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
  constraint EPS_PROP_PERSON_UNITS_N5
  primary key (PROPOSAL_NUMBER, PROP_PERSON_NUMBER, UNIT_NUMBER)
)
/
ALTER TABLE EPS_PROP_PERSON_UNITS
  ADD ( CONSTRAINT EPS_PROP_PERSON_UNITS_C0
      UNIQUE (OBJ_ID) 
      NOT DEFERRABLE INITIALLY IMMEDIATE);
/
ALTER TABLE EPS_PROP_PERSON_UNITS ADD (CONSTRAINT EPS_PROP_PERSON_UNITS_C1 UNIQUE (PROPOSAL_NUMBER, PROP_PERSON_NUMBER))
