-- Table Script 
CREATE TABLE GROUP_TYPES ( 
    GROUP_TYPE_CODE NUMBER(3,0) NOT NULL, 
    GROUP_NAME VARCHAR2(200) NOT NULL, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2(60) NOT NULL, 
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL);


-- Primary Key Constraint 
ALTER TABLE GROUP_TYPES 
ADD CONSTRAINT PK_GROUP_TYPES 
PRIMARY KEY (GROUP_TYPE_CODE);

