#
# $Id: INV_CREDIT_TYPE.sql,v 1.2 2007-10-24 19:34:05 rmancher Exp $
#
 CREATE TABLE INV_CREDIT_TYPE (
    INV_CREDIT_TYPE_CODE         VARCHAR2(3)  constraint INV_CREDIT_TYPE_N1 not null,
    DESCRIPTION                  VARCHAR2(300) NOT NULL,
    ADDS_TO_HUNDRED              CHAR(1) NOT NULL,
	UPDATE_TIMESTAMP DATE constraint INV_CREDIT_TYPE_N2 NOT NULL ENABLE,
	UPDATE_USER VARCHAR2(8) constraint INV_CREDIT_TYPE_N3 NOT NULL ENABLE,
	VER_NBR NUMBER(8,0) DEFAULT 1  constraint INV_CREDIT_TYPE_N4  NOT NULL ENABLE,
	OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
    CONSTRAINT INV_CREDIT_TYPE_C0 UNIQUE (OBJ_ID) NOT DEFERRABLE INITIALLY IMMEDIATE,
	CONSTRAINT INV_CREDIT_TYPE_P1 PRIMARY KEY (INV_CREDIT_TYPE_CODE) ENABLE
);
