 CREATE TABLE KRA_USER 
   (	"USER_ID" VARCHAR2(8) constraint KRA_USERN1 NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(90), 
	"NON_MIT_PERSON_FLAG" CHAR(1), 
	"PERSON_ID" VARCHAR2(9), 
	"USER_TYPE" CHAR(1), 
	"UNIT_NUMBER" VARCHAR2(8), 
	"STATUS" CHAR(1), 
	"UPDATE_TIMESTAMP" DATE constraint KRA_USERN2 NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(8) constraint KRA_USERN3 NOT NULL ENABLE, 
	 "VER_NBR" NUMBER(8,0) DEFAULT 1  constraint  KRA_USERN4  NOT NULL ENABLE,
	"OBJ_ID" VARCHAR2(36) DEFAULT SYS_GUID()  constraint  KRA_USERN5  NOT NULL ENABLE,
	CONSTRAINT "PK_USER_KRA" PRIMARY KEY ("USER_ID") ENABLE
);
 

 ALTER TABLE KRA_USER ADD (CONSTRAINT "FK_USER_UNIT_NUMBER_KRA" FOREIGN KEY ("UNIT_NUMBER")
	  REFERENCES "UNIT" ("UNIT_NUMBER") ) ;
