-- Table Script 
CREATE TABLE PROPOSAL_IDC_RATE ( 
    PROPOSAL_IDC_RATE_ID NUMBER(12,0) NOT NULL, 
    PROPOSAL_NUMBER VARCHAR2(8) NOT NULL, 
    SEQUENCE_NUMBER NUMBER(4,0) NOT NULL, 
    APPLICABLE_IDC_RATE NUMBER(5,2) NOT NULL, 
    IDC_RATE_TYPE_CODE NUMBER(3,0) NOT NULL, 
    FISCAL_YEAR CHAR(4) NOT NULL, 
    ON_CAMPUS_FLAG CHAR(1) NOT NULL, 
    UNDERRECOVERY_OF_IDC NUMBER(12,2), 
    SOURCE_ACCOUNT VARCHAR2(7) NOT NULL, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2(60) NOT NULL, 
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL);


-- Primary Key Constraint 
ALTER TABLE PROPOSAL_IDC_RATE 
ADD CONSTRAINT PK_PROPOSAL_IDC_RATE 
PRIMARY KEY (PROPOSAL_IDC_RATE_ID);

-- *************** MODIFIED PRIMARY KEY COLUMN - Introduced new primary key for existing composite key ************ 
-- ALTER TABLE PROPOSAL_IDC_RATE 
-- ADD CONSTRAINT PK_PROPOSAL_IDC_RATE 
-- PRIMARY KEY (PROPOSAL_NUMBER, SEQUENCE_NUMBER, APPLICABLE_IDC_RATE, IDC_RATE_TYPE_CODE, FISCAL_YEAR, ON_CAMPUS_FLAG, SOURCE_ACCOUNT);
-- *************** MODIFIED PRIMARY KEY COLUMN - Introduced new primary key for existing composite key ************ 
 

-- *************** UNIQUE CONSTRAINT DEFINED FOR COMPOSITE KEY COLUMNS ************ 
ALTER TABLE PROPOSAL_IDC_RATE 
ADD CONSTRAINT UQ_PROPOSAL_IDC_RATE 
UNIQUE (PROPOSAL_NUMBER, SEQUENCE_NUMBER, APPLICABLE_IDC_RATE, IDC_RATE_TYPE_CODE, FISCAL_YEAR, ON_CAMPUS_FLAG, SOURCE_ACCOUNT);

-- Foreign Key Constraint(s)
ALTER TABLE PROPOSAL_IDC_RATE 
ADD CONSTRAINT FK_PROPOSAL_IDC_RATE 
FOREIGN KEY (IDC_RATE_TYPE_CODE) 
REFERENCES IDC_RATE_TYPE (IDC_RATE_TYPE_CODE);

