-- Table Script 
CREATE TABLE QUESTION (
    QUESTION_REF_ID NUMBER(12,0) NOT NULL,
    QUESTION_ID NUMBER(6,0) NOT NULL,
    SEQUENCE_NUMBER NUMBER(4,0) NOT NULL,
    QUESTION VARCHAR2(2000) NOT NULL, 
    STATUS CHAR(1) NOT NULL,
    GROUP_TYPE_CODE NUMBER(3,0) NOT NULL, 
    QUESTION_TYPE_ID NUMBER(12,0) NOT NULL, 
    LOOKUP_CLASS VARCHAR2(100), 
    LOOKUP_RETURN VARCHAR2(30), 
    DISPLAYED_ANSWERS NUMBER(2,0),
    MAX_ANSWERS NUMBER(2,0),
    ANSWER_MAX_LENGTH NUMBER(4,0), 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2(60) NOT NULL, 
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL);


-- Primary Key Constraint 
ALTER TABLE QUESTION 
ADD CONSTRAINT PK_QUESTION 
PRIMARY KEY (QUESTION_REF_ID);

/* *************** UNIQUE CONSTRAINT DEFINED FOR COMPOSITE KEY COLUMNS ************ */ 
ALTER TABLE QUESTION 
ADD CONSTRAINT UQ_QUESTION_ID
UNIQUE (QUESTION_ID, SEQUENCE_NUMBER);


