-- Table Script 
CREATE TABLE QUESTIONNAIRE_ANSWER_HEADER ( 
    QUESTIONNAIRE_ANSWER_HEADER_ID NUMBER(12,0) NOT NULL,
    QUESTIONNAIRE_REF_ID_FK NUMBER(12,0) NOT NULL, 
    MODULE_ITEM_CODE NUMBER(3,0) NOT NULL, 
    MODULE_ITEM_KEY VARCHAR2(20) NOT NULL, 
    MODULE_SUB_ITEM_CODE NUMBER(3,0) NOT NULL, 
    MODULE_SUB_ITEM_KEY VARCHAR2(20) NOT NULL, 
    QUESTIONNAIRE_COMPLETED_FLAG VARCHAR2(1) NOT NULL, 
    UPDATE_TIMESTAMP DATE NOT NULL, 
    UPDATE_USER VARCHAR2(60) NOT NULL, 
    VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL, 
    OBJ_ID VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL);

-- Primary Key Constraint 
ALTER TABLE QUESTIONNAIRE_ANSWER_HEADER 
ADD CONSTRAINT PK_QUESTIONNAIRE_ANSWER_HEADER
PRIMARY KEY (QUESTIONNAIRE_ANSWER_HEADER_ID);

ALTER TABLE QUESTIONNAIRE_ANSWER_HEADER 
ADD CONSTRAINT FK_QUESTIONNAIRE_QID 
FOREIGN KEY (QUESTIONNAIRE_REF_ID_FK)
REFERENCES QUESTIONNAIRE (QUESTIONNAIRE_REF_ID);

