--KREN_CHNL_S
DROP SEQUENCE KREN_CHNL_S;
CREATE SEQUENCE KREN_CHNL_S START WITH 1001 INCREMENT BY 1 NOCACHE;
--KREN_CHNL_SUBSCRP_S
DROP SEQUENCE KREN_CHNL_SUBSCRP_S;
CREATE SEQUENCE KREN_CHNL_SUBSCRP_S START WITH 1001 INCREMENT BY 1 NOCACHE;
--KREN_CNTNT_TYP_S
DROP SEQUENCE KREN_CNTNT_TYP_S;
CREATE SEQUENCE KREN_CNTNT_TYP_S START WITH 3 INCREMENT BY 1 NOCACHE;
--KREN_MSG_DELIV_S
DROP SEQUENCE KREN_MSG_DELIV_S;
CREATE SEQUENCE KREN_MSG_DELIV_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREN_MSG_S
DROP SEQUENCE KREN_MSG_S;
CREATE SEQUENCE KREN_MSG_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREN_NTFCTN_MSG_DELIV_S
DROP SEQUENCE KREN_NTFCTN_MSG_DELIV_S;
CREATE SEQUENCE KREN_NTFCTN_MSG_DELIV_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREN_NTFCTN_S
DROP SEQUENCE KREN_NTFCTN_S;
CREATE SEQUENCE KREN_NTFCTN_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREN_PRIO_S
DROP SEQUENCE KREN_PRIO_S;
CREATE SEQUENCE KREN_PRIO_S START WITH 4 INCREMENT BY 1 NOCACHE;
--KREN_PRODCR_S
DROP SEQUENCE KREN_PRODCR_S;
CREATE SEQUENCE KREN_PRODCR_S START WITH 4 INCREMENT BY 1 NOCACHE;
--KREN_RECIP_DELIV_S
DROP SEQUENCE KREN_RECIP_DELIV_S;
CREATE SEQUENCE KREN_RECIP_DELIV_S START WITH 17 INCREMENT BY 1 NOCACHE;
--KREN_RECIP_LIST_S
DROP SEQUENCE KREN_RECIP_LIST_S;
CREATE SEQUENCE KREN_RECIP_LIST_S START WITH 3 INCREMENT BY 1 NOCACHE;
--KREN_RECIP_PREF_S
DROP SEQUENCE KREN_RECIP_PREF_S;
CREATE SEQUENCE KREN_RECIP_PREF_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREN_RECIP_S
DROP SEQUENCE KREN_RECIP_S;
CREATE SEQUENCE KREN_RECIP_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREN_RVWER_S
DROP SEQUENCE KREN_RVWER_S;
CREATE SEQUENCE KREN_RVWER_S START WITH 4 INCREMENT BY 1 NOCACHE;
--KREN_SNDR_S
DROP SEQUENCE KREN_SNDR_S;
CREATE SEQUENCE KREN_SNDR_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREW_ACTN_ITM_S
DROP SEQUENCE KREW_ACTN_ITM_S;
CREATE SEQUENCE KREW_ACTN_ITM_S START WITH 1 INCREMENT BY 1 NOCACHE;
/*
KREW_ACTN_LIST_OPTN_S
DROP SEQUENCE KREW_ACTN_LIST_OPTN_S;
CREATE SEQUENCE KREW_ACTN_LIST_OPTN_S START WITH 1 INCREMENT BY 1 NOCACHE;
*/
--KREW_ACTN_RQST_S
DROP SEQUENCE KREW_ACTN_RQST_S;
CREATE SEQUENCE KREW_ACTN_RQST_S START WITH 2375 INCREMENT BY 1 NOCACHE;
--KREW_ACTN_TKN_S
DROP SEQUENCE KREW_ACTN_TKN_S;
CREATE SEQUENCE KREW_ACTN_TKN_S START WITH 2339 INCREMENT BY 1 NOCACHE;
--KREW_DOC_HDR_S
DROP SEQUENCE KREW_DOC_HDR_S;
CREATE SEQUENCE KREW_DOC_HDR_S START WITH 4073 INCREMENT BY 1 NOCACHE;
--KREW_DOC_LNK_S
DROP SEQUENCE KREW_DOC_LNK_S;
CREATE SEQUENCE KREW_DOC_LNK_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREW_DOC_NTE_S
DROP SEQUENCE KREW_DOC_NTE_S;
CREATE SEQUENCE KREW_DOC_NTE_S START WITH 2006 INCREMENT BY 1 NOCACHE;
--KREW_DOC_TYP_ATTR_S
DROP SEQUENCE KREW_DOC_TYP_ATTR_S;
CREATE SEQUENCE KREW_DOC_TYP_ATTR_S START WITH 2139 INCREMENT BY 1 NOCACHE;
--KREW_EDL_FLD_DMP_S
DROP SEQUENCE KREW_EDL_FLD_DMP_S;
CREATE SEQUENCE KREW_EDL_FLD_DMP_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREW_EDL_S
DROP SEQUENCE KREW_EDL_S;
CREATE SEQUENCE KREW_EDL_S START WITH 2011 INCREMENT BY 1 NOCACHE;
--KREW_HLP_S
DROP SEQUENCE KREW_HLP_S;
CREATE SEQUENCE KREW_HLP_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREW_OUT_BOX_ITM_S
DROP SEQUENCE KREW_OUT_BOX_ITM_S;
CREATE SEQUENCE KREW_OUT_BOX_ITM_S START WITH 1 INCREMENT BY 1 NOCACHE;
/*
KREW_RIA_DOCTYPE_MAP_ID_S
DROP SEQUENCE KREW_RIA_DOCTYPE_MAP_ID_S;
CREATE SEQUENCE KREW_RIA_DOCTYPE_MAP_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
*/
--KREW_RSP_S
DROP SEQUENCE KREW_RSP_S;
CREATE SEQUENCE KREW_RSP_S START WITH 2177 INCREMENT BY 1 NOCACHE;
--KREW_RTE_NODE_CFG_PARM_S
DROP SEQUENCE KREW_RTE_NODE_CFG_PARM_S;
CREATE SEQUENCE KREW_RTE_NODE_CFG_PARM_S START WITH 5862 INCREMENT BY 1 NOCACHE;
--KREW_RTE_NODE_S
DROP SEQUENCE KREW_RTE_NODE_S;
CREATE SEQUENCE KREW_RTE_NODE_S START WITH 4218 INCREMENT BY 1 NOCACHE;
--KREW_RTE_TMPL_S
DROP SEQUENCE KREW_RTE_TMPL_S;
CREATE SEQUENCE KREW_RTE_TMPL_S START WITH 1872 INCREMENT BY 1 NOCACHE;
--KREW_RULE_EXPR_S
DROP SEQUENCE KREW_RULE_EXPR_S;
CREATE SEQUENCE KREW_RULE_EXPR_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREW_RULE_TMPL_OPTN_S
DROP SEQUENCE KREW_RULE_TMPL_OPTN_S;
CREATE SEQUENCE KREW_RULE_TMPL_OPTN_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KREW_SRCH_ATTR_S
DROP SEQUENCE KREW_SRCH_ATTR_S;
CREATE SEQUENCE KREW_SRCH_ATTR_S START WITH 2041 INCREMENT BY 1 NOCACHE;
/*
KREW_USR_S
DROP SEQUENCE KREW_USR_S;
CREATE SEQUENCE KREW_USR_S START WITH 1 INCREMENT BY 1 NOCACHE;
-KRIM_ATTR_DATA_ID_S
DROP SEQUENCE KRIM_ATTR_DATA_ID_S;
CREATE SEQUENCE KRIM_ATTR_DATA_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
KRIM_ATTR_DEFN_ID_S
DROP SEQUENCE KRIM_ATTR_DEFN_ID_S;
CREATE SEQUENCE KRIM_ATTR_DEFN_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
-KRIM_DLGN_ID_S
DROP SEQUENCE KRIM_DLGN_ID_S;
CREATE SEQUENCE KRIM_DLGN_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
-KRIM_DLGN_MBR_ID_S
DROP SEQUENCE KRIM_DLGN_MBR_ID_S;
CREATE SEQUENCE KRIM_DLGN_MBR_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
-KRIM_ENTITY_ADDR_ID_S
DROP SEQUENCE KRIM_ENTITY_ADDR_ID_S;
CREATE SEQUENCE KRIM_ENTITY_ADDR_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
-KRIM_ENTITY_AFLTN_ID_S
DROP SEQUENCE KRIM_ENTITY_AFLTN_ID_S;
CREATE SEQUENCE KRIM_ENTITY_AFLTN_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
KRIM_ENTITY_CTZNSHP_ID_S
DROP SEQUENCE KRIM_ENTITY_CTZNSHP_ID_S;
CREATE SEQUENCE KRIM_ENTITY_CTZNSHP_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
-KRIM_ENTITY_EMAIL_ID_S
DROP SEQUENCE KRIM_ENTITY_EMAIL_ID_S;
CREATE SEQUENCE KRIM_ENTITY_EMAIL_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
-KRIM_ENTITY_EMP_ID_S
DROP SEQUENCE KRIM_ENTITY_EMP_ID_S;
CREATE SEQUENCE KRIM_ENTITY_EMP_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
*/
--KRIM_ENTITY_ETHNIC_ID_S
DROP SEQUENCE KRIM_ENTITY_ETHNIC_ID_S;
CREATE SEQUENCE KRIM_ENTITY_ETHNIC_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRIM_ENTITY_EXT_ID_ID_S
DROP SEQUENCE KRIM_ENTITY_EXT_ID_ID_S;
CREATE SEQUENCE KRIM_ENTITY_EXT_ID_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRIM_ENTITY_ID_S
DROP SEQUENCE KRIM_ENTITY_ID_S;
CREATE SEQUENCE KRIM_ENTITY_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
/*
-KRIM_ENTITY_NM_ID_S
DROP SEQUENCE KRIM_ENTITY_NM_ID_S;
CREATE SEQUENCE KRIM_ENTITY_NM_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
-KRIM_ENTITY_PHONE_ID_S
DROP SEQUENCE KRIM_ENTITY_PHONE_ID_S;
CREATE SEQUENCE KRIM_ENTITY_PHONE_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
*/
--KRIM_ENTITY_RESIDENCY_ID_S
DROP SEQUENCE KRIM_ENTITY_RESIDENCY_ID_S;
CREATE SEQUENCE KRIM_ENTITY_RESIDENCY_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRIM_ENTITY_VISA_ID_S
DROP SEQUENCE KRIM_ENTITY_VISA_ID_S;
CREATE SEQUENCE KRIM_ENTITY_VISA_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRIM_GRP_ATTR_DATA_ID_S
DROP SEQUENCE KRIM_GRP_ATTR_DATA_ID_S;
CREATE SEQUENCE KRIM_GRP_ATTR_DATA_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRIM_GRP_ID_S
DROP SEQUENCE KRIM_GRP_ID_S;
CREATE SEQUENCE KRIM_GRP_ID_S START WITH 100007 INCREMENT BY 1 NOCACHE;
--KRIM_GRP_MBR_ID_S
DROP SEQUENCE KRIM_GRP_MBR_ID_S;
CREATE SEQUENCE KRIM_GRP_MBR_ID_S START WITH 1379 INCREMENT BY 1 NOCACHE;
/*
KRIM_PERM_ID_S
DROP SEQUENCE KRIM_PERM_ID_S;
CREATE SEQUENCE KRIM_PERM_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
KRIM_PERM_RQRD_ATTR_ID_S
DROP SEQUENCE KRIM_PERM_RQRD_ATTR_ID_S;
CREATE SEQUENCE KRIM_PERM_RQRD_ATTR_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
KRIM_PERM_TMPL_ID_S
DROP SEQUENCE KRIM_PERM_TMPL_ID_S;
CREATE SEQUENCE KRIM_PERM_TMPL_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
*/
--KRIM_PRNCPL_ID_S
DROP SEQUENCE KRIM_PRNCPL_ID_S;
CREATE SEQUENCE KRIM_PRNCPL_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRIM_ROLE_ID_S
DROP SEQUENCE KRIM_ROLE_ID_S;
CREATE SEQUENCE KRIM_ROLE_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRIM_ROLE_MBR_ID_S
DROP SEQUENCE KRIM_ROLE_MBR_ID_S;
CREATE SEQUENCE KRIM_ROLE_MBR_ID_S START WITH 1548 INCREMENT BY 1 NOCACHE;
/*
-KRIM_ROLE_PERM_ID_S
DROP SEQUENCE KRIM_ROLE_PERM_ID_S;
CREATE SEQUENCE KRIM_ROLE_PERM_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
-KRIM_ROLE_RSP_ACTN_ID_S
DROP SEQUENCE KRIM_ROLE_RSP_ACTN_ID_S;
CREATE SEQUENCE KRIM_ROLE_RSP_ACTN_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
-KRIM_ROLE_RSP_ID_S
DROP SEQUENCE KRIM_ROLE_RSP_ID_S;
CREATE SEQUENCE KRIM_ROLE_RSP_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
KRIM_RSP_ID_S
DROP SEQUENCE KRIM_RSP_ID_S;
CREATE SEQUENCE KRIM_RSP_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
KRIM_RSP_RQRD_ATTR_ID_S
DROP SEQUENCE KRIM_RSP_RQRD_ATTR_ID_S;
CREATE SEQUENCE KRIM_RSP_RQRD_ATTR_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
KRIM_RSP_TMPL_ID_S
DROP SEQUENCE KRIM_RSP_TMPL_ID_S;
CREATE SEQUENCE KRIM_RSP_TMPL_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
KRIM_TYP_ATTR_ID_S
DROP SEQUENCE KRIM_TYP_ATTR_ID_S;
CREATE SEQUENCE KRIM_TYP_ATTR_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
KRIM_TYP_ID_S
DROP SEQUENCE KRIM_TYP_ID_S;
CREATE SEQUENCE KRIM_TYP_ID_S START WITH 1 INCREMENT BY 1 NOCACHE;
KRNS_DOC_TYP_ATTR_S
DROP SEQUENCE KRNS_DOC_TYP_ATTR_S;
CREATE SEQUENCE KRNS_DOC_TYP_ATTR_S START WITH 1 INCREMENT BY 1 NOCACHE;
*/
--KRNS_LOCK_S
DROP SEQUENCE KRNS_LOCK_S;
CREATE SEQUENCE KRNS_LOCK_S START WITH 1 INCREMENT BY 1 NOCACHE;
/*
KRNS_LOOKUP_RSLT_S
DROP SEQUENCE KRNS_LOOKUP_RSLT_S;
CREATE SEQUENCE KRNS_LOOKUP_RSLT_S START WITH 1 INCREMENT BY 1 NOCACHE;
*/
--KRNS_MAINT_LOCK_S
DROP SEQUENCE KRNS_MAINT_LOCK_S;
CREATE SEQUENCE KRNS_MAINT_LOCK_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRNS_NTE_S
DROP SEQUENCE KRNS_NTE_S;
CREATE SEQUENCE KRNS_NTE_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRSB_BAM_PARM_S
DROP SEQUENCE KRSB_BAM_PARM_S;
CREATE SEQUENCE KRSB_BAM_PARM_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRSB_BAM_S
DROP SEQUENCE KRSB_BAM_S;
CREATE SEQUENCE KRSB_BAM_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRSB_FLT_SVC_DEF_S
DROP SEQUENCE KRSB_FLT_SVC_DEF_S;
CREATE SEQUENCE KRSB_FLT_SVC_DEF_S START WITH 1 INCREMENT BY 1 NOCACHE;
--KRSB_MSG_QUE_S
DROP SEQUENCE KRSB_MSG_QUE_S;
CREATE SEQUENCE KRSB_MSG_QUE_S START WITH 2488 INCREMENT BY 1 NOCACHE;
--KRSB_SVC_DEF_S
DROP SEQUENCE KRSB_SVC_DEF_S;
CREATE SEQUENCE KRSB_SVC_DEF_S START WITH 1 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_PROTOCOL_EXEMPT_NUMBER_ID;
CREATE SEQUENCE SEQ_PROTOCOL_EXEMPT_NUMBER_ID START WITH 1 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_PROTOCOL_ID;
CREATE SEQUENCE SEQ_PROTOCOL_ID START WITH 13 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_PROTOCOL_REFERENCES_ID;
CREATE SEQUENCE SEQ_PROTOCOL_REFERENCES_ID START WITH 1 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_PROTOCOL_RESEARCH_AREAS_ID;
CREATE SEQUENCE SEQ_PROTOCOL_RESEARCH_AREAS_ID START WITH 1 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_PROTOCOL_SPECIAL_REVIEW_ID;
CREATE SEQUENCE SEQ_PROTOCOL_SPECIAL_REVIEW_ID START WITH 1 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_PROTO_CORRESP_TEMPL;
CREATE SEQUENCE SEQ_PROTO_CORRESP_TEMPL START WITH 1 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_PROTO_NOTIFICATION_TEMPL;
CREATE SEQUENCE SEQ_PROTO_NOTIFICATION_TEMPL START WITH 1 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQUENCE_SUBMISSION_HISTORY;
CREATE SEQUENCE SEQUENCE_SUBMISSION_HISTORY START WITH 1 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_ATTACHMENT_ID;
CREATE SEQUENCE SEQ_ATTACHMENT_ID START WITH 1 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_COMMITTEE_ID;
CREATE SEQUENCE SEQ_COMMITTEE_ID START WITH 25 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_COMM_SCHEDULE_ID;
CREATE SEQUENCE SEQ_COMM_SCHEDULE_ID START WITH 121 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_MEETING_ID;
CREATE SEQUENCE SEQ_MEETING_ID START WITH 8 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_COMM_RESEARCH_AREAS_ID;
CREATE SEQUENCE SEQ_COMM_RESEARCH_AREAS_ID START WITH 2 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_QUESTIONNAIRE_ID;
CREATE SEQUENCE SEQ_QUESTIONNAIRE_ID START WITH 3 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE SEQ_QUESTIONNAIRE_REF_ID;
CREATE SEQUENCE SEQ_QUESTIONNAIRE_REF_ID START WITH 32 INCREMENT BY 1 NOCACHE;

