#created on: Apr 5, 2009
package actionRightMapping

#list any import classes here.

import org.kuali.kra.irb.actions.submit.ActionRightMapping;

#105/106/108/114/115/116

rule "Rule 1 -Part A 105/106/108/114/115/116"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('105','106','108','114','115','116'), unitIndicator == 'leadUnit'))
then	
    actionRight.setRightId("MODIFY_ANY_PROTOCOL");
end

rule "Rule 1 -Part B 105/106/108/114/115/116"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('105','106','108','114','115','116'))
then	
    actionRight.setRightId("SUBMIT_PROTOCOL");
end

#303

rule "Rule 2 -Part A 303"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('303'), unitIndicator == 'leadUnit')
then	
    actionRight.setRightId("MODIFY_ANY_PROTOCOL");
end

rule "Rule 2 -Part B Cond1 303"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('303'), unitIndicator == 'homeUnit', committeeId != null)
then	
    actionRight.setRightId("PERFORM_IRB_ACTIONS_ON_PROTO");
end

rule "Rule 2 -Part B Cond2 303"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('303'), unitIndicator == 'homeUnit', scheduleId != null)
then	
    actionRight.setRightId("PERFORM_IRB_ACTIONS_ON_PROTO");
end

rule "Rule 2 -Part C 303"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('303'))
then	
    actionRight.setRightId("SUBMIT_PROTOCOL");
end

#207/301/300/302/305/306
#//TODO If Committee_id or schedule ID is not available check if the user has PERFORM_IRB_ACTIONS_ON_PROTO in home unit of the committee which last approved the protocol.
rule "Rule 3 Cond1 207/301/300/302/305/306"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('207','301','300','302','305','306'), unitIndicator == 'homeUnit', committeeId != null)
then	
    actionRight.setRightId("PERFORM_IRB_ACTIONS_ON_PROTO");
end

rule "Rule 3 Cond2 207/301/300/302/305/306"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('207','301','300','302','305','306'), unitIndicator == 'homeUnit', scheduleId != null)
then	
    actionRight.setRightId("PERFORM_IRB_ACTIONS_ON_PROTO");
end

#205/206/109/201/200/210/208/209

rule "Rule 4 205/206/109/201/200/210/208/209"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('205','206','109','201','200','210','208','209'), unitIndicator == 'homeUnit')
then	
    actionRight.setRightId("PERFORM_IRB_ACTIONS_ON_PROTO");
end

#202/203/304/204/211/212

rule "Rule 5 -Part A 202/203/304/204/211/212"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('202','203','304','204','211','212'), unitIndicator == 'homeUnit')
then	
    actionRight.setRightId("PERFORM_IRB_ACTIONS_ON_PROTO");
end

rule "Rule 5 -Part B 202/203/304/204/211/212"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('202','203','304','204','211','212'), unitIndicator == 'defaultUnit', scheduleId == null, committeeId == null)
then	
    actionRight.setRightId("PERFORM_IRB_ACTIONS_ON_PROTO");
end

#101

rule "Rule 6 -101"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('101'))
then	
    actionRight.setRightId("SUBMIT_PROTOCOL);
end
