#created on: Apr 5, 2009
package statusActionMapping

#list any import classes here.
import org.kuali.kra.irb.actions.submit.ProtocolAvailableActionMapping;
import java.util.Arrays;

function void setActionTypeCodes(ProtocolAvailableActionMapping protocolAction, String[] actionTypeCodes) {
    protocolAction.setActionTypeCodes(Arrays.asList(actionTypeCodes));    
} 

rule "Check for ProtocolAction for status = 100"
salience 100
when
	protocolAction : ProtocolAvailableActionMapping(submissionTypeCode == "100")
then	
	setActionTypeCodes(protocolAction, new String[] {"200"});
end
