#created on: Apr 5, 2009
package statusActionMapping

#list any import classes here.
import org.kuali.kra.brms.ProtocolStatusActionMapping;
import java.util.Arrays;

function void setActionTypeCodes(ProtocolStatusActionMapping statusAction, String[] actionTypeCodes) {
	//((ProtocolActionService)KraServiceLocator.getService("protocolActionService")).updateStatus(protocolAction.getProtocol(), newStatus);
    statusAction.getProtocol().setActionTypeCodes(Arrays.asList(actionTypeCodes));    
} 

rule "Check for ProtocolAction for status = 100"
salience 100
when
	statusAction : ProtocolStatusActionMapping(protocolStatusCode in ("100","101"))
then	
	setActionTypeCodes(statusAction, new String[] {"100","101","200","300","400"});
	#setActionTypeCodes(statusAction, new String[] {"100","200","300","400"});
end
rule "Check for ProtocolAction for status = 200"
salience 100
when
	statusAction : ProtocolStatusActionMapping(protocolStatusCode in ("200","201"))
then	
	setActionTypeCodes(statusAction, new String[] {"200","300","301"});
end
rule "Check for ProtocolAction for status = 300"
salience 100
when
	statusAction : ProtocolStatusActionMapping(protocolStatusCode in ("300","301"))
then	
	setActionTypeCodes(statusAction, new String[] {"300","301","400"});
end
