DELIMITER /
CREATE TABLE CUST_REPORT_TYPE (
    REPORT_TYPE_CODE INT NOT NULL,
    REPORT_TYPE_DESC VARCHAR(50) NOT NULL,
    UPDATE_USER VARCHAR(60) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL,
 	OBJ_ID VARCHAR(36) NOT NULL)
/


ALTER TABLE CUST_REPORT_TYPE 
ADD CONSTRAINT PK_CUST_REPORT_TYPE 
PRIMARY KEY (REPORT_TYPE_CODE)
/


DELIMITER ;
