DELIMITER /
CREATE TABLE CUST_RPT_DEFAULT_PARMS (
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    REPORT_TYPE_CODE INT NOT NULL,
    CLASS_NAME VARCHAR(100) NOT NULL,
    JAVA_STATEMENTS VARCHAR(2000)  NOT NULL,
    UNIT_FOR_AUTH_CHECK CHAR(1),
    UPDATE_USER VARCHAR(60) NOT NULL,
    UPDATE_TIMESTAMP DATE NOT NULL,
    VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL,
 	OBJ_ID VARCHAR(36) NOT NULL)
/


ALTER TABLE CUST_RPT_DEFAULT_PARMS 
ADD CONSTRAINT PK_CUST_RPT_DEFAULT_PARMS 
PRIMARY KEY (PARAMETER_NAME, REPORT_TYPE_CODE, CLASS_NAME)
/


DELIMITER ;
